export const SKILL_VISUAL_ASSETS:Readonly<Record<string,string>>={
 mercenary_skill_1:'assets/ui/skills/contract_mercenary/mercenary_skill_1.webp',
 mercenary_skill_2:'assets/ui/skills/contract_mercenary/mercenary_skill_2.webp',
 mercenary_skill_3:'assets/ui/skills/contract_mercenary/mercenary_skill_3.webp',
 hunter_skill_1:'assets/ui/skills/hunter/hunter_skill_1.webp',
 hunter_skill_2:'assets/ui/skills/hunter/hunter_skill_2.webp',
 hunter_skill_3:'assets/ui/skills/hunter/hunter_skill_3.webp',
 field_medic_skill_1:'assets/ui/skills/field_medic/field_medic_skill_1.webp',
 field_medic_skill_2:'assets/ui/skills/field_medic/field_medic_skill_2.webp',
 field_medic_skill_3:'assets/ui/skills/field_medic/field_medic_skill_3.webp',
 duelist_skill_1:'assets/ui/skills/duelist/duelist_skill_1.webp',
 duelist_skill_2:'assets/ui/skills/duelist/duelist_skill_2.webp',
 duelist_skill_3:'assets/ui/skills/duelist/duelist_skill_3.webp',
 vanguard_explorer_skill_1:'assets/ui/skills/vanguard_explorer/vanguard_explorer_skill_1.webp',
 vanguard_explorer_skill_2:'assets/ui/skills/vanguard_explorer/vanguard_explorer_skill_2.webp',
 vanguard_explorer_skill_3:'assets/ui/skills/vanguard_explorer/vanguard_explorer_skill_3.webp',
 tracker_skill_1:'assets/ui/skills/tracker/tracker_skill_1.webp',
 tracker_skill_2:'assets/ui/skills/tracker/tracker_skill_2.webp',
 tracker_skill_3:'assets/ui/skills/tracker/tracker_skill_3.webp',
 survivor_skill_1:'assets/ui/skills/survivor/survivor_skill_1.webp',
 survivor_skill_2:'assets/ui/skills/survivor/survivor_skill_2.webp',
 survivor_skill_3:'assets/ui/skills/survivor/survivor_skill_3.webp',
 expedition_medic_skill_1:'assets/ui/skills/expedition_medic/expedition_medic_skill_1.webp',
 expedition_medic_skill_2:'assets/ui/skills/expedition_medic/expedition_medic_skill_2.webp',
 expedition_medic_skill_3:'assets/ui/skills/expedition_medic/expedition_medic_skill_3.webp',
 redeemer_skill_1:'assets/ui/skills/redeemer/redeemer_skill_1.webp',
 redeemer_skill_2:'assets/ui/skills/redeemer/redeemer_skill_2.webp',
 redeemer_skill_3:'assets/ui/skills/redeemer/redeemer_skill_3.webp',
 lantern_keeper_skill_1:'assets/ui/skills/lantern_keeper/lantern_keeper_skill_1.webp',
 lantern_keeper_skill_2:'assets/ui/skills/lantern_keeper/lantern_keeper_skill_2.webp',
 lantern_keeper_skill_3:'assets/ui/skills/lantern_keeper/lantern_keeper_skill_3.webp',
 relic_collector_skill_1:'assets/ui/skills/relic_collector/relic_collector_skill_1.webp',
 relic_collector_skill_2:'assets/ui/skills/relic_collector/relic_collector_skill_2.webp',
 relic_collector_skill_3:'assets/ui/skills/relic_collector/relic_collector_skill_3.webp',
 monster_dismantler_skill_1:'assets/ui/skills/monster_dismantler/monster_dismantler_skill_1.webp',
 monster_dismantler_skill_2:'assets/ui/skills/monster_dismantler/monster_dismantler_skill_2.webp',
 monster_dismantler_skill_3:'assets/ui/skills/monster_dismantler/monster_dismantler_skill_3.webp',
 expedition_archivist_skill_1:'assets/ui/skills/expedition_archivist/expedition_archivist_skill_1.webp',
 expedition_archivist_skill_2:'assets/ui/skills/expedition_archivist/expedition_archivist_skill_2.webp',
 expedition_archivist_skill_3:'assets/ui/skills/expedition_archivist/expedition_archivist_skill_3.webp',
};

export function skillVisualAssetFor(skillId:string|null|undefined):string|null{
 return skillId?SKILL_VISUAL_ASSETS[skillId]??null:null;
}
