import type {ExpeditionEventDefinition} from './types';
import {STRONGHOLD_BALANCE} from './resourceStronghold';
// Authored tower events go here. Test content is NEVER merged into this catalog.
export const EVENT_CATALOG:ExpeditionEventDefinition[]=[
 {id:'common_rest',type:'RECOVERY',title:'바람 잦은 틈',description:'전투가 끝난 자리에 잠시 숨을 고를 틈이 생겼습니다.',weight:1,conditions:[{kind:'PLAYER_HP_BELOW',ratio:.8}],choices:[{id:'rest',label:'숨을 고른다',description:'체력을 조금 회복합니다.',icon:'♥',styleVariant:'PRIMARY',effects:[{kind:'HEAL_HP',ratio:.2}],resultText:'숨을 고르고 체력을 회복했습니다.'},{id:'skip',label:'지나간다',description:'쉬지 않고 이동합니다.',icon:'⇥',styleVariant:'SKIP',effects:[],resultText:'휴식을 뒤로하고 이동합니다.'}]},
 {id:'common_cache',type:'SUPPLY',title:'버려진 보급품',description:'이전 탐사자가 남긴 상자에서 밀봉된 포션이 나왔습니다.',weight:1,choices:[{id:'take',label:'포션을 챙긴다',description:'원정 가방에 넣습니다.',icon:'♥',styleVariant:'PRIMARY',effects:[{kind:'ADD_POTION',potion:'healing_lesser',amount:1}],resultText:'하급 회복 포션을 챙겼습니다.'},{id:'skip',label:'지나간다',description:'무게를 아낍니다.',icon:'⇥',styleVariant:'SKIP',effects:[],resultText:'보급품을 두고 이동합니다.'}]},
 {id:'common_scrap',type:'DISCOVERY',title:'떨어진 잔해',description:'탑의 잔해 사이에서 쓸 만한 재료와 은화가 보입니다.',weight:1,choices:[{id:'search',label:'잔해를 줍는다',description:'원정 임시 보관으로 챙깁니다.',icon:'⌕',styleVariant:'PRIMARY',effects:[{kind:'ADD_TEMP_LOOT',loot:{kind:'MATERIAL',tower:'CURRENT',tier:'CURRENT',amount:2}},{kind:'ADD_EXPEDITION_SILVER',amount:10}],resultText:'재료와 은화를 챙겼습니다.'},{id:'skip',label:'지나간다',description:'손대지 않습니다.',icon:'⇥',styleVariant:'SKIP',effects:[],resultText:'잔해를 두고 이동합니다.'}]},
 {id:'common_risk',type:'RISK',title:'불안한 틈새',description:'깊은 틈새에서 빛이 납니다. 손을 넣으면 다칠 수도 있습니다.',weight:1,choices:[{id:'search',label:'손을 넣어본다',description:'위험을 감수합니다.',icon:'⚠',styleVariant:'DANGER',effects:[],outcomes:[{id:'find',weight:1,effects:[{kind:'ADD_EXPEDITION_SILVER',amount:25}],resultText:'틈새에서 은화를 찾았습니다.'},{id:'injury',weight:1,effects:[{kind:'TAKE_DAMAGE',amount:15}],resultText:'틈새가 무너지며 상처를 입었습니다.'}]},{id:'skip',label:'지나간다',description:'위험을 피합니다.',icon:'⇥',styleVariant:'SKIP',effects:[],resultText:'틈새를 두고 이동합니다.'}]},
 {id:'common_remedy',type:'STATUS',title:'맑은 공기',description:'잠시 맑은 공기가 흘러 몸이 가벼워집니다.',weight:1,choices:[{id:'breathe',label:'깊이 쉰다',description:'상태를 가다듬습니다.',icon:'✦',styleVariant:'PRIMARY',effects:[{kind:'REMOVE_EFFECT',effectId:'poison'},{kind:'HEAL_HP',ratio:.1}],resultText:'몸이 조금 가벼워졌습니다.'},{id:'skip',label:'지나간다',description:'그대로 이동합니다.',icon:'⇥',styleVariant:'SKIP',effects:[],resultText:'그대로 이동합니다.'}]},
 {id:'resource_stronghold',type:'STRONGHOLD',title:'자원거점 발견',description:'고가치 자원이 밀집된 거점을 발견했습니다. 점령을 시작하면 15분 동안 자리를 지켜야 보상을 확보할 수 있습니다.',weight:.65,conditions:[{kind:'FLOOR',min:3,max:10}],decisionMs:STRONGHOLD_BALANCE.decisionMs,choices:[{id:'claim',label:'점령한다',description:'15분 점령을 시작합니다.',icon:'◆',styleVariant:'DANGER',effects:[{kind:'START_RESOURCE_STRONGHOLD'}],resultText:'자원거점 점령을 시작했습니다.'},{id:'skip',label:'지나간다',description:'거점에 개입하지 않습니다.',icon:'⇥',styleVariant:'SKIP',effects:[],resultText:'자원거점을 뒤로하고 탐사를 계속합니다.'}]},
];
export const BOSS_EVENT:ExpeditionEventDefinition={id:'boss_encounter',type:'BOSS',title:'강력한 존재의 흔적',description:'앞쪽에서 거대한 발소리가 들려옵니다. 흔적을 따라가면 이 구역의 보스와 마주할 수 있습니다.',weight:1,conditions:[{kind:'BOSS_FLOOR',value:true}],choices:[{id:'challenge',label:'도전한다',description:'준비를 마치고 보스에게 향합니다.',icon:'⚔',styleVariant:'PRIMARY',effects:[{kind:'START_BOSS_BATTLE'}],resultText:'보스에게 향할 준비를 마쳤습니다.'},{id:'skip',label:'지나간다',description:'이번 흔적을 포기하고 탐사를 계속합니다.',icon:'⇥',styleVariant:'SKIP',effects:[],resultText:'흔적을 뒤로하고 다른 길로 나아갑니다.'}]};
// Asset keys are resolved centrally; missing or failed art receives a neutral placeholder.
export const EVENT_ASSETS:Record<string,string>={dev_mine_backdrop:'./assets/backgrounds/ore/t1.png',potion:'./assets/ui/inventory/health.png',ore:'./assets/ui/inventory/ore.png',silver:'./assets/ui/pixel-v1/13-silver-icon.png'};
export const eventAsset=(key?:string)=>key?EVENT_ASSETS[key]:undefined;
