import {BOSS_EVENT} from './catalog';
import type {EventChoice,ExpeditionEventDefinition} from './types';
const skip:EventChoice={id:'skip',label:'지나간다',description:'더 이상 시간을 낭비하지 않습니다.',icon:'⇥',styleVariant:'SKIP',effects:[],resultText:'발걸음을 옮겨 탐사를 계속합니다.'};
export const DEV_EVENTS:ExpeditionEventDefinition[]=[
 {id:'TEST_RECOVERY_EVENT',type:'RECOVERY',title:'잠깐의 휴식',description:'바람이 잦아든 구석에서 숨을 고를 자리를 발견했습니다.',weight:1,metadata:{fixture:true},choices:[{id:'rest',label:'숨을 고른다',styleVariant:'PRIMARY',effects:[{kind:'HEAL_HP',ratio:.25}],resultText:'잠시 쉬며 체력을 회복했습니다.'},skip]},
 {id:'TEST_SUPPLY_EVENT',type:'SUPPLY',title:'남겨진 보급품',description:'낡은 상자 안에 아직 밀봉된 회복 포션이 남아 있습니다.',weight:1,metadata:{fixture:true},choices:[{id:'take',label:'포션을 챙긴다',styleVariant:'PRIMARY',effects:[{kind:'ADD_POTION',potion:'health',amount:1}],resultText:'회복 포션을 원정 가방에 넣었습니다.'},skip]},
 {id:'TEST_RISK_EVENT',type:'RISK',title:'흔들리는 잔해',description:'무너진 돌무더기 사이에서 무언가 빛납니다. 손을 넣으면 다칠 수도 있습니다.',weight:1,metadata:{fixture:true},choices:[{id:'search',label:'잔해를 조사한다',styleVariant:'DANGER',effects:[],outcomes:[{id:'find',weight:1,effects:[{kind:'ADD_EXPEDITION_SILVER',amount:20}],resultText:'잔해 사이에서 은화를 찾았습니다.'},{id:'injury',weight:1,effects:[{kind:'TAKE_DAMAGE',amount:12}],resultText:'잔해가 무너지며 상처를 입었습니다.'}]},skip]},
 {id:'TEST_DISCOVERY_EVENT',type:'DISCOVERY',imageAssetKey:'dev_mine_backdrop',title:'버려진 광부의 가방',description:'무너진 지지대 아래에서 낡은 탐사 가방을 발견했다.\n아직 쓸 만한 물건이 남아 있을지도 모른다.',weight:1,metadata:{fixture:true},choices:[{id:'search',label:'가방을 조사한다',description:'무엇이 남아 있는지 조심스럽게 살펴봅니다.',icon:'⌕',styleVariant:'PRIMARY',effects:[{kind:'ADD_TEMP_LOOT',loot:{kind:'MATERIAL',tower:'CURRENT',tier:'CURRENT',amount:2}},{kind:'ADD_EXPEDITION_SILVER',amount:10}],resultText:'가방 안에서 쓸 만한 물건을 발견했습니다.'},skip],rewardPreview:[{label:'회복 포션',iconAssetKey:'potion',note:'보급품'},{label:'광석 재료',iconAssetKey:'ore',note:'현재 티어'},{label:'Silver',iconAssetKey:'silver',note:'은화'},{label:'알 수 없는 물건',note:'가능한 발견물'}]},
 {...BOSS_EVENT,id:'TEST_BOSS_EVENT',title:'깊은 곳의 진동',metadata:{fixture:true}}
];
