import type {Expedition} from '../types';
import type {ResourceStrongholdRuntime} from './types';
import {bossIdFor} from '../engine/bossTracking';
const obj=(v:unknown):v is Record<string,any>=>!!v&&typeof v==='object'&&!Array.isArray(v);
const count=(v:unknown)=>typeof v==='number'&&Number.isSafeInteger(v)&&v>=0;
const strings=(v:unknown):v is string[]=>Array.isArray(v)&&v.every(x=>typeof x==='string');
const finite=(v:unknown)=>typeof v==='number'&&Number.isFinite(v);
const STRONGHOLD_TOWERS=['ore','leather','gem','kaleon'];
const stamp=(v:unknown)=>count(v);
const nil=(v:unknown)=>v===null;
const validStronghold=(v:unknown):v is ResourceStrongholdRuntime|null|undefined=>{
 if(v===undefined||v===null)return true;
 if(!obj(v)||typeof v.instanceId!=='string'||!v.instanceId||!['ACTIVE','CONTESTED','COMPLETED','ABANDONED','DELETED'].includes(v.status)||typeof v.ownerUserId!=='string'||!v.ownerUserId||!STRONGHOLD_TOWERS.includes(v.tower)||!count(v.floor)||v.floor<3||v.floor>10||!count(v.version)||v.version<1||!stamp(v.captureStartedAt)||!stamp(v.captureEndsAt)||v.captureEndsAt<=v.captureStartedAt||!obj(v.reward)||v.reward.tower!==v.tower||!count(v.reward.tier)||v.reward.tier<1||v.reward.tier>5||!count(v.reward.materialAmount)||v.reward.materialAmount<1||!count(v.reward.silver))return false;
 if(!(v.contestedByUserId===null||(typeof v.contestedByUserId==='string'&&v.contestedByUserId.length>0))||!(v.contestRemainingMs===null||count(v.contestRemainingMs))||!['completedAt','abandonedAt','deletedAt'].every(k=>v[k]===null||stamp(v[k])))return false;
 if(v.status==='ACTIVE')return nil(v.contestedByUserId)&&nil(v.contestRemainingMs)&&nil(v.completedAt)&&nil(v.abandonedAt)&&nil(v.deletedAt);
 if(v.status==='CONTESTED')return typeof v.contestedByUserId==='string'&&v.contestedByUserId.length>0&&count(v.contestRemainingMs)&&nil(v.completedAt)&&nil(v.abandonedAt)&&nil(v.deletedAt);
 if(v.status==='COMPLETED')return stamp(v.completedAt)&&Number(v.completedAt)>=v.captureEndsAt&&nil(v.abandonedAt)&&nil(v.deletedAt);
 if(v.status==='ABANDONED')return stamp(v.abandonedAt)&&nil(v.completedAt)&&nil(v.deletedAt);
 return stamp(v.deletedAt)&&((stamp(v.completedAt)&&nil(v.abandonedAt))||(stamp(v.abandonedAt)&&nil(v.completedAt)));
};
const compatibleBossId=(tower:unknown,floor:unknown,id:unknown,current:string|null)=>id===current||(tower==='ore'&&floor===10&&id==='mining_ogre');
const validEventInstance=(instanceId:unknown,sequence:number)=>typeof instanceId==='string'&&(instanceId===`event-${sequence}`||/^server-event-[0-9a-f-]+-\d+$/i.test(instanceId));
export function validEventExpedition(value:unknown):value is Expedition|null {if(value===null)return true;if(!obj(value)||!obj(value.events)||!obj(value.bossTracking))return false;const ev=value.events,p=ev.pendingEvent,boss=bossIdFor(value.tower,value.floor),stronghold=ev.stronghold;if(!validStronghold(stronghold)||(obj(stronghold)&&(stronghold.tower!==value.tower||stronghold.floor!==value.floor))||!['BATTLE','EVENT','EVENT_RESULT'].includes(ev.phase)||!['production','test'].includes(ev.mode)||!count(ev.sequence)||!count(ev.bossKillCountThisExpedition)||!strings(ev.recentEventIds)||ev.recentEventIds.length>10||!count(value.bossTracking.progress)||value.bossTracking.pendingBossId!==null||value.bossTracking.encounterReason!==null||(ev.activeBossId!==null&&ev.activeBossId!==boss))return false;
 if(!boss&&(value.bossTracking.progress!==0||ev.bossKillCountThisExpedition!==0))return false;
 if(ev.phase==='BATTLE')return p===null&&['PLAYER_TURN','MONSTER_TURN'].includes(value.phase);
 if(value.phase!=='BATTLE_END'||ev.activeBossId!==null||!obj(p)||!validEventInstance(p.instanceId,ev.sequence)||typeof p.eventId!=='string'||!p.eventId||!['CHOICE','RESULT'].includes(p.state)||(p.bossId!==null&&(!boss||!compatibleBossId(value.tower,value.floor,p.bossId,boss)))||typeof p.resultText!=='string'||!strings(p.resultLines)||!['NORMAL','BOSS'].includes(p.next)||typeof p.randomValue!=='number'||!Number.isFinite(p.randomValue)||p.randomValue<0||p.randomValue>=1||(p.expiresAt!==undefined&&p.expiresAt!==null&&!finite(p.expiresAt))||(p.eventId==='resource_stronghold'&&!finite(p.expiresAt)))return false;
 if(p.next==='BOSS'&&!p.bossId)return false;
 if(p.bossId&&value.bossTracking.progress!==0)return false;
 return ev.phase==='EVENT'?p.state==='CHOICE'&&p.choiceId===null&&p.outcomeId===null&&p.resultLines.length===0&&p.next==='NORMAL':p.state==='RESULT'&&typeof p.choiceId==='string'&&(p.outcomeId===null||typeof p.outcomeId==='string');
}
