import test from 'node:test';import assert from 'node:assert/strict';import {initialState} from '../src/game/engine/state.ts';import {ASSOCIATION_CREATION_FEE_SILVER,createAssociation,joinAssociation,leaveAssociation,reviewApplication} from '../src/game/association/service.ts';
const eligible=()=>{const s=initialState();s.market.traderCertified=true;s.silver=ASSOCIATION_CREATION_FEE_SILVER;return s;};
test('조합 01: 자격을 가진 한 명은 Silver 등록금으로 단독 창설한다',()=>{const s=eligible(),n=createAssociation(s,{name:'검은등불',description:'탐사',joinPolicy:'APPROVAL'},100);assert.equal(n.silver,0);assert.equal(n.association.associations[0].members.length,1);assert.equal(n.association.associations[0].members[0].role,'LEADER');assert.equal(n.association.associations[0].recordNumber,'NR-000001');});
test('조합 02: 자격·등록금·이름 검증 실패는 원자적으로 거부한다',()=>{let s=initialState();s.silver=999;assert.equal(createAssociation(s,{name:'조합',description:'',joinPolicy:'OPEN'}).association.associations.length,0);s=eligible();assert.equal(createAssociation(s,{name:'탑기록원',description:'',joinPolicy:'OPEN'}).association.associations.length,0);assert.equal(createAssociation(s,{name:' ',description:'',joinPolicy:'OPEN'}).silver,ASSOCIATION_CREATION_FEE_SILVER);});
test('조합 03: 조합장은 직접 탈퇴할 수 없다',()=>{const n=createAssociation(eligible(),{name:'은빛등불',description:'',joinPolicy:'OPEN'});assert.match(leaveAssociation(n).notice,/위임 또는 해산/);});
test('조합 04: 자유 가입과 승인 가입은 각각 소속·신청 기록을 남긴다',()=>{const leader=createAssociation(eligible(),{name:'자유등불',description:'',joinPolicy:'OPEN'},100),id=leader.association.currentId!;const guest=structuredClone(leader);guest.market.ownerId='guest';guest.association.currentId=null;const joined=joinAssociation(guest,id,200);assert.equal(joined.association.currentId,id);assert.equal(joined.association.associations[0].members.length,2);const approval=createAssociation(eligible(),{name:'승인등불',description:'',joinPolicy:'APPROVAL'},100),guest2=structuredClone(approval);guest2.market.ownerId='guest';guest2.association.currentId=null;const requested=joinAssociation(guest2,approval.association.currentId!,200);assert.equal(requested.association.associations[0].applications[0].status,'PENDING');});
test('조합 05: 조합장은 승인 신청을 멤버로 전환한다',()=>{const leader=createAssociation(eligible(),{name:'기록등불',description:'',joinPolicy:'APPROVAL'},100),guest=structuredClone(leader);guest.market.ownerId='guest';guest.association.currentId=null;const requested=joinAssociation(guest,leader.association.currentId!,200),reviewed=reviewApplication({...leader,association:{...requested.association,currentId:leader.association.currentId}},'application-1',true,300);assert.equal(reviewed.association.associations[0].applications[0].status,'ACCEPTED');assert.equal(reviewed.association.associations[0].members.some(m=>m.playerId==='guest'),true);});


