import test from 'node:test';import assert from 'node:assert/strict';
import {monsterSkillThreats,chargeInterrupted,shieldFeedback} from '../src/components/battle/combatIntel';
import {initialState} from '../src/game/engine/state';import {enter} from '../src/game/engine/expedition';import {createMonsterRuntime} from '../src/game/engine/monsterAi';import {applyEffect} from '../src/game/engine/effects';
function prepared(){const e=enter(initialState(),'ore',1).expedition!;e.monster.definitionId='iron_maw_burrower';e.monsterRuntime=createMonsterRuntime(e.monster);e.monsterRuntime.preparedActionId='burrow_charge';return e;}
test('threats describe actual multi-hit penetration and effect metadata',()=>{const text=monsterSkillThreats({id:'test',name:'test',description:'',kind:'charge',cooldown:1,hits:3,penetrationRate:.4,effects:[{target:'TARGET',effectId:'stun'},{target:'SELF',effectId:'attack_up'}]});assert.match(text,/연속 타격 3회/);assert.match(text,/방어 관통 40%/);assert.match(text,/기절/);assert.match(text,/자신/);assert.equal(monsterSkillThreats({id:'plain',name:'',description:'',kind:'charge',cooldown:1}),'단일 타격');});
test('only a living stunned monster cancelling its prepared attack counts as interruption',()=>{const before=prepared(),after=structuredClone(before);applyEffect(after,'monster','stun','player',0);assert.equal(chargeInterrupted(before,after),true);after.monster.currentHp=0;assert.equal(chargeInterrupted(before,after),false);const cancelled=prepared();cancelled.monsterRuntime!.preparedActionId=null;assert.equal(chargeInterrupted(before,cancelled),false);assert.equal(chargeInterrupted(before,prepared()),false);});
test('shield feedback distinguishes absorption and full defense including hit shields',()=>{assert.equal(shieldFeedback({outcome:'BLOCKED_BY_SHIELD',absorbedByShield:0,hpDamage:0}),'보호막 방어!');assert.equal(shieldFeedback({absorbedByShield:15,hpDamage:4}),'보호막 흡수');assert.equal(shieldFeedback({absorbedByShield:0,hpDamage:15}),null);});

test('interruption survives a stun expiring during the completed monster turn',()=>{const before=prepared(),after=structuredClone(before);applyEffect(after,'monster','stun','player',0);after.monsterEffects=[];assert.equal(chargeInterrupted(before,after),true);});
