import test from 'node:test';
import assert from 'node:assert/strict';
import {initialState,stats} from '../src/game/engine/state';
import {enter} from '../src/game/engine/expedition';
import {basicAttack,passPlayerTurn,resolveMonsterTurn,useBattlePotion,useBattleSkill} from '../src/game/engine/combat';
import {applyEffect,effectStacks,hasEffect,EFFECTS,validateEffectDefinitions} from '../src/game/engine/effects';
import {resolveDirectHits} from '../src/game/engine/directHits';
import {resolveActorDirectHits} from '../src/game/engine/monsterSkills';
import {consumeDirectHitReaction,prepareReactive,reactivePreparedSkill} from '../src/game/engine/reactions';
import {chooseMonsterAction,createMonsterRuntime,TEST_MONSTER_REACTIVE,TEST_MONSTER_STATUS,TEST_MONSTER_SELF_STATUS,validateMonsterDefinition,type MonsterDefinition,type MonsterSkillDefinition} from '../src/game/engine/monsterAi';
import {createRepository,COMBAT_TRIGGERS_BACKUP_KEY,migrateV18,SAVE_KEY,validSave} from '../src/storage/repository';
import {initialEvents,openEvent,resolveEvent} from '../src/game/events/service';
import {DEV_EVENTS} from '../src/game/events/fixtures';

const noEvent=()=>.99;
const reactiveState=()=>{const s=enter(initialState(),'ore',1),e=s.expedition!;e.monster={definitionId:TEST_MONSTER_REACTIVE.id,name:'반격 훈련체',hp:1000,currentHp:1000,attack:20,defense:0,speed:1,skillPower:1};e.monsterRuntime=createMonsterRuntime(e.monster);e.phase='MONSTER_TURN';return resolveMonsterTurn(s);};
const prepareSkill=TEST_MONSTER_REACTIVE.skills!.find(skill=>skill.kind==='reactive_prepare')!;
const memory=(raw?:string)=>{const map=new Map<string,string>();if(raw)map.set(SAVE_KEY,raw);return {map,repo:createRepository({getItem:key=>map.get(key)??null,setItem:(key,value)=>void map.set(key,value)})};};

test('DIRECT HIT 01-07: both actors and every hit emit direct-hit points, while death/DOT/event damage never fires a reaction',()=>{let s=enter(initialState(),'ore',1),e=s.expedition!,observed=0;const direct=resolveDirectHits(e,'player','monster',3,()=>1,()=>observed++);assert.equal(direct.triggerPoints,3);assert.equal(observed,3);prepareReactive(e,'monster',TEST_MONSTER_REACTIVE.id,prepareSkill);e.monster.currentHp=1;const lethal=resolveDirectHits(e,'player','monster',1,()=>1,()=>consumeDirectHitReaction(e,'monster'));assert.equal(lethal.triggerPoints,1);assert.ok(e.reactivePrepared.monster);s=reactiveState();applyEffect(s.expedition!,'monster','poison','player',s.expedition!.playerTurn);const pending=s.expedition!.reactivePrepared.monster;s=passPlayerTurn(s,noEvent);s=resolveMonsterTurn(s);assert.deepEqual(s.expedition!.reactivePrepared.monster,pending);s=reactiveState();prepareReactive(s.expedition!,'player',TEST_MONSTER_REACTIVE.id,prepareSkill);const hp=s.expedition!.hp;resolveActorDirectHits(s,'monster');assert.ok(s.expedition!.hp<hp);assert.equal(s.expedition!.reactivePrepared.player,null);let event=enter(initialState(),'ore',1);event.expedition!.events=initialEvents('test');event.expedition!.monster.currentHp=0;openEvent(event,DEV_EVENTS.find(x=>x.id==='TEST_RISK_EVENT')!,()=>.9);prepareReactive(event.expedition!,'player',TEST_MONSTER_REACTIVE.id,prepareSkill);const id=event.expedition!.events.pendingEvent!.instanceId;event=resolveEvent(event,id,'search');assert.ok(event.expedition!.reactivePrepared.player);});

test('REACTIVE 08-16: prepare consumes one turn, starts cooldown, persists pending, then fires once without another turn or cooldown reset',()=>{let s=enter(initialState(),'ore',1),e=s.expedition!;e.monster={definitionId:TEST_MONSTER_REACTIVE.id,name:'반격 훈련체',hp:1000,currentHp:1000,attack:20,defense:0,speed:1,skillPower:1};e.monsterRuntime=createMonsterRuntime(e.monster);e.phase='MONSTER_TURN';const beforeHp=e.hp;s=resolveMonsterTurn(s);e=s.expedition!;assert.equal(e.phase,'PLAYER_TURN');assert.equal(e.monsterRuntime!.turnNumber,1);assert.equal(e.monsterRuntime!.skillCooldowns.counter_stance,3);assert.ok(e.reactivePrepared.monster);const cooldown=e.monsterRuntime!.skillCooldowns.counter_stance,turn=e.monsterRuntime!.turnNumber;s=basicAttack(s,noEvent);assert.ok(s.expedition!.hp<beforeHp);assert.equal(s.expedition!.reactivePrepared.monster,null);assert.equal(s.expedition!.monsterRuntime!.turnNumber,turn);assert.equal(s.expedition!.monsterRuntime!.skillCooldowns.counter_stance,cooldown);assert.match(s.logs.join('\n'),/준비된 행동 소모/);assert.match(s.logs.join('\n'),/즉시 발동/);});

test('REACTIVE 17-22: DOT, item and non-damage actions do not fire; reload fires exactly once; cleanup prevents carryover',()=>{let s=reactiveState(),pending=structuredClone(s.expedition!.reactivePrepared.monster);s=useBattlePotion(s,'healing_lesser',noEvent);assert.deepEqual(s.expedition!.reactivePrepared.monster,pending);s=resolveMonsterTurn(s);s=useBattleSkill(s,'quick',noEvent);assert.deepEqual(s.expedition!.reactivePrepared.monster,pending);s=resolveMonsterTurn(s);applyEffect(s.expedition!,'monster','poison','player',s.expedition!.playerTurn);s=passPlayerTurn(s,noEvent);s=resolveMonsterTurn(s);assert.deepEqual(s.expedition!.reactivePrepared.monster,pending);const {repo}=memory();repo.save(s);s=repo.load();s=basicAttack(s,noEvent);assert.equal(s.expedition!.reactivePrepared.monster,null);const reactionLogs=s.logs.filter(line=>line.includes('즉시 발동')).length;s=resolveMonsterTurn(s);assert.equal(s.logs.filter(line=>line.includes('즉시 발동')).length,reactionLogs);s.expedition!.phase='PLAYER_TURN';s.expedition!.monster.currentHp=1;s=basicAttack(s,noEvent);assert.deepEqual(s.expedition!.reactivePrepared,{player:null,monster:null});assert.ok(s.expedition!.monsterRuntime);});

test('REACTIVE replacement and validation: one slot replaces explicitly and invalid definitions are reported safely',()=>{const s=enter(initialState(),'ore',1),e=s.expedition!,second={...prepareSkill,id:'counter_stance_2'} satisfies MonsterSkillDefinition;prepareReactive(e,'monster',TEST_MONSTER_REACTIVE.id,prepareSkill);prepareReactive(e,'monster',TEST_MONSTER_REACTIVE.id,second);assert.equal(e.reactivePrepared.monster?.prepareSkillId,'counter_stance_2');const bad:MonsterDefinition={id:'bad-reactive',name:'bad',skills:[{id:'loop',name:'loop',description:'',cooldown:1,kind:'reactive_prepare',reactiveTrigger:'DIRECT_HIT_RECEIVED',reactionSkillId:'loop'}],aiRules:[]};assert.ok(validateMonsterDefinition(bad).length>0);});

test('MULTI REACTION 23-27: one counter, continuation on survival, stop on attacker death, and no reaction chain',()=>{let s=reactiveState();const turn=s.expedition!.monsterRuntime!.turnNumber,result=resolveActorDirectHits(s,'player',3,.2);assert.equal(result.hits.length,3);assert.equal(s.logs.filter(line=>line.includes('즉시 발동')).length,1);assert.equal(s.expedition!.monsterRuntime!.turnNumber,turn);s=reactiveState();s.expedition!.hp=1;const lethal=resolveActorDirectHits(s,'player',3,.2);assert.equal(lethal.hits.length,1);assert.equal(s.expedition!.hp,0);s=reactiveState();prepareReactive(s.expedition!,'player',TEST_MONSTER_REACTIVE.id,prepareSkill);resolveActorDirectHits(s,'player',1,.2);assert.ok(s.expedition!.reactivePrepared.player);assert.equal(s.expedition!.reactivePrepared.monster,null);});

test('STACK 28-36: crossing fires once, removes/applies deterministically, can rebuild, and survives reload',()=>{let s=enter(initialState(),'ore',1),e=s.expedition!;applyEffect(e,'monster','test_armor','monster',0);let r=applyEffect(e,'monster','test_crack','player',1)!;assert.equal(r.newStacks,1);assert.equal(r.thresholdTriggered,false);r=applyEffect(e,'monster','test_crack','player',1)!;assert.equal(r.newStacks,2);assert.equal(r.thresholdTriggered,false);r=applyEffect(e,'monster','test_crack','player',1)!;assert.equal(r.thresholdTriggered,true);assert.equal(hasEffect(e.monsterEffects,'test_crack'),false);assert.equal(hasEffect(e.monsterEffects,'test_armor'),false);assert.equal(hasEffect(e.monsterEffects,'test_exposed'),true);assert.equal(applyEffect(e,'monster','test_crack','player',1)!.thresholdTriggered,false);applyEffect(e,'monster','test_crack','player',1);assert.equal(applyEffect(e,'monster','test_crack','player',1)!.thresholdTriggered,true);for(let i=0;i<3;i++)r=applyEffect(e,'player','test_latched_stack','monster',1)!;assert.equal(r.thresholdTriggered,true);assert.equal(applyEffect(e,'player','test_latched_stack','monster',1)!.thresholdTriggered,false);applyEffect(e,'monster','test_resonance','player',1);applyEffect(e,'monster','test_resonance','player',1);const {repo}=memory();repo.save(s);s=repo.load();assert.equal(effectStacks(s.expedition!.monsterEffects,'test_resonance'),2);});

test('STATUS AI 37-47: has/missing/stack/AND/priority and invalid data are deterministic with safe fallback',()=>{const monster={definitionId:TEST_MONSTER_STATUS.id,name:'AI',hp:100,currentHp:100,attack:10,defense:0,speed:1,skillPower:1},runtime=createMonsterRuntime(monster),base=enter(initialState(),'ore',1).expedition!;let choice=chooseMonsterAction(TEST_MONSTER_STATUS,runtime,monster,100,100,[],[]);assert.equal(choice.kind,'BASIC_ATTACK');applyEffect(base,'player','test_resonance','monster',0);choice=chooseMonsterAction(TEST_MONSTER_STATUS,runtime,monster,100,100,[],base.playerEffects);assert.equal(choice.skill?.id,'test_pressure');applyEffect(base,'player','test_resonance','monster',0);applyEffect(base,'player','test_resonance','monster',0);choice=chooseMonsterAction(TEST_MONSTER_STATUS,runtime,monster,100,100,[],base.playerEffects);assert.equal(choice.skill?.id,'test_burst');choice=chooseMonsterAction(TEST_MONSTER_SELF_STATUS,createMonsterRuntime({...monster,definitionId:TEST_MONSTER_SELF_STATUS.id}),monster,100,100,[],[]);assert.equal(choice.skill?.id,'restore_armor');applyEffect(base,'monster','test_armor','monster',0);choice=chooseMonsterAction(TEST_MONSTER_SELF_STATUS,createMonsterRuntime({...monster,definitionId:TEST_MONSTER_SELF_STATUS.id}),monster,100,100,base.monsterEffects,[]);assert.equal(choice.skill?.id,'armored_strike');const both:MonsterDefinition={id:'both',name:'both',skills:[{id:'x',name:'x',description:'',cooldown:1,kind:'damage'}],aiRules:[{id:'and',priority:1,actionId:'x',conditions:[{kind:'TARGET_HAS_EFFECT',effectId:'test_resonance'},{kind:'SELF_HAS_EFFECT',effectId:'test_armor'}]}]};assert.equal(chooseMonsterAction(both,runtime,monster,100,100,[],base.playerEffects).kind,'BASIC_ATTACK');assert.equal(chooseMonsterAction(both,runtime,monster,100,100,base.monsterEffects,base.playerEffects).skill?.id,'x');const invalid:MonsterDefinition={...both,aiRules:[{id:'bad',priority:99,actionId:'x',conditions:[{kind:'TARGET_HAS_EFFECT',effectId:'unknown'}]}]};assert.equal(chooseMonsterAction(invalid,runtime,monster,100,100,base.monsterEffects,base.playerEffects).kind,'BASIC_ATTACK');assert.ok(validateMonsterDefinition(invalid).length>0);assert.equal(effectStacks([], 'test_resonance'),0);});

test('STATUS AI production path chooses effect-stack action without mutating effects',()=>{let s=enter(initialState(),'ore',1),e=s.expedition!;e.monster={definitionId:TEST_MONSTER_STATUS.id,name:'상태 AI 훈련체',hp:100,currentHp:100,attack:10,defense:0,speed:1,skillPower:1};e.monsterRuntime=createMonsterRuntime(e.monster);for(let i=0;i<3;i++)applyEffect(e,'player','test_resonance','monster',0);const before=structuredClone(e.playerEffects);e.phase='MONSTER_TURN';s=resolveMonsterTurn(s);assert.match(s.logs.join('\n'),/TEST_BURST/);assert.deepEqual(s.expedition!.playerEffects,before);});

test('SAVE v18→v21 preserves battle state, initializes reactions, backs up once, and rejects backup failure',()=>{const current=enter(initialState(),'ore',1),legacy:any=structuredClone(current);legacy.version=18;delete legacy.expedition.reactivePrepared;legacy.expedition.hp=77;legacy.expedition.monster.currentHp=19;legacy.expedition.monsterRuntime.preparedActionId='charge';legacy.expedition.playerEffects.push({instanceId:'legacy',effectId:'guard',sourceActorId:'player',targetActorId:'player',remainingDuration:2,stackCount:1,applicationSequence:99,createdTurn:1,scope:'BATTLE'});const migrated=migrateV18(legacy);assert.equal(migrated.version,21);assert.equal(migrated.expedition!.hp,77);assert.equal(migrated.expedition!.monster.currentHp,19);assert.equal(migrated.expedition!.monsterRuntime!.preparedActionId,'charge');assert.equal(migrated.expedition!.playerEffects.length,1);assert.deepEqual(migrated.expedition!.reactivePrepared,{player:null,monster:null});assert.ok(validSave(migrated));const raw=JSON.stringify(legacy),{map,repo}=memory(raw);repo.load();assert.equal(map.get(COMBAT_TRIGGERS_BACKUP_KEY),raw);repo.load();assert.equal(map.get(COMBAT_TRIGGERS_BACKUP_KEY),raw);let main=raw,writes=0;const failing=createRepository({getItem:key=>key===SAVE_KEY?main:null,setItem:(key,value)=>{writes++;if(key===COMBAT_TRIGGERS_BACKUP_KEY)throw Error('full');if(key===SAVE_KEY)main=value;}});assert.throws(()=>failing.load());assert.equal(writes,1);assert.equal(main,raw);});

test('Charge and Reactive keep independent single slots',()=>{const s=enter(initialState(),'ore',1),e=s.expedition!,definition:MonsterDefinition={id:'combined',name:'combined',skills:[{id:'charge',name:'charge',description:'',cooldown:2,kind:'charge'},{id:'stance',name:'stance',description:'',cooldown:2,kind:'reactive_prepare',reactiveTrigger:'DIRECT_HIT_RECEIVED',reactionSkillId:'counter'},{id:'counter',name:'counter',description:'',cooldown:0,kind:'damage'}],aiRules:[]};e.monsterRuntime!.preparedActionId='charge';prepareReactive(e,'monster',TEST_MONSTER_REACTIVE.id,prepareSkill);const choice=chooseMonsterAction(definition,e.monsterRuntime!,e.monster,e.hp,stats(s).hp,e.monsterEffects,e.playerEffects);assert.equal(choice.kind,'PREPARED_DISCHARGE');assert.ok(e.reactivePrepared.monster);});

test('UI contracts expose reactive labels and stack values without engine-side mutation',()=>{const s=reactiveState(),e=s.expedition!;assert.equal(reactivePreparedSkill(e,'monster')?.prepare.name,'TEST_COUNTER 준비');for(let i=0;i<2;i++)applyEffect(e,'player','test_resonance','monster',e.playerTurn);assert.equal(effectStacks(e.playerEffects,'test_resonance'),2);assert.equal(EFFECTS.test_resonance.name,'TEST_RESONANCE');assert.deepEqual(validateEffectDefinitions(),[]);const invalid={bad:{...EFFECTS.test_crack,id:'bad',thresholdReaction:{threshold:0,applyEffectIds:['missing']}}};assert.ok(validateEffectDefinitions(invalid).length>=2);assert.equal(stats(s).hp,180);});

