import test from 'node:test';
import assert from 'node:assert/strict';
import {initialState} from '../src/game/engine/state';
import {autoEquip,bestEquipmentIds,isEquipmentUpgrade} from '../src/game/engine/equipmentAutoEquip';
const fixture=()=>{const s=initialState();s.equipmentItems=[{id:'sword',kind:'association_supply_iron_sword',grade:'rare',enhancement:0},{id:'bow',kind:'outer_guard_longbow',grade:'legendary',enhancement:0},{id:'better-sword',kind:'association_supply_iron_sword',grade:'heroic',enhancement:0},{id:'helmet',kind:'expedition_iron_helmet',grade:'common',enhancement:0}];s.equipped.weapon='sword';return s;};
test('automatic equipment and upgrade hints preserve weapon kind and fill empty slots',()=>{const s=fixture();assert.deepEqual(bestEquipmentIds(s),['better-sword','helmet']);assert.equal(isEquipmentUpgrade(s,'bow'),false);assert.equal(isEquipmentUpgrade(s,'better-sword'),true);const next=autoEquip(s);assert.equal(next.equipped.weapon,'better-sword');assert.equal(next.equipped.helmet,'helmet');assert.equal(s.equipped.weapon,'sword');assert.deepEqual(bestEquipmentIds(next),[]);});
test('empty weapon chooses highest grade with sword winning grade ties',()=>{const s=fixture();s.equipped.weapon=null;assert.equal(autoEquip(s).equipped.weapon,'bow');s.equipmentItems[0].grade='legendary';assert.equal(autoEquip(s).equipped.weapon,'sword');});
test('equal grades keep equipped identity and expeditions prevent changes',()=>{const s=fixture();s.equipmentItems[2].grade='rare';assert.equal(isEquipmentUpgrade(s,'better-sword'),false);assert.equal(autoEquip(s).equipped.weapon,'sword');s.expedition={} as any;assert.deepEqual(autoEquip(s).equipped,s.equipped);});

test('inventory renders auto equip and accessible upgrade hints',async()=>{const React=await import('react');const {renderToStaticMarkup}=await import('react-dom/server');const {InventoryScreen}=await import('../src/components/inventory/InventoryScreen');const html=renderToStaticMarkup(React.createElement(InventoryScreen,{game:fixture(),setGame:()=>{},onEnhancement:()=>{}}));assert.match(html,/자동 장착/);assert.equal((html.match(/aria-label="현재 장비보다 상위 등급"/g)||[]).length,2);});
