import test from 'node:test';import assert from 'node:assert/strict';import {PGlite} from '@electric-sql/pglite';import {readFileSync} from 'node:fs';
import {EQUIPMENT_DEFINITIONS,EQUIPMENT_GRADES,equipmentItemStats} from '../src/game/data/equipment';
const u='11111111-1111-4111-8111-111111111111',v='22222222-2222-4222-8222-222222222222';
test('fixed catalog SQL resets retired stock, refunds bids, matches all 45 effects and batches one product',async()=>{const db=new PGlite();try{
await db.exec(`create schema private;create schema realtime;create role anon;create role authenticated;
create table public.game_saves(user_id uuid primary key,payload jsonb,revision bigint default 1);
create table private.player_wallets(user_id uuid primary key,silver bigint,updated_at timestamptz);
create table private.market_assets(user_id uuid,item_id text,quantity bigint,gear jsonb,updated_at timestamptz,primary key(user_id,item_id));
create table private.market_orders(order_id uuid primary key default gen_random_uuid(),user_id uuid,item_id text,side text,limit_price bigint,original_quantity bigint,remaining_quantity bigint,status text,gear jsonb,escrow_gear jsonb default '[]',created_at timestamptz default now(),expires_at timestamptz default now()+interval '30 days',updated_at timestamptz);
create table private.market_trades(trade_id uuid default gen_random_uuid(),item_id text,price bigint,quantity bigint,buy_order_id uuid,sell_order_id uuid,buyer_id uuid,seller_id uuid);
create table private.market_storage(user_id uuid,item_id text,silver bigint);
create table private.equipment_market_listings(status text,updated_at timestamptz);
create table private.game_mail(attachment_gear jsonb,attachment_item_id text,attachment_quantity bigint,attachment_assets jsonb default '[]');
create table private.online_expeditions(user_id uuid,status text,equipment_snapshot jsonb,temporary_loot jsonb,run_version bigint);
create table private.player_association_seals(user_id uuid,level int);
create table private.village_life_players(user_id uuid,materials jsonb);
create function private.require_active_game_session(uuid,bigint,text,text) returns uuid language sql as $$select $1$$;
create function private.village_life_user(uuid,bigint,text,text) returns uuid language sql as $$select $1$$;
create function private.sync_market_economy_from_latest_save(uuid) returns bigint language sql as $$select 1::bigint$$;
create function private.persist_market_economy_to_save(uuid) returns void language sql as $$select$$;
create function private.persist_client_payload_with_server_economy(uuid,jsonb,text) returns void language sql as $$update public.game_saves set payload=$2 where user_id=$1$$;
create function private.association_seal_bonus_json(int) returns jsonb language sql as $$select '{}'::jsonb$$;
create function private.refresh_village_life(uuid) returns jsonb language sql as $$select '{}'::jsonb$$;
create function private.cloud_record_json(uuid) returns jsonb language sql as $$select '{}'::jsonb$$;
create function private.market_state_json(uuid) returns jsonb language sql as $$select '{}'::jsonb$$;
create function private.market_order_mail(uuid,text) returns void language sql as $$select$$;
create function realtime.send(jsonb,text,text,boolean) returns void language sql as $$select$$;
create function private.deliver_market_asset(uuid,text,bigint,jsonb) returns void language sql as $$insert into private.market_assets values($1,'equipment_v2:'||($4->>'id'),$3,$4,now())$$;
insert into public.game_saves values('${u}','{"expedition":null,"items":[],"equipmentItems":[],"equipped":{},"lootItems":{}}',1),('${v}','{"expedition":null,"items":[],"equipmentItems":[],"equipped":{},"lootItems":{}}',1);
insert into private.player_wallets values('${u}',1000,now()),('${v}',1000,now());
insert into private.market_assets values('${u}','equipment_v2:old',1,'{"id":"old","kind":"outer_guard_longbow","grade":"rare","enhancement":10}',now());
insert into private.market_orders(user_id,item_id,side,limit_price,original_quantity,remaining_quantity,status) values('${u}','equipment:outer_guard_longbow:rare:+10','BUY',100,3,2,'PARTIAL');
insert into private.game_mail values('{"id":"old"}','equipment_v2:old',1,'[{"id":"raw-old","kind":"outer_guard_longbow","grade":"rare","enhancement":10},{"itemId":"equipment_v2:old","gear":{"id":"old"}},{"itemId":"material:ore:1","quantity":3}]');
`);
await db.exec(readFileSync(new URL('../supabase/migrations/20261008142245_fixed_equipment_catalog.sql',import.meta.url),'utf8'));
assert.equal((await db.query<any>(`select silver::int from private.player_wallets where user_id='${u}'`)).rows[0].silver,1200);
assert.equal((await db.query<any>(`select count(*)::int n from private.market_assets where item_id='equipment_v2:old'`)).rows[0].n,0);
const mail=(await db.query<any>('select * from private.game_mail')).rows[0];assert.equal(mail.attachment_gear,null);assert.equal(mail.attachment_assets.length,1);
for(const kind of Object.keys(EQUIPMENT_DEFINITIONS))for(const grade of EQUIPMENT_GRADES){const b=(await db.query<any>('select private.fixed_equipment_stats($1,$2) b',[kind,grade])).rows[0].b;assert.deepEqual(b,equipmentItemStats({id:'x',kind,grade,enhancement:0} as any));}
const gears=[{id:'r1',kind:'expedition_merit_ring',grade:'rare',enhancement:0},{id:'r2',kind:'expedition_merit_ring',grade:'rare',enhancement:0}];
for(const g of gears)await db.query(`insert into private.market_assets values($1,$2,1,$3::jsonb,now())`,[u,'equipment_v2:'+g.id,JSON.stringify(g)]);
await db.query(`select public.place_online_market_order($1,1,'c','d',$2,'SELL',50,2)`,[u,'equipment_v2:r1']);
const order=(await db.query<any>(`select * from private.market_orders where status='OPEN'`)).rows[0];assert.equal(order.item_id,'equipment:expedition_merit_ring:rare');assert.equal(order.escrow_gear.length,2);
await db.query(`select public.place_online_market_order($1,1,'c','d',$2,'BUY',50,2)`,[v,order.item_id]);
assert.equal((await db.query<any>(`select count(*)::int n from private.market_assets where user_id='${v}' and item_id in('equipment_v2:r1','equipment_v2:r2')`)).rows[0].n,2);
await assert.rejects(()=>db.query(`select public.place_online_market_order($1,1,'c','d','equipment:expedition_merit_ring:rare:+3','BUY',50,1)`,[v]),/EQUIPMENT_MARKET_ITEM_INVALID/);
assert.equal((await db.query<any>(`select has_function_privilege('authenticated','public.enhance_online_equipment(uuid,bigint,text,text,text)','EXECUTE') ok`)).rows[0].ok,false);
await db.exec(`insert into private.village_life_players values('${v}','{"stone":0}');`);
const dis=(await db.query<any>(`select public.dismantle_online_equipment('${v}',1,'c','d','r1') r`)).rows[0].r;assert.equal(dis.stones,0);assert.equal(dis.splitStones,4);
assert.equal((await db.query<any>(`select count(*)::int n from private.market_assets where item_id='other:enhancement_stone'`)).rows[0].n,0);
}finally{await db.close();}});
