import test from 'node:test';import assert from 'node:assert/strict';
import {initialState} from '../src/game/engine/state.ts';import {enter} from '../src/game/engine/expedition.ts';
import {inventoryView,selectInventory,categories} from '../src/game/inventoryView.ts';
const fixture=()=>{const s=initialState();s.materials.ore[0]=12;s.materials.gem[2]=4;s.skillBooks={execute:2,heavy:3};s.cosmetics.appearanceItems.default=1;s.lootItems.fragment=2;s.items.push({id:'new',kind:'sword',tier:3,enhancement:2});return s;};
test('inventory normalize categories and positive quantities',()=>{const a=inventoryView(fixture());assert.equal(categories.length,8);assert.equal(new Set(a.map(i=>i.category)).size,7);assert.ok(a.every(i=>i.quantity>0));assert.equal(new Set(a.map(i=>i.key)).size,a.length);});
test('inventory excludes expedition loot and does not mutate',()=>{const s=enter(fixture(),'ore',1);s.expedition!.loot.materials.ore[0]=999;const before=JSON.stringify(s),a=inventoryView(s);assert.equal(a.find(i=>i.key==='materials:ore:0')?.quantity,12);selectInventory(a,'all','', 'tier');assert.equal(JSON.stringify(s),before);});
test('inventory category and search filters',()=>{const a=inventoryView(fixture());assert.ok(selectInventory(a,'potions').every(i=>i.category==='potions'));assert.equal(selectInventory(a,'all','3등급').length,1);assert.equal(selectInventory(a,'all','없는물건').length,0);});
test('inventory name tier quantity sorting',()=>{const a=inventoryView(fixture());const names=selectInventory(a,'all','','name');assert.deepEqual(names.map(i=>i.name),a.map(i=>i.name).sort((a,b)=>a.localeCompare(b,'ko')));const tiers=selectInventory(a,'all','','tier');assert.equal(tiers[0].tier,3);const quantities=selectInventory(a,'all','','quantity');assert.equal(quantities[0].quantity,30);});
test('inventory equipment default sort puts equipped first',()=>{assert.equal(selectInventory(inventoryView(fixture()),'equipment')[0].sourceId,'starter');});
test('inventory unlearned first and tier/status filters',()=>{const a=inventoryView(fixture());assert.equal(selectInventory(a,'skillbooks')[0].sourceId,'execute');assert.ok(selectInventory(a,'all','','default',{tier:3,status:false}).every(i=>i.tier===3));assert.equal(selectInventory(a,'equipment','','default',{tier:0,status:true}).length,1);});

