import test from 'node:test';
import assert from 'node:assert/strict';
import {initialState,stats} from '../src/game/engine/state';
import {enter} from '../src/game/engine/expedition';
import {basicAttack,damage,flee,hasPlayableBattleAction,passPlayerTurn,resolveMonsterTurn,tick,useBattlePotion,useBattleSkill} from '../src/game/engine/combat';
import {applyEffect} from '../src/game/engine/effects';
import {beginMonsterTurn,chooseMonsterAction,createMonsterRuntime,TEST_MONSTER_BASIC,TEST_MONSTER_CHARGE,TEST_MONSTER_EFFECT,TEST_MONSTER_MULTI,type MonsterDefinition} from '../src/game/engine/monsterAi';
import {createRepository,migrateV17,MONSTER_RUNTIME_BACKUP_KEY,SAVE_KEY,validSave} from '../src/storage/repository';
import {openEvent} from '../src/game/events/service';
import {DEV_EVENTS} from '../src/game/events/fixtures';

const runtimeState=(definitionId:string)=>{const s=enter(initialState(),'ore',1),e=s.expedition!;e.monster={definitionId,name:'전투 훈련체',hp:1000,currentHp:1000,attack:20,defense:0,speed:1,skillPower:1};e.monsterRuntime=createMonsterRuntime(e.monster);e.phase='MONSTER_TURN';return s;};
const memory=(raw?:string)=>{const map=new Map<string,string>();if(raw)map.set(SAVE_KEY,raw);return {map,repo:createRepository({getItem:key=>map.get(key)??null,setItem:(key,value)=>void map.set(key,value)})};};

test('MONSTER 01-04: encounter runtime, basic fallback, reload, encounter replacement',()=>{let s=enter(initialState(),'ore',1);assert.ok(s.expedition!.monsterRuntime);assert.equal(s.expedition!.monsterRuntime!.definitionId,s.expedition!.monster.definitionId);s.expedition!.phase='MONSTER_TURN';const hp=s.expedition!.hp;s=resolveMonsterTurn(s);assert.ok(s.expedition!.hp<hp);const {repo}=memory();repo.save(s);assert.deepEqual(repo.load().expedition!.monsterRuntime,s.expedition!.monsterRuntime);s.expedition!.monster.currentHp=1;s=basicAttack(s,()=>.99);assert.ok(s.expedition!.monsterRuntime);assert.equal(s.expedition!.monsterRuntime!.turnNumber,0);});

test('MONSTER 05-10: priority, HP conditions, ready condition and invalid fallback are deterministic',()=>{const monster={definitionId:TEST_MONSTER_BASIC.id,name:'AI',hp:100,currentHp:50,attack:10,defense:0,speed:1,skillPower:1},runtime=createMonsterRuntime(monster);const chosen=chooseMonsterAction(TEST_MONSTER_BASIC,runtime,monster,50,100);assert.equal(chosen.skill?.id,'crush');runtime.skillCooldowns.crush=1;assert.equal(chooseMonsterAction(TEST_MONSTER_BASIC,runtime,monster,50,100).kind,'BASIC_ATTACK');monster.currentHp=90;runtime.skillCooldowns.crush=0;assert.equal(chooseMonsterAction(TEST_MONSTER_BASIC,runtime,monster,50,100).kind,'BASIC_ATTACK');const targetRule:MonsterDefinition={id:'target',name:'target',skills:[{id:'x',name:'x',description:'',cooldown:1,kind:'damage'}],aiRules:[{id:'a',priority:1,actionId:'x',conditions:[{kind:'TARGET_HP_BELOW',value:.5}]}]};assert.equal(chooseMonsterAction(targetRule,runtime,monster,40,100).skill?.id,'x');const invalid={...targetRule,aiRules:[{id:'bad',priority:99,actionId:'missing',conditions:[]}]} satisfies MonsterDefinition;assert.equal(chooseMonsterAction(invalid,runtime,monster,40,100).kind,'BASIC_ATTACK');});

test('MONSTER 11-14: cooldown starts after skill and decreases only at monster turn start',()=>{let s=runtimeState(TEST_MONSTER_BASIC.id);s.expedition!.monster.currentHp=500;s=resolveMonsterTurn(s);assert.equal(s.expedition!.monsterRuntime!.skillCooldowns.crush,2);const unchanged=s.expedition!.monsterRuntime!.skillCooldowns.crush;s=basicAttack(s);assert.equal(s.expedition!.monsterRuntime!.skillCooldowns.crush,unchanged);s=resolveMonsterTurn(s);assert.equal(s.expedition!.monsterRuntime!.skillCooldowns.crush,1);s=basicAttack(s);s=resolveMonsterTurn(s);assert.equal(s.expedition!.monsterRuntime!.skillCooldowns.crush,2);const standalone=createMonsterRuntime({definitionId:'x',name:'x',hp:1,currentHp:1,attack:1,defense:0,speed:1,skillPower:1});standalone.skillCooldowns.x=1;beginMonsterTurn(standalone);assert.equal(standalone.skillCooldowns.x,0);});

test('MONSTER 15-20: charge consumes prepare/discharge turns, survives damage/reload, cooldown begins on discharge',()=>{let s=runtimeState(TEST_MONSTER_CHARGE.id);const before=s.expedition!.hp;s=resolveMonsterTurn(s);assert.equal(s.expedition!.hp,before);assert.equal(s.expedition!.monsterRuntime!.preparedActionId,'charge');assert.equal(s.expedition!.monsterRuntime!.skillCooldowns.charge,undefined);s=basicAttack(s);assert.equal(s.expedition!.monsterRuntime!.preparedActionId,'charge');const {repo}=memory();repo.save(s);s=repo.load();s=resolveMonsterTurn(s);assert.ok(s.expedition!.hp<before);assert.equal(s.expedition!.monsterRuntime!.preparedActionId,null);assert.equal(s.expedition!.monsterRuntime!.skillCooldowns.charge,2);assert.match(s.logs.join('\n'),/준비 시작/);assert.match(s.logs.join('\n'),/준비 공격 발동/);});

test('MONSTER 21-23: multi-hit applies defense for each hit, remains one action and stops on death',()=>{let s=runtimeState(TEST_MONSTER_MULTI.id);const turn=s.expedition!.monsterRuntime!.turnNumber;s=resolveMonsterTurn(s);assert.equal(s.logs.filter(line=>line.includes('[삼연격]')&&line.includes('타')).length,3);assert.equal(s.expedition!.monsterRuntime!.turnNumber,turn+1);s=runtimeState(TEST_MONSTER_MULTI.id);s.expedition!.hp=5;s=resolveMonsterTurn(s);assert.equal(s.lastExpedition?.outcome,'dead');assert.equal(s.logs.filter(line=>line.includes('[삼연격]')&&line.includes('타')).length,1);});

test('MONSTER 24-27: monster effects target player/self and keep created-turn periodic semantics',()=>{let s=runtimeState(TEST_MONSTER_EFFECT.id);s=resolveMonsterTurn(s);const poison=s.expedition!.playerEffects.find(effect=>effect.effectId==='poison');assert.ok(poison);const hp=s.expedition!.hp;s=passPlayerTurn(s);assert.equal(s.expedition!.hp,hp-5);assert.equal(s.expedition!.playerEffects.find(effect=>effect.effectId==='poison')?.remainingDuration,1);s=runtimeState(TEST_MONSTER_EFFECT.id);s.expedition!.monsterRuntime!.skillCooldowns.venom=2;s=resolveMonsterTurn(s);assert.ok(s.expedition!.monsterEffects.some(effect=>effect.effectId==='defense_up'));});

test('PLAYER 28-31: manual turns never auto-pass, pass resolves effects, and real time never reduces cooldown',()=>{let s=enter(initialState(),'ore',1);s.skills=[null,null,null];for(const p of Object.keys(s.expedition!.bag))s.expedition!.bag[p as keyof typeof s.expedition!.bag]=0;assert.equal(hasPlayableBattleAction(s),true);applyEffect(s.expedition!,'player','poison','monster',0);const hp=s.expedition!.hp;s=passPlayerTurn(s);assert.equal(s.expedition!.hp,hp-5);assert.equal(s.expedition!.playerEffects[0].remainingDuration,1);const frozen=tick(s,999);assert.strictEqual(frozen,s);});

test('ITEM 32-34: actual potion use consumes one action and proceeds to monster turn',()=>{let s=enter(initialState(),'ore',1);const before=s.expedition!.bag.healing_lesser;s.expedition!.hp=50;s=useBattlePotion(s,'healing_lesser');assert.equal(s.expedition!.bag.healing_lesser,before-1);assert.equal(s.expedition!.phase,'MONSTER_TURN');assert.ok(s.expedition!.hp>50);});

test('PLAYER 13 and legacy regressions: bow attacks twice, guard reduces damage, quick/haste grant no attack buff',()=>{let s=initialState();s.items.push({id:'bow',kind:'bow',tier:1,enhancement:0});s.equipped.weapon='bow';s=enter(s,'ore',1);s.expedition!.monster.currentHp=1000;const before=s.expedition!.monster.currentHp;s=basicAttack(s);assert.equal(s.logs.filter(line=>line.includes('활 공격')).length,2);assert.ok(s.expedition!.monster.currentHp<before);let guarded=enter(initialState(),'ore',1);guarded.expedition!.hp=stats(guarded).hp*.5;guarded=useBattleSkill(guarded,'guard');guarded.expedition!.monster.attack=50;const guardHp=guarded.expedition!.hp;guarded=resolveMonsterTurn(guarded);let plain=enter(initialState(),'ore',1);plain.expedition!.hp=stats(plain).hp*.5;plain.expedition!.monster.attack=50;const plainHp=plain.expedition!.hp;plain.expedition!.phase='MONSTER_TURN';plain=resolveMonsterTurn(plain);assert.ok(guardHp-guarded.expedition!.hp<plainHp-plain.expedition!.hp);let legacy=enter(initialState(),'ore',1);legacy=useBattleSkill(legacy,'quick');assert.equal(legacy.expedition!.playerEffects.some(effect=>effect.effectId==='attack_up'),false);legacy=resolveMonsterTurn(legacy);legacy=useBattlePotion(legacy,'healing_lesser');assert.equal(legacy.expedition!.playerEffects.some(effect=>effect.effectId==='attack_up'),false);});

test('FLEE 35-39: final turn uses AI/prepared, then return/death/DOT settlement rules',()=>{let s=runtimeState(TEST_MONSTER_CHARGE.id);s=resolveMonsterTurn(s);s=flee(s);s=resolveMonsterTurn(s);assert.equal(s.lastExpedition?.outcome,'returned');assert.ok(s.logs.some(line=>line.includes('준비 공격 발동')));s=runtimeState(TEST_MONSTER_MULTI.id);s.expedition!.phase='PLAYER_TURN';s.expedition!.hp=1;s=flee(s);assert.equal(resolveMonsterTurn(s).lastExpedition?.outcome,'dead');s=runtimeState(TEST_MONSTER_BASIC.id);s.expedition!.phase='PLAYER_TURN';s.expedition!.monster.currentHp=1;s.expedition!.monster.attack=1;applyEffect(s.expedition!,'monster','poison','player',0);s=flee(s);s=resolveMonsterTurn(s);assert.equal(s.lastExpedition?.outcome,'returned');assert.equal(s.lastExpedition?.kills,1);});

test('SAVE 03/19: v17 migration preserves battle state, runtime and one-time backup',()=>{const current=enter(initialState(),'ore',1),legacy:any=structuredClone(current);legacy.version=17;delete legacy.expedition.monsterRuntime;legacy.expedition.hp=77;legacy.expedition.monster.currentHp=19;legacy.expedition.monsterTurn=4;legacy.expedition.loot.silver=123;const migrated=migrateV17(legacy);assert.equal(migrated.version,21);assert.equal(migrated.expedition!.hp,77);assert.equal(migrated.expedition!.monster.currentHp,19);assert.equal(migrated.expedition!.monsterRuntime!.turnNumber,4);assert.equal(migrated.expedition!.loot.silver,123);assert.ok(validSave(migrated));const raw=JSON.stringify(legacy),{map,repo}=memory(raw);repo.load();assert.equal(map.get(MONSTER_RUNTIME_BACKUP_KEY),raw);repo.load();assert.equal(map.get(MONSTER_RUNTIME_BACKUP_KEY),raw);});

test('SAVE 19: v18 migration backup failure leaves the v17 main save untouched',()=>{const legacy:any=enter(initialState(),'ore',1);legacy.version=17;delete legacy.expedition.monsterRuntime;const raw=JSON.stringify(legacy);let main=raw,writes=0;const repo=createRepository({getItem:key=>key===SAVE_KEY?main:null,setItem:(key,value)=>{writes++;if(key===MONSTER_RUNTIME_BACKUP_KEY)throw Error('storage full');if(key===SAVE_KEY)main=value;}});assert.throws(()=>repo.load());assert.equal(writes,1);assert.equal(main,raw);});

test('SAVE 50: pending event migration keeps runtime absent and event identity intact',()=>{const current=enter(initialState(),'ore',1);current.expedition!.monster.currentHp=0;openEvent(current,DEV_EVENTS[0],()=>0);const legacy:any=structuredClone(current);legacy.version=17;delete legacy.expedition.monsterRuntime;const migrated=migrateV17(legacy);assert.equal(migrated.expedition!.monsterRuntime,null);assert.equal(migrated.expedition!.events.pendingEvent!.instanceId,current.expedition!.events.pendingEvent!.instanceId);});


