import test from 'node:test';
import assert from 'node:assert/strict';
import {initialState,stats} from '../src/game/engine/state';
import {enter,requestReturn} from '../src/game/engine/expedition';
import {basicAttack,canPlayerAct,canUsePotion,passPlayerTurn,resolveMonsterTurn,resolveRevivalDecision,useBattlePotion} from '../src/game/engine/combat';
import {applyEffect,activeShield} from '../src/game/engine/effects';
import {createMonsterRuntime,TEST_MONSTER_BASIC,TEST_MONSTER_MULTI,TEST_MONSTER_REACTIVE,TEST_MONSTER_CHARGE} from '../src/game/engine/monsterAi';
import {createRepository,migrateV19,POTION_OVERHAUL_BACKUP_KEY,SAVE_KEY,validSave} from '../src/storage/repository';
import {CONFIG,generalPotionIds,potionIds} from '../src/game/data/config';
import {initialEvents,openEvent,resolveEvent} from '../src/game/events/service';
import {DEV_EVENTS} from '../src/game/events/fixtures';

const memory=(raw?:string)=>{const map=new Map<string,string>();if(raw)map.set(SAVE_KEY,raw);return {map,repo:createRepository({getItem:key=>map.get(key)??null,setItem:(key,value)=>void map.set(key,value)})};};
const withRevival=(definitionId=TEST_MONSTER_BASIC.id)=>{const base=initialState();base.potions.revival=1;base.loadout.healing_lesser=0;base.loadout.revival=1;const s=enter(base,'ore',1),e=s.expedition!;e.monster={definitionId,name:'부활 훈련체',hp:1000,currentHp:1000,attack:20,defense:0,speed:1,skillPower:1};e.monsterRuntime=createMonsterRuntime(e.monster);return s;};

test('POTION 01: five production IDs and separate carry caps are centralized',()=>{assert.deepEqual(potionIds,['healing_lesser','healing_standard','healing_greater','healing_supreme','revival']);const s=initialState();s.potions.healing_lesser=99;s.loadout.healing_lesser=CONFIG.generalPotionLimit;s.loadout.healing_standard=1;assert.equal(enter(s,'ore',1).expedition,null);s.loadout.healing_standard=0;s.potions.revival=2;s.loadout.revival=2;assert.equal(enter(s,'ore',1).expedition,null);s.loadout.revival=1;assert.ok(enter(s,'ore',1).expedition);assert.equal(generalPotionIds.length,4);});

test('POTION 02: four healing tiers are manual instant heals, clamp HP, consume one action, and create no buff',()=>{const ratios=[.2,.35,.5,.75];for(const [i,id] of generalPotionIds.entries()){const base=initialState();base.potions[id]=1;base.loadout.healing_lesser=0;base.loadout[id]=1;let s=enter(base,'ore',1);const max=stats(s,s.expedition!.equipment).hp;s.expedition!.hp=max-10;assert.equal(canUsePotion(s,id),true);s=useBattlePotion(s,id,()=>.99);assert.equal(s.expedition!.hp,Math.min(max,max-10+max*ratios[i]));assert.equal(s.expedition!.bag[id],0);assert.equal(s.expedition!.phase,'MONSTER_TURN');assert.equal(s.expedition!.playerEffects.length,0);}const full=enter(initialState(),'ore',1);assert.equal(canUsePotion(full,'healing_lesser'),false);assert.strictEqual(useBattlePotion(full,'healing_lesser'),full);assert.equal(canUsePotion(full,'revival'),false);});

test('REVIVAL 03: lethal basic damage pauses, locks actions, consumes only on accept, and resumes without a duplicate monster turn',()=>{let s=withRevival();const e=s.expedition!;e.hp=1;e.phase='MONSTER_TURN';s=resolveMonsterTurn(s);assert.equal(s.expedition!.hp,0);assert.equal(s.expedition!.pendingRevival?.source,'DIRECT_HIT');assert.equal(s.expedition!.monsterTurn,1);assert.equal(canPlayerAct(s),false);assert.strictEqual(requestReturn(s),s);const turn=s.expedition!.monsterRuntime!.turnNumber;s=resolveRevivalDecision(s,true);assert.equal(s.expedition!.bag.revival,0);assert.equal(s.expedition!.monsterRuntime!.turnNumber,turn);assert.equal(s.expedition!.phase,'PLAYER_TURN');assert.ok(s.expedition!.hp>0);});

test('REVIVAL 04: decline keeps the potion unconsumed in the death receipt and runs normal death settlement',()=>{let s=withRevival();s.expedition!.hp=1;s.expedition!.phase='MONSTER_TURN';s=resolveMonsterTurn(s);s=resolveRevivalDecision(s,false);assert.equal(s.expedition,null);assert.equal(s.lastExpedition?.outcome,'dead');assert.equal(s.lastExpedition?.remainingPotions.revival,1);});

test('REVIVAL 05: multi-hit pauses on the lethal hit and resumes only the remaining hits',()=>{let s=withRevival(TEST_MONSTER_MULTI.id),e=s.expedition!;e.hp=1;e.phase='MONSTER_TURN';s=resolveMonsterTurn(s);e=s.expedition!;const direct=e.pendingRevival!.steps.find(x=>x.kind==='DIRECT_HITS');assert.ok(direct&&direct.remainingHits>0);const turn=e.monsterRuntime!.turnNumber,monsterTurn=e.monsterTurn;s=resolveRevivalDecision(s,true);assert.ok(s.expedition);assert.equal(s.expedition!.monsterRuntime!.turnNumber,turn);assert.equal(s.expedition!.monsterTurn,monsterTurn);assert.equal(s.expedition!.phase,'PLAYER_TURN');assert.ok(s.expedition!.hp<Math.round(stats(s,s.expedition!.equipment).hp*CONFIG.revivalHealRatio));});

test('REVIVAL 06: shield absorbs before lethal check and periodic damage can open the same decision',()=>{let s=withRevival(),e=s.expedition!;applyEffect(e,'player','test_shield','player',e.playerTurn);activeShield(e,'player')!.currentShield=100;e.hp=1;e.monster.attack=20;e.phase='MONSTER_TURN';s=resolveMonsterTurn(s);assert.equal(s.expedition!.pendingRevival,null);assert.equal(s.expedition!.hp,1);s.expedition!.phase='PLAYER_TURN';applyEffect(s.expedition!,'player','poison','monster',0);activeShield(s.expedition!,'player')!.currentShield=1;s=passPlayerTurn(s,()=>.99);assert.equal(s.expedition!.pendingRevival?.source,'PERIODIC_DAMAGE');});

test('REVIVAL 07: pending decision and continuation survive save/reload and resolve once',()=>{let s=withRevival(TEST_MONSTER_MULTI.id);s.expedition!.hp=1;s.expedition!.phase='MONSTER_TURN';s=resolveMonsterTurn(s);const before=structuredClone(s.expedition!.pendingRevival),turn=s.expedition!.monsterTurn;const {repo}=memory();repo.save(s);s=repo.load();assert.deepEqual(s.expedition!.pendingRevival,before);s=resolveRevivalDecision(s,true);assert.equal(s.expedition!.monsterTurn,turn);assert.equal(s.expedition!.pendingRevival,null);assert.ok(validSave(s));});

test('MIGRATION 08: v19 potion bags merge deterministically across permanent, loadout, expedition, preset, result, and crafting jobs',()=>{const source:any=structuredClone(initialState());source.version=19;const old={health:2,regen:3,attack:5,defense:7,haste:11};source.potions={...old};source.loadout={...old};source.expeditionPresets[0]={name:'legacy',equipment:{...source.equipped},skills:[...source.skills],potions:{...old},threshold:70};source.lastExpedition={outcome:'dead',tower:'ore',floor:1,time:0,kills:0,loot:{silver:0,materials:{ore:[0,0,0,0,0],leather:[0,0,0,0,0],gem:[0,0,0,0,0],kaleon:[0,0,0,0,0]},tickets:{ore:Array(50).fill(0),leather:Array(50).fill(0),gem:Array(50).fill(0),kaleon:Array(50).fill(0)},skillBooks:{},items:{}},remainingPotions:{...old}};source.crafting.jobs=[{jobId:'craft-1',recipeId:'health-1',itemId:'health',kind:'health',tier:1,quantity:10,field:'alchemy',status:'QUEUED',queuedAt:0,startedAt:null,completesAt:null,durationMs:1,consumedMaterials:1,consumedSilver:0}];const n=migrateV19(source);for(const bag of [n.potions,n.loadout,n.expeditionPresets[0]!.potions,n.lastExpedition!.remainingPotions]){assert.equal(bag.healing_lesser,25);assert.equal(bag.healing_standard,3);assert.equal(bag.revival,0);}assert.equal(n.crafting.jobs[0].kind,'healing_lesser');assert.equal(n.version,22);assert.ok(validSave(n));});

test('MIGRATION 09: repository backs up v19 once and writes the current schema under the unchanged key',()=>{const old:any=structuredClone(initialState());old.version=19;const toOld=(b:any)=>({health:b.healing_lesser,regen:b.healing_standard,attack:b.healing_greater,defense:b.healing_supreme,haste:0});old.potions=toOld(old.potions);old.loadout=toOld(old.loadout);const {repo,map}=memory(JSON.stringify(old));const n=repo.load();assert.equal(n.version,22);assert.ok(map.has(POTION_OVERHAUL_BACKUP_KEY));assert.ok(map.has(SAVE_KEY));repo.load();assert.equal(map.get(POTION_OVERHAUL_BACKUP_KEY),JSON.stringify(old));});


test('REVIVAL 10: reactive counter and charged attack pause at the same lethal boundary without resetting cooldowns',()=>{let reactive=withRevival(TEST_MONSTER_REACTIVE.id);reactive.expedition!.phase='MONSTER_TURN';reactive=resolveMonsterTurn(reactive);reactive.expedition!.hp=1;const cooldown=reactive.expedition!.monsterRuntime!.skillCooldowns.counter_stance;reactive=basicAttack(reactive,()=>.99);assert.equal(reactive.expedition!.pendingRevival?.source,'DIRECT_HIT');reactive=resolveRevivalDecision(reactive,true);assert.equal(reactive.expedition!.monsterRuntime!.skillCooldowns.counter_stance,cooldown);assert.equal(reactive.expedition!.phase,'MONSTER_TURN');let charge=withRevival(TEST_MONSTER_CHARGE.id);charge.expedition!.phase='MONSTER_TURN';charge=resolveMonsterTurn(charge);charge=passPlayerTurn(charge,()=>.99);charge.expedition!.hp=1;charge=resolveMonsterTurn(charge);assert.equal(charge.expedition!.pendingRevival?.source,'DIRECT_HIT');const turn=charge.expedition!.monsterRuntime!.turnNumber;charge=resolveRevivalDecision(charge,true);assert.equal(charge.expedition!.monsterRuntime!.turnNumber,turn);});

test('REVIVAL 11: lethal random-event damage pauses on the result and can resume or decline through the common decision',()=>{let s=withRevival();const e=s.expedition!;e.hp=1;e.events=initialEvents('test');e.monster.currentHp=0;openEvent(s,DEV_EVENTS.find(x=>x.id==='TEST_RISK_EVENT')!,()=>.9);const id=e.events.pendingEvent!.instanceId;s=resolveEvent(s,id,'search');assert.equal(s.expedition!.pendingRevival?.source,'EVENT_DAMAGE');assert.equal(s.expedition!.events.phase,'EVENT_RESULT');s=resolveRevivalDecision(s,true);assert.equal(s.expedition!.pendingRevival,null);assert.ok(s.expedition!.hp>0);assert.equal(s.expedition!.events.phase,'EVENT_RESULT');});
