import test from 'node:test';
import assert from 'node:assert/strict';
import {initialState,stats} from '../src/game/engine/state';
import {enter} from '../src/game/engine/expedition';
import {activeShield,applyEffect,applyIncomingDamage,clearBattleEffects,EFFECTS,expireTurnEffects,hasEffect,removeEffectById,validateEffectDefinitions} from '../src/game/engine/effects';
import {resolveDirectHits} from '../src/game/engine/directHits';
import {passPlayerTurn,resolveMonsterTurn} from '../src/game/engine/combat';
import {resolveActorDirectHits} from '../src/game/engine/monsterSkills';
import {prepareReactive} from '../src/game/engine/reactions';
import {chooseMonsterAction,createMonsterRuntime,TEST_MONSTER_CHARGE,TEST_MONSTER_REACTIVE,type MonsterDefinition} from '../src/game/engine/monsterAi';
import {createRepository,SAVE_KEY,validSave} from '../src/storage/repository';

const noEvent=()=>.99;
const state=()=>enter(initialState(),'ore',1);
const prepareSkill=TEST_MONSTER_REACTIVE.skills!.find(skill=>skill.kind==='reactive_prepare')!;
const memory=()=>{const map=new Map<string,string>();return createRepository({getItem:key=>map.get(key)??null,setItem:(key,value)=>void map.set(key,value)});};

test('SHIELD 01-08: both actors receive one HP-independent Shield that absorbs, overflows and removes at zero',()=>{const s=state(),e=s.expedition!;applyEffect(e,'player','test_shield','player',e.playerTurn);applyEffect(e,'monster','test_shield','monster',e.monsterTurn);assert.equal(activeShield(e,'player')?.currentShield,30);assert.equal(activeShield(e,'monster')?.currentShield,30);const playerHp=e.hp,monsterHp=e.monster.currentHp;let r=resolveDirectHits(e,'player','monster',1,()=>20);assert.equal(r.resolutions[0].absorbedByShield,20);assert.equal(e.monster.currentHp,monsterHp);assert.equal(activeShield(e,'monster')?.currentShield,10);r=resolveDirectHits(e,'monster','player',1,()=>30);assert.equal(r.resolutions[0].shieldAfter,0);assert.equal(e.hp,playerHp);assert.equal(activeShield(e,'player'),undefined);applyEffect(e,'player','test_shield','player',e.playerTurn);r=resolveDirectHits(e,'monster','player',1,()=>45);assert.equal(r.total,15);assert.equal(e.hp,playerHp-15);assert.equal(r.resolutions[0].shieldAfter,0);assert.ok(r.resolutions[0].shieldAfter>=0);assert.equal(hasEffect(e.playerEffects,'test_shield'),false);});

test('SHIELD 09-17: full absorption still triggers one Reactive and multi-hit consumes Shield hit by hit',()=>{let s=state(),e=s.expedition!;e.monster={definitionId:TEST_MONSTER_REACTIVE.id,name:'반격 훈련체',hp:1000,currentHp:1000,attack:20,defense:0,speed:1,skillPower:1};e.monsterRuntime=createMonsterRuntime(e.monster);applyEffect(e,'monster','test_shield','monster',e.monsterTurn);prepareReactive(e,'monster',TEST_MONSTER_REACTIVE.id,prepareSkill);const playerHp=e.hp,result=resolveActorDirectHits(s,'player',3,0.2);assert.equal(result.triggerPoints,3);assert.equal(s.logs.filter(line=>line.includes('즉시 발동')).length,1);assert.equal(e.reactivePrepared.monster,null);assert.ok(e.hp<playerHp);assert.deepEqual(result.resolutions.map(hit=>hit.shieldBefore),[30,28,26]);assert.equal(result.total,0);s=state();e=s.expedition!;applyEffect(e,'monster','test_shield','monster',e.monsterTurn);const exact=resolveDirectHits(e,'player','monster',3,()=>15);assert.deepEqual(exact.resolutions.map(hit=>[hit.absorbedByShield,hit.hpDamage]),[[15,0],[15,0],[0,15]]);assert.equal(exact.total,15);assert.equal(exact.hits.length,3);});

test('SHIELD lethal/reaction contract: overflow death blocks counter and counter death stops remaining hits',()=>{let s=state(),e=s.expedition!;e.monster={definitionId:TEST_MONSTER_REACTIVE.id,name:'반격 훈련체',hp:5,currentHp:5,attack:20,defense:0,speed:1,skillPower:1};e.monsterRuntime=createMonsterRuntime(e.monster);applyEffect(e,'monster','test_shield','monster',e.monsterTurn);activeShield(e,'monster')!.currentShield=2;prepareReactive(e,'monster',TEST_MONSTER_REACTIVE.id,prepareSkill);resolveDirectHits(e,'player','monster',1,()=>10,()=>{throw Error('dead target reacted');});assert.equal(e.monster.currentHp,0);assert.ok(e.reactivePrepared.monster);s=state();e=s.expedition!;e.monster={definitionId:TEST_MONSTER_REACTIVE.id,name:'반격 훈련체',hp:100,currentHp:100,attack:999,defense:0,speed:1,skillPower:1};e.monsterRuntime=createMonsterRuntime(e.monster);e.hp=1;applyEffect(e,'monster','test_shield','monster',e.monsterTurn);prepareReactive(e,'monster',TEST_MONSTER_REACTIVE.id,prepareSkill);const result=resolveActorDirectHits(s,'player',3,.2);assert.equal(result.hits.length,1);assert.equal(e.hp,0);});

test('SHIELD 18-25: periodic damage uses Shield without Direct Hit/Reactive while Heal and HOT affect HP only',()=>{let s=state(),e=s.expedition!;applyEffect(e,'player','test_shield','player',e.playerTurn);activeShield(e,'player')!.currentShield=10;prepareReactive(e,'player',TEST_MONSTER_REACTIVE.id,prepareSkill);applyEffect(e,'player','poison','monster',e.playerTurn-1);const hp=e.hp,pending=structuredClone(e.reactivePrepared.player);s=passPlayerTurn(s,noEvent);e=s.expedition!;assert.equal(e.hp,hp);assert.equal(activeShield(e,'player')?.currentShield,5);assert.deepEqual(e.reactivePrepared.player,pending);activeShield(e,'player')!.currentShield=3;e.phase='PLAYER_TURN';e.playerTurn++;applyEffect(e,'player','poison','monster',e.playerTurn-1);s=passPlayerTurn(s,noEvent);e=s.expedition!;assert.equal(activeShield(e,'player'),undefined);assert.equal(e.hp,hp-2);s=state();e=s.expedition!;e.hp=50;applyEffect(e,'player','test_shield','player',e.playerTurn);activeShield(e,'player')!.currentShield=12;applyEffect(e,'player','regen','player',e.playerTurn-1);s=passPlayerTurn(s,noEvent);e=s.expedition!;assert.ok(e.hp>50);assert.equal(activeShield(e,'player')?.currentShield,12);});

test('SHIELD 26-35: duration, explicit removal, battle cleanup and reapply replacement are deterministic',()=>{const s=state(),e=s.expedition!;applyEffect(e,'player','test_shield','player',1);const first=activeShield(e,'player')!;first.currentShield=5;applyEffect(e,'player','test_shield','player',2);const replaced=activeShield(e,'player')!;assert.equal(replaced.currentShield,30);assert.equal(replaced.remainingDuration,3);assert.equal(replaced.stackCount,1);assert.notEqual(replaced.instanceId,first.instanceId);expireTurnEffects(e,'player',2);assert.equal(activeShield(e,'player')?.remainingDuration,3);expireTurnEffects(e,'player',3);expireTurnEffects(e,'player',4);assert.ok(activeShield(e,'player'));expireTurnEffects(e,'player',5);assert.equal(activeShield(e,'player'),undefined);applyEffect(e,'player','test_shield','player',6);removeEffectById(e,'player','test_shield');assert.equal(e.playerEffects.some(effect=>'currentShield' in effect),false);applyEffect(e,'player','test_shield','player',6);clearBattleEffects(e);assert.equal(activeShield(e,'player'),undefined);});

test('SHIELD 36-42: current amount and duration survive v19 reload without refill or migration',()=>{const s=state(),e=s.expedition!,repo=memory();applyEffect(e,'player','test_shield','player',e.playerTurn);activeShield(e,'player')!.currentShield=17;activeShield(e,'player')!.remainingDuration=2;e.monster={...e.monster,definitionId:TEST_MONSTER_CHARGE.id};e.monsterRuntime=createMonsterRuntime(e.monster);e.monsterRuntime.preparedActionId='charge';prepareReactive(e,'monster',TEST_MONSTER_REACTIVE.id,prepareSkill);assert.equal(s.version,20);assert.ok(validSave(s));repo.save(s);const loaded=repo.load(),shield=activeShield(loaded.expedition!,'player');assert.equal(loaded.version,20);assert.equal(shield?.currentShield,17);assert.equal(shield?.remainingDuration,2);assert.equal(loaded.expedition!.monsterRuntime?.preparedActionId,'charge');assert.ok(loaded.expedition!.reactivePrepared.monster);assert.ok(loaded.expedition!.playerEffects.some(effect=>effect.effectId==='test_shield'));assert.ok(repo.load());});

test('SHIELD 43-58: Charge, Stack and Status AI remain independent and invalid definitions fail safely',()=>{const s=state(),e=s.expedition!;applyEffect(e,'monster','test_shield','monster',e.monsterTurn);const chargeRuntime=createMonsterRuntime({...e.monster,definitionId:TEST_MONSTER_CHARGE.id});chargeRuntime.preparedActionId='charge';resolveDirectHits(e,'player','monster',1,()=>10);assert.equal(chargeRuntime.preparedActionId,'charge');assert.equal(activeShield(e,'monster')?.stackCount,1);const shieldRule:MonsterDefinition={id:'shield-ai',name:'shield-ai',skills:[{id:'x',name:'x',description:'',cooldown:1,kind:'damage'}],aiRules:[{id:'has',priority:1,actionId:'x',conditions:[{kind:'SELF_HAS_EFFECT',effectId:'test_shield'}]}]};assert.equal(chooseMonsterAction(shieldRule,createMonsterRuntime(e.monster),e.monster,e.hp,stats(s).hp,e.monsterEffects,e.playerEffects).skill?.id,'x');applyIncomingDamage(e,'monster',99);assert.equal(chooseMonsterAction(shieldRule,createMonsterRuntime(e.monster),e.monster,e.hp,stats(s).hp,e.monsterEffects,e.playerEffects).kind,'BASIC_ATTACK');assert.deepEqual(validateEffectDefinitions(),[]);const invalid={bad:{...EFFECTS.test_shield,id:'bad',shieldAmount:0,stackingPolicy:'STACK' as const,maxStacks:3,scope:'EXPEDITION' as const}};assert.ok(validateEffectDefinitions(invalid).length>=4);const before=e.monsterEffects.length;assert.equal(applyEffect(e,'monster','missing-shield','monster',0),undefined);assert.equal(e.monsterEffects.length,before);});
