import {advanceSkillTurns,skillTurnsLeft} from './turns';
import type {GameState,Potion} from '../types';
import {COMBAT,SKILLS,POTIONS,PASSIVES} from '../data/config';
import {stats,weaponOf,equippedItem,log} from './state';
import {reward} from './drops';
import {leave} from './expedition';
import {postBattle} from '../events/service';
import {random} from '../events/rng';
import {applyEffect,applyIncomingDamage,clearBattleEffects,expireTurnEffects,modifier,periodicDelta} from './effects';
import {resolveBattleJobId,resolvePlayerCombatKit} from '../jobs/service';
import {jobById} from '../jobs/catalog';
import {damage} from './damage';
import {beginMonsterTurn,chooseMonsterAction,createMonsterRuntime,definitionForRuntime,useMonsterAction} from './monsterAi';
import {directHitLog,resolveActorDirectHits,resolveMonsterAction} from './monsterSkills';
import {clearReactivePrepared} from './reactions';

export {damage} from './damage';
const active=(e:NonNullable<GameState['expedition']>,key:string)=>(e.buffs[key]??0)>0;
const skillById=(id:string)=>SKILLS.find(skill=>skill.id===id);
function heal(s:GameState,amount:number){const e=s.expedition!;e.hp=Math.min(stats(s,e.equipment).hp,e.hp+amount);}
function startPlayerTurn(s:GameState){const e=s.expedition!,base=stats(s,e.equipment);e.phase='PLAYER_TURN';e.playerTurn++;e.pendingFlee=false;if(active(e,'regen'))heal(s,base.hp*POTIONS.regen.value/POTIONS.regen.duration);for(const key of Object.keys(e.buffs)){e.buffs[key]=Math.max(0,e.buffs[key]-1);if(e.buffs[key]===0)delete e.buffs[key];}advanceSkillTurns(e,SKILLS.map(skill=>skill.id));}
function attackValue(s:GameState){const e=s.expedition!,base=stats(s,e.equipment),passive=equippedItem(s,'accessory',e.equipment)?.kind as keyof typeof PASSIVES|undefined,berserk=passive==='berserker'&&e.hp/base.hp<=PASSIVES.berserker.threshold?1+PASSIVES.berserker.value:1;return base.attack*(1+modifier(e,'player','attack'))*berserk;}
function defeatMonster(s:GameState,rng:()=>number){const e=s.expedition!;e.monster.currentHp=0;e.monsterRuntime=null;clearReactivePrepared(e);const defeatedBoss=e.events.activeBossId!==null;reward(s,rng);if(e.pendingFlee){if(defeatedBoss){e.bossTracking.bossDefeated=true;e.events.bossKillCountThisExpedition++;}return leave(s);}return postBattle(s,defeatedBoss,rng);}
function applyPeriodicDelta(s:GameState,actor:'player'|'monster',delta:number){const e=s.expedition!;if(delta<0){const result=applyIncomingDamage(e,actor,-delta),before=actor==='player'?e.hp:e.monster.currentHp,after=Math.max(0,before-result.hpDamage);if(actor==='player')e.hp=after;else e.monster.currentHp=after;log(s,(actor==='player'?'지속 피해 · ':'적 지속 피해 · ')+result.hpDamage+(result.absorbedByShield>0?' · 보호막 '+result.absorbedByShield+' 흡수':''));return;}if(delta>0){if(actor==='player')e.hp=Math.min(stats(s,e.equipment).hp,e.hp+delta);else e.monster.currentHp=Math.min(e.monster.hp,e.monster.currentHp+delta);log(s,(actor==='player'?'재생 회복 · ':'적 지속 회복 · ')+delta);}}
function finishPlayerTurn(s:GameState,rng:()=>number){const e=s.expedition!,delta=periodicDelta(e,'player',stats(s,e.equipment).hp,e.playerTurn);applyPeriodicDelta(s,'player',delta);expireTurnEffects(e,'player',e.playerTurn);e.time++;if(e.hp<=0)return leave(s,true);if(e.monster.currentHp<=0){clearBattleEffects(e);return defeatMonster(s,rng);}e.phase='MONSTER_TURN';return s;}

export function canPlayerAct(s:GameState){return !!s.expedition&&s.expedition.events.phase==='BATTLE'&&s.expedition.phase==='PLAYER_TURN'&&s.expedition.hp>0&&s.expedition.monster.currentHp>0&&!s.expedition.bossTracking.pendingBossId;}
export function canUseSkill(s:GameState,id:string){const e=s.expedition,skill=skillById(id),jobReady=!!jobById(resolveBattleJobId(s))?.combatKit,activeIds=resolvePlayerCombatKit(s).activeSkillIds;return !!e&&!!skill&&canPlayerAct(s)&&activeIds.includes(id)&&(jobReady||(s.learned.includes(id)&&skill.weapons.includes(weaponOf(s,e.equipment))))&&skillTurnsLeft(e,id)===0&&(skill.condition!=='enemyLow'||e.monster.currentHp/e.monster.hp<=COMBAT.enemyLow)&&(skill.condition!=='selfLow'||e.hp/stats(s,e.equipment).hp<=COMBAT.selfLow);}
export function canUsePotion(s:GameState,potion:Potion){return canPlayerAct(s)&&(s.expedition?.bag[potion]??0)>0;}
export function hasPlayableBattleAction(s:GameState){return canPlayerAct(s);}
export function passPlayerTurn(state:GameState,rng:()=>number=random):GameState {if(!canPlayerAct(state))return state;const s=structuredClone(state);log(s,'행동할 수 없어 이번 턴을 넘깁니다.');return finishPlayerTurn(s,rng);}
export function basicAttack(state:GameState,rng:()=>number=random):GameState {if(!canPlayerAct(state))return state;const s=structuredClone(state),e=s.expedition!,weapon=weaponOf(s,e.equipment),hitResult=resolveActorDirectHits(s,'player',weapon==='bow'?2:1);if(hitResult.hits.length===1)log(s,'당신의 공격 · '+directHitLog(hitResult));else hitResult.resolutions.forEach((value,index)=>log(s,`당신의 활 공격 ${index+1}타 · ${value.hpDamage} 피해${value.absorbedByShield>0?' · 보호막 '+value.absorbedByShield+' 흡수':''}`));const passive=equippedItem(s,'accessory',e.equipment)?.kind as keyof typeof PASSIVES|undefined;if(passive==='vampire'&&e.hp>0)heal(s,hitResult.total*PASSIVES.vampire.value);return finishPlayerTurn(s,rng);}
export function useBattleSkill(state:GameState,id:string,rng:()=>number=random):GameState {if(!canUseSkill(state,id))return state;const s=structuredClone(state),e=s.expedition!,skill=skillById(id)!;e.cooldowns['turn:'+id]=skill.cooldown;if(skill.effect==='damage'){const hit=resolveActorDirectHits(s,'player',1,skill.value*stats(s,e.equipment).skillPower);log(s,'['+skill.name+'] · '+hit.total+' 피해');}else if(skill.effect==='guard'){applyEffect(e,'player','guard','player',e.playerTurn);log(s,'['+skill.name+'] 사용 · '+skill.duration+'턴 지속');}else log(s,'['+skill.name+'] 사용 · 현재 수동 턴제에서는 추가 효과 없음');return finishPlayerTurn(s,rng);}
export function useBattlePotion(state:GameState,potion:Potion,rng:()=>number=random):GameState {if(!canUsePotion(state,potion))return state;const s=structuredClone(state),e=s.expedition!,data=POTIONS[potion];e.bag[potion]--;if(potion==='health')heal(s,stats(s,e.equipment).hp*data.value);else if(potion==='regen')applyEffect(e,'player','regen','player',e.playerTurn);else if(potion==='defense')applyEffect(e,'player','defense_up','player',e.playerTurn);else if(potion==='attack')applyEffect(e,'player','attack_up','player',e.playerTurn);log(s,'['+data.name+' 포션] 사용 · 남은 수량 '+e.bag[potion]+(potion==='haste'?' · 현재 추가 효과 없음':''));return finishPlayerTurn(s,rng);}
export function flee(state:GameState,rng:()=>number=random):GameState {if(!canPlayerAct(state))return state;const s=structuredClone(state),e=s.expedition!;e.pendingFlee=true;log(s,'도망을 시도합니다. 적의 정상 행동 1회를 버텨야 합니다.');return finishPlayerTurn(s,rng);}
export function resolveMonsterTurn(state:GameState):GameState {if(!state.expedition||state.expedition.events.phase!=='BATTLE'||state.expedition.phase!=='MONSTER_TURN')return state;const s=structuredClone(state),e=s.expedition!;e.time++;e.monsterTurn++;e.monsterRuntime??=createMonsterRuntime(e.monster,e.monsterTurn-1);beginMonsterTurn(e.monsterRuntime);const definition=definitionForRuntime(e.monster,e.monsterRuntime),decision=chooseMonsterAction(definition,e.monsterRuntime,e.monster,e.hp,stats(s,e.equipment).hp,e.monsterEffects,e.playerEffects);resolveMonsterAction(s,decision);useMonsterAction(e.monsterRuntime,decision);const delta=periodicDelta(e,'monster',e.monster.hp,e.monsterTurn);applyPeriodicDelta(s,'monster',delta);expireTurnEffects(e,'monster',e.monsterTurn);if(e.hp<=0)return leave(s,true);if(e.monster.currentHp<=0){clearBattleEffects(e);return defeatMonster(s,random);}if(e.pendingFlee){log(s,'도망에 성공했습니다.');return leave(s);}startPlayerTurn(s);return s;}
// Compatibility export: elapsed real time never changes battle state.
export function tick(state:GameState,_dt?:number,_rng?:()=>number){return state;}
