import type {GameState,Field,Tower,Weapon,Potion,CraftJob} from '../types';
import {CONFIG,WEAPONS,PASSIVES,potionIds,POTIONS,POTION_CRAFTING} from '../data/config';
import {itemSlot,itemName} from './state';
import {getGoldenRecorderBenefits,isGoldenRecorderActive} from '../premium/goldenRecorder';
export const GOLDEN_RECORDER_CRAFT_QUEUE_LIMIT=3;
export const CRAFT_DURATION_MS=30_000;
export function fieldFor(kind:string):Field{return potionIds.includes(kind as Potion)?'alchemy':itemSlot(kind)==='weapon'?'weapon':itemSlot(kind)==='accessory'?'accessory':'armor';}
export const materialFor=(field:Field):Tower=>({weapon:'ore',armor:'leather',accessory:'gem',alchemy:'kaleon'} as const)[field];
export const discount=(crafts:number)=>Math.min(CONFIG.maxDiscount,Math.max(0,crafts)*CONFIG.discountPerCraft);
export const cost=(s:GameState,field:Field,tier:number,now=Date.now())=>Math.max(1,Math.ceil(CONFIG.craftCost*tier*(1-discount(s.mastery[field].crafts)-getGoldenRecorderBenefits(s,now).craftingMaterialReductionBonus)));
export function advanceMastery(s:GameState,field:Field,tier:number){const m=s.mastery[field];m.crafts++;if(tier===m.unlocked&&m.unlocked<5){m.progress++;if(m.progress>=CONFIG.masteryRequired){m.unlocked++;m.progress=0;}}}
const active=(s:GameState)=>s.crafting.jobs.find(j=>j.status==='CRAFTING');const queued=(s:GameState)=>s.crafting.jobs.filter(j=>j.status==='QUEUED').sort((a,b)=>a.queuedAt-b.queuedAt);
const start=(j:CraftJob,at:number)=>{j.status='CRAFTING';j.startedAt=at;j.completesAt=at+j.durationMs};
export function settleCrafting(state:GameState,now=Date.now()):GameState{const current=active(state),first=!current?queued(state)[0]:undefined;if(!first&&(!current||current.completesAt===null||now<current.completesAt))return state;const s=structuredClone(state);let cur=active(s);if(!cur){const next=queued(s)[0];if(next)start(next,now);cur=active(s)}while(cur&&cur.completesAt!==null&&now>=cur.completesAt){const doneAt=cur.completesAt;cur.status='COMPLETED_UNCLAIMED';advanceMastery(s,cur.field,cur.tier);const next=queued(s)[0];if(next){start(next,doneAt);cur=next}else cur=undefined;}return s;}
export function startCraft(s0:GameState,kind:string,tier:number,quantity=1,now=Date.now()):GameState{let s=settleCrafting(s0,now);if(s.expedition)return {...s,notice:'귀환 후 제작할 수 있습니다.'};if(!(kind in WEAPONS||kind in PASSIVES||['armor','boots',...potionIds].includes(kind))||!Number.isInteger(tier)||tier<1||tier>5)return {...s,notice:'잘못된 제작 요청입니다.'};const consumable=potionIds.includes(kind as Potion);if(consumable&&((kind==='revival'&&!POTION_CRAFTING.revivalProductionEnabled)||POTIONS[kind as Potion].tier!==tier))return {...s,notice:kind==='revival'?'회생 포션 제작법은 아직 공개되지 않았습니다.':'이 티어에서 제작할 수 없는 포션입니다.'};if((consumable&&quantity!==(kind==='revival'?POTION_CRAFTING.revivalBatch:POTION_CRAFTING.generalBatch))||(!consumable&&quantity!==1))return {...s,notice:consumable?'포션은 한 작업에 10개만 제작할 수 있습니다.':'장비는 한 작업에 1개만 제작할 수 있습니다.'};const field=fieldFor(kind),mat=materialFor(field),amount=cost(s,field,tier,now),isBusy=!!active(s);if(tier>s.mastery[field].unlocked)return {...s,notice:'이전 티어 제작으로 자격을 먼저 해금하세요.'};if(isBusy&&(!isGoldenRecorderActive(s,now)||queued(s).length>=GOLDEN_RECORDER_CRAFT_QUEUE_LIMIT))return {...s,notice:isGoldenRecorderActive(s,now)?'제작 대기열이 가득 찼습니다.':'현재 다른 제작이 진행 중입니다.'};if(s.materials[mat][tier-1]<amount)return {...s,notice:'제작 재료가 부족합니다.'};s.materials[mat][tier-1]-=amount;const j:CraftJob={jobId:'craft-'+s.crafting.nextJobId++,recipeId:`${kind}-${tier}`,itemId:kind,kind,tier,quantity,field,status:'QUEUED',queuedAt:now,startedAt:null,completesAt:null,durationMs:CRAFT_DURATION_MS,consumedMaterials:amount,consumedSilver:0};s.crafting.jobs.push(j);if(!isBusy)start(j,now);s.notice=isBusy?'제작 대기열에 추가했습니다.':'제작을 시작했습니다.';return s;}
export function cancelCraft(s0:GameState,jobId:string,now=Date.now()):GameState{let s=settleCrafting(s0,now);const j=s.crafting.jobs.find(x=>x.jobId===jobId&&(x.status==='CRAFTING'||x.status==='QUEUED'));if(!j)return {...s,notice:'취소할 제작 작업이 없습니다.'};s.materials[materialFor(j.field)][j.tier-1]+=j.consumedMaterials;s.silver+=j.consumedSilver;const wasCrafting=j.status==='CRAFTING';j.status='CANCELLED';const next=queued(s)[0];if(!active(s)&&next)start(next,now);s.notice='제작을 취소하고 자원을 반환했습니다.';return s;}
export function claimCraft(s0:GameState,jobId:string,now=Date.now()):GameState{const s=settleCrafting(s0,now),j=s.crafting.jobs.find(x=>x.jobId===jobId&&x.status==='COMPLETED_UNCLAIMED');if(!j)return {...s,notice:'수령할 완료품이 없습니다.'};if(potionIds.includes(j.kind as Potion))s.potions[j.kind as Potion]+=j.quantity;else s.items.push({id:'item-'+s.nextId++,kind:j.kind,tier:j.tier,enhancement:0});s.crafting.jobs=s.crafting.jobs.filter(x=>x.jobId!==jobId);s.notice='제작 완료품을 수령했습니다.';return s;}
export function claimAllCraft(s:GameState,now=Date.now()){return settleCrafting(s,now).crafting.jobs.filter(j=>j.status==='COMPLETED_UNCLAIMED').reduce((n,j)=>claimCraft(n,j.jobId,now),settleCrafting(s,now));}
export function craft(s:GameState,kind:string,tier:number,now=Date.now()):GameState{const quantity=potionIds.includes(kind as Potion)?10:1;const queued=startCraft(s,kind,tier,quantity,now);const current=queued.crafting.jobs.find(j=>j.status==='CRAFTING');if(!current)return queued;const done=claimCraft(settleCrafting(queued,(current.completesAt??now)+1),current.jobId,(current.completesAt??now)+1);if(potionIds.includes(kind as Potion))done.potions[kind as Potion]-=10-tier*2;return done;}



