import type {ActiveEffect,EffectDefinition,EffectTag,Expedition} from '../types';

export const EFFECTS:Record<string,EffectDefinition>={
 attack_up:{id:'attack_up',name:'공격 증가',description:'공격력이 증가합니다.',category:'BUFF',behavior:'STAT_MODIFIER',tags:['STAT_UP'],defaultDuration:3,stackingPolicy:'REFRESH_DURATION',payload:{stat:'attack',multiplier:.3}},
 defense_up:{id:'defense_up',name:'방어 증가',description:'방어력이 증가합니다.',category:'BUFF',behavior:'STAT_MODIFIER',tags:['STAT_UP'],defaultDuration:3,stackingPolicy:'REFRESH_DURATION',payload:{stat:'defense',multiplier:.4}},
 regen:{id:'regen',name:'재생',description:'턴 종료 시 체력을 회복합니다.',category:'BUFF',behavior:'PERIODIC_HEAL',tags:['HOT','REGEN'],defaultDuration:3,stackingPolicy:'REFRESH_DURATION',payload:{amount:.1}},
 guard:{id:'guard',name:'방어 태세',description:'받는 피해가 40% 감소합니다.',category:'BUFF',behavior:'STAT_MODIFIER',tags:['STAT_UP'],defaultDuration:4,stackingPolicy:'REFRESH_DURATION',payload:{stat:'receivedDamage',multiplier:-.4}},
 poison:{id:'poison',name:'중독',description:'턴 종료 시 피해를 받습니다.',category:'DEBUFF',behavior:'PERIODIC_DAMAGE',tags:['DOT','POISON'],defaultDuration:2,stackingPolicy:'REFRESH_DURATION',payload:{amount:5}},
 weaken:{id:'weaken',name:'방어 약화',description:'방어력이 감소합니다.',category:'DEBUFF',behavior:'STAT_MODIFIER',tags:['STAT_DOWN'],defaultDuration:2,stackingPolicy:'REFRESH_DURATION',payload:{stat:'defense',multiplier:-.2}},
 verdant_grace:{id:'verdant_grace',name:'녹빛 은총',description:'녹빛 생명력이 턴마다 체력을 회복합니다.',category:'BUFF',behavior:'PERIODIC_HEAL',tags:['HOT','REGEN'],defaultDuration:3,stackingPolicy:'REFRESH_DURATION',payload:{amount:.08}},
 green_incense:{id:'green_incense',name:'성유 독향',description:'오염된 향이 턴마다 피해를 줍니다.',category:'DEBUFF',behavior:'PERIODIC_DAMAGE',tags:['DOT','POISON'],defaultDuration:3,stackingPolicy:'REFRESH_DURATION',payload:{amount:5}},
 atonement_guard:{id:'atonement_guard',name:'대속 갑주',description:'대속의 흔적이 방어력을 크게 높입니다.',category:'BUFF',behavior:'STAT_MODIFIER',tags:['STAT_UP'],defaultDuration:3,stackingPolicy:'REFRESH_DURATION',payload:{stat:'defense',multiplier:.45}},
 confession_burden:{id:'confession_burden',name:'고해의 짐',description:'죄책에 짓눌려 공격력이 감소합니다.',category:'DEBUFF',behavior:'STAT_MODIFIER',tags:['STAT_DOWN'],defaultDuration:3,stackingPolicy:'REFRESH_DURATION',payload:{stat:'attack',multiplier:-.22}},
 stigmata_wound:{id:'stigmata_wound',name:'성흔 상처',description:'벌어진 성흔 때문에 받는 피해가 증가합니다.',category:'DEBUFF',behavior:'STAT_MODIFIER',tags:['STAT_DOWN'],defaultDuration:3,stackingPolicy:'REFRESH_DURATION',payload:{stat:'receivedDamage',multiplier:.15}},
 transferred_pain:{id:'transferred_pain',name:'전가된 고통',description:'옮겨진 고통이 턴마다 생명력을 깎습니다.',category:'DEBUFF',behavior:'PERIODIC_DAMAGE',tags:['DOT'],defaultDuration:3,stackingPolicy:'REFRESH_DURATION',payload:{amount:7}},
 atonement_mark:{id:'atonement_mark',name:'대속의 인장',description:'희생 대상으로 지목된 표식입니다.',category:'DEBUFF',behavior:'STAT_MODIFIER',tags:['STAT_DOWN'],defaultDuration:4,stackingPolicy:'REFRESH_DURATION'},
 sacrifice_mark:{id:'sacrifice_mark',name:'희생 표식',description:'집전관이 제물로 지목한 표식입니다. 3중첩 시 처형 의식이 준비됩니다.',category:'DEBUFF',behavior:'STAT_MODIFIER',tags:['STAT_DOWN'],defaultDuration:6,stackingPolicy:'STACK',maxStacks:3},
 atonement_shield:{id:'atonement_shield',name:'대속의 장막',description:'대속 십자가가 피해를 대신 받아냅니다.',category:'BUFF',behavior:'SHIELD',tags:['SHIELD'],defaultDuration:3,stackingPolicy:'REPLACE',shieldAmount:55,scope:'BATTLE'},
 false_grace_shield:{id:'false_grace_shield',name:'거짓 은총',description:'거짓 구원의 형상을 띤 보호막입니다.',category:'BUFF',behavior:'SHIELD',tags:['SHIELD'],defaultDuration:3,stackingPolicy:'REPLACE',shieldAmount:65,scope:'BATTLE'},
 kaleon_grace:{id:'kaleon_grace',name:'칼레온의 녹빛 은총',description:'흡수한 생명력으로 큰 폭의 재생을 얻습니다.',category:'BUFF',behavior:'PERIODIC_HEAL',tags:['HOT','REGEN'],defaultDuration:3,stackingPolicy:'REFRESH_DURATION',payload:{amount:.12}},
 kaleon_shield:{id:'kaleon_shield',name:'거짓 구원의 장막',description:'칼레온이 자신을 구원의 중심으로 삼아 펼친 보호막입니다.',category:'BUFF',behavior:'SHIELD',tags:['SHIELD'],defaultDuration:3,stackingPolicy:'REPLACE',shieldAmount:90,scope:'BATTLE'},
 atonement_debt:{id:'atonement_debt',name:'대속의 부채',description:'칼레온이 떠넘긴 고통의 몫입니다. 3중첩 시 대속 집행의 대상이 됩니다.',category:'DEBUFF',behavior:'STAT_MODIFIER',tags:['STAT_DOWN'],defaultDuration:7,stackingPolicy:'STACK',maxStacks:3},
 test_crack:{id:'test_crack',name:'TEST_CRACK',description:'개발용 균열 중첩입니다.',category:'DEBUFF',behavior:'STAT_MODIFIER',tags:['STAT_DOWN'],defaultDuration:5,stackingPolicy:'STACK',maxStacks:3,thresholdReaction:{threshold:3,removeSelf:true,removeEffectIds:['test_armor'],applyEffectIds:['test_exposed'],message:'TEST_CRACK 임계 반응 발동'}},
 test_armor:{id:'test_armor',name:'TEST_ARMOR',description:'개발용 방어 상태입니다.',category:'BUFF',behavior:'STAT_MODIFIER',tags:['STAT_UP'],defaultDuration:5,stackingPolicy:'REFRESH_DURATION',payload:{stat:'defense',multiplier:.4}},
 test_exposed:{id:'test_exposed',name:'TEST_EXPOSED',description:'개발용 노출 상태입니다.',category:'DEBUFF',behavior:'STAT_MODIFIER',tags:['STAT_DOWN'],defaultDuration:3,stackingPolicy:'REFRESH_DURATION',payload:{stat:'defense',multiplier:-.4}},
 test_resonance:{id:'test_resonance',name:'TEST_RESONANCE',description:'개발용 공진 중첩입니다.',category:'DEBUFF',behavior:'STAT_MODIFIER',tags:['STAT_DOWN'],defaultDuration:5,stackingPolicy:'STACK',maxStacks:5},
 test_latched_stack:{id:'test_latched_stack',name:'TEST_LATCHED_STACK',description:'개발용 경계 통과 검증 상태입니다.',category:'DEBUFF',behavior:'STAT_MODIFIER',tags:['STAT_DOWN'],defaultDuration:5,stackingPolicy:'STACK',maxStacks:3,thresholdReaction:{threshold:3,applyEffectIds:['test_exposed']}},
 test_shield:{id:'test_shield',name:'TEST_SHIELD',description:'개발용 공통 보호막입니다.',category:'BUFF',behavior:'SHIELD',tags:['SHIELD'],defaultDuration:3,stackingPolicy:'REPLACE',shieldAmount:30,scope:'BATTLE'},
 iron_armor:{id:'iron_armor',name:'흑맥 갑주',description:'방어력이 크게 증가합니다.',category:'BUFF',behavior:'STAT_MODIFIER',tags:['STAT_UP'],defaultDuration:99,stackingPolicy:'REFRESH_DURATION',payload:{stat:'defense',multiplier:.65}},
 fracture:{id:'fracture',name:'균열',description:'직접 공격을 받을 때 누적됩니다.',category:'DEBUFF',behavior:'STAT_MODIFIER',tags:['STAT_DOWN'],defaultDuration:99,stackingPolicy:'STACK',maxStacks:3,thresholdReaction:{threshold:3,removeSelf:true,removeEffectIds:['iron_armor'],applyEffectIds:['exposed_core'],message:'갑주가 파쇄되어 노출 상태가 되었습니다.'}},
 exposed_core:{id:'exposed_core',name:'노출',description:'방어력이 감소합니다.',category:'DEBUFF',behavior:'STAT_MODIFIER',tags:['STAT_DOWN'],defaultDuration:4,stackingPolicy:'REFRESH_DURATION',payload:{stat:'defense',multiplier:-.35}},
 resonance:{id:'resonance',name:'울림',description:'울림이 누적됩니다.',category:'DEBUFF',behavior:'STAT_MODIFIER',tags:['STAT_DOWN'],defaultDuration:5,stackingPolicy:'STACK',maxStacks:5},
 crushing_pressure:{id:'crushing_pressure',name:'압착 저주',description:'방어력이 감소합니다.',category:'DEBUFF',behavior:'STAT_MODIFIER',tags:['STAT_DOWN'],defaultDuration:3,stackingPolicy:'REFRESH_DURATION',payload:{stat:'defense',multiplier:-.3}},
 iron_core_shield:{id:'iron_core_shield',name:'철심 보호막',description:'철심의 보호막입니다.',category:'BUFF',behavior:'SHIELD',tags:['SHIELD'],defaultDuration:3,stackingPolicy:'REPLACE',shieldAmount:70,scope:'BATTLE'},
  blood_scent:{id:'blood_scent',name:'핏빛 추적',description:'약점을 꿰뚫어 보며 받는 피해가 증가합니다.',category:'DEBUFF',behavior:'STAT_MODIFIER',tags:['STAT_DOWN'],defaultDuration:3,stackingPolicy:'REFRESH_DURATION',payload:{stat:'receivedDamage',multiplier:.2}},
  predator_wound:{id:'predator_wound',name:'포식자의 상처',description:'깊은 상처로 턴마다 피해를 입습니다.',category:'DEBUFF',behavior:'PERIODIC_DAMAGE',tags:['DOT','BLEED'],defaultDuration:3,stackingPolicy:'REFRESH_DURATION',payload:{amount:6}},
  pack_defense:{id:'pack_defense',name:'무리의 방어',description:'무리의 결속으로 방어력이 크게 증가합니다.',category:'BUFF',behavior:'STAT_MODIFIER',tags:['STAT_UP'],defaultDuration:3,stackingPolicy:'REFRESH_DURATION',payload:{stat:'defense',multiplier:.5}},
  sanctuary_shield:{id:'sanctuary_shield',name:'성소의 보호막',description:'고대 의식으로 두른 신성한 보호막입니다.',category:'BUFF',behavior:'SHIELD',tags:['SHIELD'],defaultDuration:3,stackingPolicy:'REPLACE',shieldAmount:60,scope:'BATTLE'},
  ritual_brand:{id:'ritual_brand',name:'의식의 낙인',description:'성소의 의식으로 새겨진 낙인입니다.',category:'DEBUFF',behavior:'STAT_MODIFIER',tags:['STAT_DOWN'],defaultDuration:4,stackingPolicy:'REFRESH_DURATION'},
  lord_shield:{id:'lord_shield',name:'적아의 장막',description:'적아의 주인이 펼치는 절대적인 보호막입니다.',category:'BUFF',behavior:'SHIELD',tags:['SHIELD'],defaultDuration:3,stackingPolicy:'REPLACE',shieldAmount:85,scope:'BATTLE'},
  crimson_debt:{id:'crimson_debt',name:'진홍의 부채',description:'적아에게 진 빚입니다. 3중첩 시 피의 수확 대상이 됩니다.',category:'DEBUFF',behavior:'STAT_MODIFIER',tags:['STAT_DOWN'],defaultDuration:6,stackingPolicy:'STACK',maxStacks:3},
};
export type EffectActor='player'|'monster';
const effectsFor=(e:Expedition,actor:EffectActor)=>actor==='player'?e.playerEffects:e.monsterEffects;
const sort=(effects:ActiveEffect[])=>[...effects].sort((a,b)=>a.applicationSequence-b.applicationSequence);
export interface EffectApplicationResult {previousStacks:number;newStacks:number;thresholdTriggered:boolean;message?:string}
function transition(e:Expedition,actor:EffectActor,definition:EffectDefinition,previousStacks:number,newStacks:number,source:EffectActor,turn:number,depth:number):EffectApplicationResult {const threshold=definition.thresholdReaction;if(!threshold||previousStacks>=threshold.threshold||newStacks<threshold.threshold)return {previousStacks,newStacks,thresholdTriggered:false};if(threshold.removeSelf)removeEffectById(e,actor,definition.id);for(const id of threshold.removeEffectIds??[])removeEffectById(e,actor,id);for(const id of threshold.applyEffectIds??[])applyEffectInternal(e,actor,id,source,turn,depth+1);return {previousStacks,newStacks,thresholdTriggered:true,message:threshold.message};}
function validShieldDefinition(definition:EffectDefinition){return definition.behavior!=='SHIELD'||(Number.isFinite(definition.shieldAmount)&&Number(definition.shieldAmount)>0&&definition.defaultDuration>0&&definition.stackingPolicy==='REPLACE'&&(definition.scope??'BATTLE')==='BATTLE'&&!definition.maxStacks&&!definition.thresholdReaction);}
function applyEffectInternal(e:Expedition,actor:EffectActor,effectId:string,source:EffectActor,turn:number,depth:number):EffectApplicationResult|undefined {if(depth>8)return;const definition=EFFECTS[effectId];if(!definition||!validShieldDefinition(definition))return;const list=effectsFor(e,actor);if(definition.behavior==='SHIELD')for(let index=list.length-1;index>=0;index--){const candidate=EFFECTS[list[index].effectId];if(candidate?.behavior==='SHIELD')list.splice(index,1);}const active=list.find(effect=>effect.effectId===effectId),previousStacks=active?.stackCount??0;if(active){if(definition.stackingPolicy==='IGNORE_IF_ACTIVE')return {previousStacks,newStacks:previousStacks,thresholdTriggered:false};if(definition.stackingPolicy==='STACK')active.stackCount=Math.min(definition.maxStacks??99,active.stackCount+1);if(definition.stackingPolicy==='REPLACE')list.splice(list.indexOf(active),1);else {active.remainingDuration=definition.defaultDuration;active.createdTurn=turn;return transition(e,actor,definition,previousStacks,active.stackCount,source,turn,depth);}}
 const created:ActiveEffect={instanceId:`effect-${++e.effectSequence}`,effectId,sourceActorId:source,targetActorId:actor,remainingDuration:definition.defaultDuration,stackCount:1,applicationSequence:e.effectSequence,createdTurn:turn,scope:definition.scope??'BATTLE',...(definition.behavior==='SHIELD'?{currentShield:definition.shieldAmount}: {})};list.push(created);return transition(e,actor,definition,previousStacks,created.stackCount,source,turn,depth);
}
export function applyEffect(e:Expedition,actor:EffectActor,effectId:string,source:EffectActor,turn:number){return applyEffectInternal(e,actor,effectId,source,turn,0);}
export function removeEffectsByTag(e:Expedition,actor:EffectActor,tag:EffectTag){const list=effectsFor(e,actor);list.splice(0,list.length,...list.filter(effect=>!EFFECTS[effect.effectId]?.tags.includes(tag)));}
export function removeEffectById(e:Expedition,actor:EffectActor,effectId:string){const list=effectsFor(e,actor);list.splice(0,list.length,...list.filter(effect=>effect.effectId!==effectId));}
export function effectStacks(effects:ActiveEffect[],effectId:string){const active=effects.find(effect=>effect.effectId===effectId&&effect.remainingDuration>0&&effect.stackCount>0);return active?.stackCount??0;}
export function hasEffect(effects:ActiveEffect[],effectId:string){return effectStacks(effects,effectId)>0;}
export function validateEffectDefinitions(catalog:Record<string,EffectDefinition>=EFFECTS){const errors:string[]=[];for(const definition of Object.values(catalog)){if(!definition.id)errors.push('effect: missing id');if(!Number.isSafeInteger(definition.defaultDuration)||definition.defaultDuration<1)errors.push(`${definition.id}: invalid duration`);if(definition.behavior==='SHIELD'){if(!Number.isFinite(definition.shieldAmount)||Number(definition.shieldAmount)<=0)errors.push(`${definition.id}: invalid shield amount`);if(definition.stackingPolicy!=='REPLACE')errors.push(`${definition.id}: shield requires REPLACE policy`);if((definition.scope??'BATTLE')!=='BATTLE')errors.push(`${definition.id}: shield scope must be BATTLE`);if(definition.maxStacks||definition.thresholdReaction)errors.push(`${definition.id}: shield cannot use stack threshold`);}const threshold=definition.thresholdReaction;if(!threshold)continue;if(!Number.isSafeInteger(threshold.threshold)||threshold.threshold<1)errors.push(`${definition.id}: invalid threshold`);if(definition.stackingPolicy!=='STACK')errors.push(`${definition.id}: threshold requires STACK policy`);for(const id of [...(threshold.removeEffectIds??[]),...(threshold.applyEffectIds??[])])if(!catalog[id])errors.push(`${definition.id}: unknown transition effect ${id}`);}return errors;}
export interface DamageAbsorption {incomingDamage:number;absorbedByShield:number;hpDamage:number;shieldBefore:number;shieldAfter:number}
export function activeShield(e:Expedition,actor:EffectActor){return sort(effectsFor(e,actor)).reverse().find(effect=>EFFECTS[effect.effectId]?.behavior==='SHIELD'&&(effect.currentShield??0)>0);}
export function applyIncomingDamage(e:Expedition,actor:EffectActor,incomingDamage:number):DamageAbsorption {const incoming=Math.max(0,incomingDamage),shield=activeShield(e,actor),before=shield?.currentShield??0,absorbed=Math.min(before,incoming),after=Math.max(0,before-absorbed),hpDamage=incoming-absorbed;if(shield){shield.currentShield=after;if(after<=0)removeEffectById(e,actor,shield.effectId);}return {incomingDamage:incoming,absorbedByShield:absorbed,hpDamage,shieldBefore:before,shieldAfter:after};}
export function modifier(e:Expedition,actor:EffectActor,stat:'attack'|'defense'|'receivedDamage'){return sort(effectsFor(e,actor)).reduce((value,effect)=>{const d=EFFECTS[effect.effectId];return d?.behavior==='STAT_MODIFIER'&&d.payload?.stat===stat?value+(d.payload.multiplier??0)*effect.stackCount:value;},0);}
export function periodicDelta(e:Expedition,actor:EffectActor,maxHp:number,turn:number){return sort(effectsFor(e,actor)).filter(effect=>effect.createdTurn!==turn).reduce((total,effect)=>{const d=EFFECTS[effect.effectId];if(!d)return total;if(d.behavior==='PERIODIC_DAMAGE')return total-(d.payload?.amount??0)*effect.stackCount;if(d.behavior==='PERIODIC_HEAL')return total+maxHp*(d.payload?.amount??0)*effect.stackCount;return total;},0);}
export function expireTurnEffects(e:Expedition,actor:EffectActor,turn:number){const list=effectsFor(e,actor);for(const effect of list)if(effect.createdTurn!==turn)effect.remainingDuration--;list.splice(0,list.length,...list.filter(effect=>effect.remainingDuration>0));}
export function clearBattleEffects(e:Expedition){e.playerEffects=e.playerEffects.filter(x=>x.scope==='EXPEDITION');e.monsterEffects=e.monsterEffects.filter(x=>x.scope==='EXPEDITION');e.preparedEffects=e.preparedEffects.filter(x=>x.scope==='EXPEDITION');e.reactivePrepared={player:null,monster:null};}
