import {combatRuntime} from './battleLifecycle';
import type {ActiveEffect,EffectDefinition,EffectTag,Expedition} from '../types';

export const EFFECTS:Record<string,EffectDefinition>={
 iron_attack_down_15:{"id":"iron_attack_down_15","name":"광석 가루","description":"광석 가루","category":"DEBUFF","behavior":"STAT_MODIFIER","tags":["STAT_DOWN"],"defaultDuration":2,"stackingPolicy":"EXTEND_DURATION","payload":{"stat":"attack","multiplier":-0.15}},
 iron_attack_down_20:{"id":"iron_attack_down_20","name":"날카로운 울음","description":"날카로운 울음","category":"DEBUFF","behavior":"STAT_MODIFIER","tags":["STAT_DOWN"],"defaultDuration":2,"stackingPolicy":"EXTEND_DURATION","payload":{"stat":"attack","multiplier":-0.2}},
 iron_defense_down_15:{"id":"iron_defense_down_15","name":"철맥 상처","description":"철맥 상처","category":"DEBUFF","behavior":"STAT_MODIFIER","tags":["STAT_DOWN"],"defaultDuration":2,"stackingPolicy":"EXTEND_DURATION","payload":{"stat":"defense","multiplier":-0.15}},
 iron_attack_20:{"id":"iron_attack_20","name":"작업 독촉","description":"작업 독촉","category":"BUFF","behavior":"STAT_MODIFIER","tags":["STAT_UP"],"defaultDuration":2,"stackingPolicy":"EXTEND_DURATION","payload":{"stat":"attack","multiplier":0.2}},
 iron_guard_25:{"id":"iron_guard_25","name":"철턱 움츠리기","description":"철턱 움츠리기","category":"BUFF","behavior":"STAT_MODIFIER","tags":["STAT_UP"],"defaultDuration":2,"stackingPolicy":"EXTEND_DURATION","payload":{"stat":"receivedDamage","multiplier":-0.25}},
 iron_pressure:{"id":"iron_pressure","name":"철맥 압박","description":"철맥 압박","category":"DEBUFF","behavior":"STAT_MODIFIER","tags":["STAT_DOWN"],"defaultDuration":2,"stackingPolicy":"EXTEND_DURATION","payload":{"stat":"defense","multiplier":-0.2}},
 iron_carrier_shield:{"id":"iron_carrier_shield","name":"광석 자루 방패","description":"광석 자루 방패","category":"BUFF","behavior":"SHIELD","tags":["SHIELD"],"defaultDuration":3,"stackingPolicy":"REPLACE","shieldPercent":0.15,"scope":"BATTLE"},
 iron_echo_shield:{"id":"iron_echo_shield","name":"공명 차폐","description":"공명 차폐","category":"BUFF","behavior":"SHIELD","tags":["SHIELD"],"defaultDuration":3,"stackingPolicy":"REPLACE","shieldPercent":0.12,"scope":"BATTLE"},

b_attack_20:{"id": "b_attack_20", "name": "공격 강화", "description": "2턴간 공격 피해 증가 20%", "category": "BUFF", "behavior": "STAT_MODIFIER", "tags": ["STAT_UP"], "defaultDuration": 2, "stackingPolicy": "REFRESH_DURATION", "payload": {"stat": "outgoingDamage", "multiplier": 0.2}},
b_attack_25:{"id": "b_attack_25", "name": "공격 강화", "description": "2턴간 공격 피해 증가 25%", "category": "BUFF", "behavior": "STAT_MODIFIER", "tags": ["STAT_UP"], "defaultDuration": 2, "stackingPolicy": "REFRESH_DURATION", "payload": {"stat": "outgoingDamage", "multiplier": 0.25}},
b_guard_15:{"id": "b_guard_15", "name": "피해 감소", "description": "2턴간 받는 피해 감소 15%", "category": "BUFF", "behavior": "STAT_MODIFIER", "tags": ["STAT_UP"], "defaultDuration": 2, "stackingPolicy": "REFRESH_DURATION", "payload": {"stat": "receivedDamage", "multiplier": -0.15}},
b_guard_30:{"id": "b_guard_30", "name": "피해 감소", "description": "2턴간 받는 피해 감소 30%", "category": "BUFF", "behavior": "STAT_MODIFIER", "tags": ["STAT_UP"], "defaultDuration": 2, "stackingPolicy": "REFRESH_DURATION", "payload": {"stat": "receivedDamage", "multiplier": -0.3}},

 attack_up:{id:'attack_up',name:'공격 증가',description:'공격력이 증가합니다.',category:'BUFF',behavior:'STAT_MODIFIER',tags:['STAT_UP'],defaultDuration:3,stackingPolicy:'REFRESH_DURATION',payload:{stat:'attack',multiplier:.3}},
 defense_up:{id:'defense_up',name:'방어 증가',description:'방어력이 증가합니다.',category:'BUFF',behavior:'STAT_MODIFIER',tags:['STAT_UP'],defaultDuration:3,stackingPolicy:'REFRESH_DURATION',payload:{stat:'defense',multiplier:.4}},
 regen:{id:'regen',name:'재생',description:'턴 종료 시 체력을 회복합니다.',category:'BUFF',behavior:'PERIODIC_HEAL',tags:['HOT','REGEN'],defaultDuration:3,stackingPolicy:'REFRESH_DURATION',payload:{amount:.1}},
 guard:{id:'guard',name:'방어 태세',description:'받는 피해가 40% 감소합니다.',category:'BUFF',behavior:'STAT_MODIFIER',tags:['STAT_UP'],defaultDuration:4,stackingPolicy:'REFRESH_DURATION',payload:{stat:'receivedDamage',multiplier:-.4}},
 poison:{id:'poison',name:'중독',description:'턴 종료 시 피해를 받습니다.',category:'DEBUFF',behavior:'PERIODIC_DAMAGE',tags:['DOT','POISON'],defaultDuration:2,stackingPolicy:'REFRESH_DURATION',payload:{amount:5}},
 bleed:{id:'bleed',name:'출혈',description:'턴 종료 시 피해를 받습니다.',category:'DEBUFF',behavior:'PERIODIC_DAMAGE',tags:['DOT','BLEED'],defaultDuration:2,stackingPolicy:'REFRESH_DURATION',payload:{amount:5}},
 weaken:{id:'weaken',name:'방어 약화',description:'방어력이 감소합니다.',category:'DEBUFF',behavior:'STAT_MODIFIER',tags:['STAT_DOWN'],defaultDuration:2,stackingPolicy:'REFRESH_DURATION',payload:{stat:'defense',multiplier:-.2}},
 test_crack:{id:'test_crack',name:'TEST_CRACK',description:'개발용 균열 중첩입니다.',category:'DEBUFF',behavior:'STAT_MODIFIER',tags:['STAT_DOWN'],defaultDuration:5,stackingPolicy:'STACK',maxStacks:3,thresholdReaction:{threshold:3,removeSelf:true,removeEffectIds:['test_armor'],applyEffectIds:['test_exposed'],message:'TEST_CRACK 임계 반응 발동'}},
 test_armor:{id:'test_armor',name:'TEST_ARMOR',description:'개발용 방어 상태입니다.',category:'BUFF',behavior:'STAT_MODIFIER',tags:['STAT_UP'],defaultDuration:5,stackingPolicy:'REFRESH_DURATION',payload:{stat:'defense',multiplier:.4}},
 test_exposed:{id:'test_exposed',name:'TEST_EXPOSED',description:'개발용 노출 상태입니다.',category:'DEBUFF',behavior:'STAT_MODIFIER',tags:['STAT_DOWN'],defaultDuration:3,stackingPolicy:'REFRESH_DURATION',payload:{stat:'defense',multiplier:-.4}},
 test_resonance:{id:'test_resonance',name:'TEST_RESONANCE',description:'개발용 공진 중첩입니다.',category:'DEBUFF',behavior:'STAT_MODIFIER',tags:['STAT_DOWN'],defaultDuration:5,stackingPolicy:'STACK',maxStacks:5},
 test_latched_stack:{id:'test_latched_stack',name:'TEST_LATCHED_STACK',description:'개발용 경계 통과 검증 상태입니다.',category:'DEBUFF',behavior:'STAT_MODIFIER',tags:['STAT_DOWN'],defaultDuration:5,stackingPolicy:'STACK',maxStacks:3,thresholdReaction:{threshold:3,applyEffectIds:['test_exposed']}},
 test_shield:{id:'test_shield',name:'TEST_SHIELD',description:'개발용 공통 보호막입니다.',category:'BUFF',behavior:'SHIELD',tags:['SHIELD'],defaultDuration:3,stackingPolicy:'REPLACE',shieldAmount:30,scope:'BATTLE'},
 test_hit_shield:{id:'test_hit_shield',name:'TEST_HIT_SHIELD',description:'개발용 타격 보호막입니다.',category:'BUFF',behavior:'SHIELD',tags:['SHIELD'],defaultDuration:3,stackingPolicy:'REPLACE',shieldHits:2,scope:'BATTLE'},
 iron_armor:{id:'iron_armor',name:'흑맥 갑주',description:'방어력이 크게 증가합니다.',category:'BUFF',behavior:'STAT_MODIFIER',tags:['STAT_UP'],defaultDuration:3,stackingPolicy:'REFRESH_DURATION',payload:{stat:'defense',multiplier:.5}},
 fracture:{id:'fracture',name:'균열',description:'직접 공격을 받을 때 누적됩니다.',category:'DEBUFF',behavior:'STAT_MODIFIER',tags:['STAT_DOWN'],defaultDuration:99,stackingPolicy:'STACK',maxStacks:3,thresholdReaction:{threshold:3,removeSelf:true,removeEffectIds:['iron_armor'],applyEffectIds:['exposed_core'],message:'갑주가 파쇄되어 노출 상태가 되었습니다.'}},
 exposed_core:{id:'exposed_core',name:'노출',description:'방어력이 감소합니다.',category:'DEBUFF',behavior:'STAT_MODIFIER',tags:['STAT_DOWN'],defaultDuration:2,stackingPolicy:'REFRESH_DURATION',payload:{stat:'defense',multiplier:-.35}},
 resonance:{id:'resonance',name:'울림',description:'공명 돌진의 대상이 됩니다.',category:'DEBUFF',behavior:'STAT_MODIFIER',tags:['STAT_DOWN'],defaultDuration:3,stackingPolicy:'STACK',maxStacks:5},
 crushing_pressure:{id:'crushing_pressure',name:'압착 저주',description:'방어력이 감소합니다.',category:'DEBUFF',behavior:'STAT_MODIFIER',tags:['STAT_DOWN'],defaultDuration:3,stackingPolicy:'REFRESH_DURATION',payload:{stat:'defense',multiplier:-.3}},
 iron_core_shield:{id:'iron_core_shield',name:'철심 보호막',description:'철심의 보호막입니다.',category:'BUFF',behavior:'SHIELD',tags:['SHIELD'],defaultDuration:3,stackingPolicy:'REPLACE',shieldPercent:.15,scope:'BATTLE'},
 fang_wound:{id:'fang_wound',name:'송곳니 출혈',description:'직접 공격을 받으면 누적되는 출혈입니다.',category:'DEBUFF',behavior:'PERIODIC_DAMAGE',tags:['DOT','BLEED'],defaultDuration:3,stackingPolicy:'STACK',maxStacks:3,payload:{amount:6}},
 blood_rite_ward:{id:'blood_rite_ward',name:'혈의식 수호',description:'성소의 수호막입니다.',category:'BUFF',behavior:'SHIELD',tags:['SHIELD'],defaultDuration:3,stackingPolicy:'REPLACE',shieldAmount:60,scope:'BATTLE'},
 red_mantle_shield:{id:'red_mantle_shield',name:'적아 외피',description:'적아의 주인의 외피입니다.',category:'BUFF',behavior:'SHIELD',tags:['SHIELD'],defaultDuration:3,stackingPolicy:'REPLACE',shieldAmount:75,scope:'BATTLE'},
 crystal_shell:{id:'crystal_shell',name:'결정막',description:'얇은 결정 보호막입니다.',category:'BUFF',behavior:'SHIELD',tags:['SHIELD'],defaultDuration:3,stackingPolicy:'REPLACE',shieldAmount:32,scope:'BATTLE'},
 crystal_bastion:{id:'crystal_bastion',name:'백정장벽',description:'두꺼운 백색 결정 보호막입니다.',category:'BUFF',behavior:'SHIELD',tags:['SHIELD'],defaultDuration:3,stackingPolicy:'REPLACE',shieldAmount:65,scope:'BATTLE'},
 crystal_core_shield:{id:'crystal_core_shield',name:'심핵장벽',description:'심핵을 감싸는 고밀도 결정 보호막입니다.',category:'BUFF',behavior:'SHIELD',tags:['SHIELD'],defaultDuration:3,stackingPolicy:'REPLACE',shieldAmount:85,scope:'BATTLE'},
 crystal_hardening:{id:'crystal_hardening',name:'결정경화',description:'결정층이 굳어 방어력이 증가합니다.',category:'BUFF',behavior:'STAT_MODIFIER',tags:['STAT_UP'],defaultDuration:3,stackingPolicy:'REFRESH_DURATION',payload:{stat:'defense',multiplier:.35}},
 crystal_growth:{id:'crystal_growth',name:'천광증폭',description:'결정핵의 출력으로 공격력이 증가합니다.',category:'BUFF',behavior:'STAT_MODIFIER',tags:['STAT_UP'],defaultDuration:3,stackingPolicy:'REFRESH_DURATION',payload:{stat:'attack',multiplier:.25}},
 crystal_regen:{id:'crystal_regen',name:'광핵재생',description:'턴 종료 시 최대 HP 일부를 회복합니다.',category:'BUFF',behavior:'PERIODIC_HEAL',tags:['HOT','REGEN'],defaultDuration:3,stackingPolicy:'REFRESH_DURATION',payload:{amount:.06}},
 crystal_glare:{id:'crystal_glare',name:'탁광',description:'굴절된 빛이 공격력을 낮춥니다.',category:'DEBUFF',behavior:'STAT_MODIFIER',tags:['STAT_DOWN'],defaultDuration:2,stackingPolicy:'REFRESH_DURATION',payload:{stat:'attack',multiplier:-.2}},
 crystal_venom:{id:'crystal_venom',name:'광독',description:'결정성 독이 턴 종료 시 피해를 줍니다.',category:'DEBUFF',behavior:'PERIODIC_DAMAGE',tags:['DOT','POISON'],defaultDuration:3,stackingPolicy:'REFRESH_DURATION',payload:{amount:5}},
 crystal_fracture:{id:'crystal_fracture',name:'결정 균열',description:'결정성 상처가 누적되어 방어력을 낮춥니다.',category:'DEBUFF',behavior:'STAT_MODIFIER',tags:['STAT_DOWN'],defaultDuration:5,stackingPolicy:'STACK',maxStacks:3,payload:{stat:'defense',multiplier:-.08}},
 hunter_mark:{id:'hunter_mark',name:'사냥감 표식',description:'추적 중인 사냥감 표식입니다.',category:'DEBUFF',behavior:'STAT_MODIFIER',tags:['STAT_DOWN'],defaultDuration:3,stackingPolicy:'REFRESH_DURATION'},
 mercenary_guard:{id:'mercenary_guard',name:'방패 올리기',description:'받는 피해가 25% 감소합니다.',category:'BUFF',behavior:'STAT_MODIFIER',tags:['STAT_UP'],defaultDuration:2,stackingPolicy:'REFRESH_DURATION',payload:{stat:'receivedDamage',multiplier:-.25}},
 field_medic_regen:{id:'field_medic_regen',name:'지혈 재생',description:'턴당 최대 HP 5%를 회복합니다.',category:'BUFF',behavior:'PERIODIC_HEAL',tags:['HOT','REGEN'],defaultDuration:3,stackingPolicy:'REFRESH_DURATION',payload:{amount:.05}},
 field_medic_analgesic:{id:'field_medic_analgesic',name:'진통제',description:'받는 피해가 30% 감소합니다.',category:'BUFF',behavior:'STAT_MODIFIER',tags:['STAT_UP'],defaultDuration:2,stackingPolicy:'REFRESH_DURATION',payload:{stat:'receivedDamage',multiplier:-.3}},
 duelist_counter_stance:{id:'duelist_counter_stance',name:'받아치기 태세',description:'다음 직접 공격을 반격 준비합니다.',category:'BUFF',behavior:'STAT_MODIFIER',tags:['STAT_UP'],defaultDuration:2,stackingPolicy:'REFRESH_DURATION',payload:{stat:'receivedDamage',multiplier:-.4}},
 kaleon_regen:{id:'kaleon_regen',name:'녹빛 재생',description:'비정상적인 조직 재생으로 턴 종료 시 최대 HP의 7%를 회복합니다.',category:'BUFF',behavior:'PERIODIC_HEAL',tags:['HOT','REGEN'],defaultDuration:3,stackingPolicy:'REFRESH_DURATION',payload:{amount:.07}},
 kaleon_blight:{id:'kaleon_blight',name:'녹병',description:'녹화 오염이 턴 종료 시 피해를 줍니다.',category:'DEBUFF',behavior:'PERIODIC_DAMAGE',tags:['DOT','POISON'],defaultDuration:3,stackingPolicy:'REFRESH_DURATION',payload:{amount:7}},
 kaleon_overgrowth:{id:'kaleon_overgrowth',name:'과잉 증식',description:'증식 조직이 몸을 덮어 방어력이 증가합니다.',category:'BUFF',behavior:'STAT_MODIFIER',tags:['STAT_UP'],defaultDuration:3,stackingPolicy:'REFRESH_DURATION',payload:{stat:'defense',multiplier:.3}},
 kaleon_transfer_mark:{id:'kaleon_transfer_mark',name:'전이 표식',description:'고통의 전이 경로가 누적됩니다.',category:'DEBUFF',behavior:'STAT_MODIFIER',tags:['STAT_DOWN'],defaultDuration:5,stackingPolicy:'STACK',maxStacks:3,payload:{stat:'defense',multiplier:-.05}},
 kaleon_saint_ward:{id:'kaleon_saint_ward',name:'수용자의 장벽',description:'칼레온이 오염을 억누르는 조직 장벽을 전개합니다.',category:'BUFF',behavior:'SHIELD',tags:['SHIELD'],defaultDuration:3,stackingPolicy:'REPLACE',shieldAmount:90,scope:'BATTLE'},
 c_attack_15:{id:'c_attack_15',name:'공격력 강화 15%',description:'공격력 강화 15%',category:'BUFF',behavior:'STAT_MODIFIER',tags:['STAT_UP'],defaultDuration:2,stackingPolicy:'EXTEND_DURATION',payload:{stat:'attack',multiplier:0.15}},
 c_attack_20:{id:'c_attack_20',name:'공격력 강화 20%',description:'공격력 강화 20%',category:'BUFF',behavior:'STAT_MODIFIER',tags:['STAT_UP'],defaultDuration:2,stackingPolicy:'EXTEND_DURATION',payload:{stat:'attack',multiplier:0.2}},
 c_attack_25:{id:'c_attack_25',name:'공격력 강화 25%',description:'공격력 강화 25%',category:'BUFF',behavior:'STAT_MODIFIER',tags:['STAT_UP'],defaultDuration:2,stackingPolicy:'EXTEND_DURATION',payload:{stat:'attack',multiplier:0.25}},
 c_defense_25:{id:'c_defense_25',name:'방어력 강화 25%',description:'방어력 강화 25%',category:'BUFF',behavior:'STAT_MODIFIER',tags:['STAT_UP'],defaultDuration:2,stackingPolicy:'EXTEND_DURATION',payload:{stat:'defense',multiplier:0.25}},
 c_defense_30:{id:'c_defense_30',name:'방어력 강화 30%',description:'방어력 강화 30%',category:'BUFF',behavior:'STAT_MODIFIER',tags:['STAT_UP'],defaultDuration:2,stackingPolicy:'EXTEND_DURATION',payload:{stat:'defense',multiplier:0.3}},
 c_porter_shield_18:{id:'c_porter_shield_18',name:'짐꾼 보호막 18%',description:'최대 HP의 18% 보호막',category:'BUFF',behavior:'SHIELD',tags:['SHIELD'],defaultDuration:3,stackingPolicy:'REPLACE',shieldPercent:0.18,scope:'BATTLE'},
 c_porter_shield_30:{id:'c_porter_shield_30',name:'짐꾼 보호막 30%',description:'최대 HP의 30% 보호막',category:'BUFF',behavior:'SHIELD',tags:['SHIELD'],defaultDuration:3,stackingPolicy:'REPLACE',shieldPercent:0.3,scope:'BATTLE'},
 berserker_blood_boost:{id:'berserker_blood_boost',name:'피의 대가',description:'공격 피해가 25% 증가합니다.',category:'BUFF',behavior:'STAT_MODIFIER',tags:['STAT_UP'],defaultDuration:3,stackingPolicy:'REFRESH_DURATION',payload:{stat:'attack',multiplier:.25}},
};
for(const d of Object.values(EFFECTS))if(!d.id.startsWith('test_')&&d.behavior!=='SHIELD'){
 d.stackingPolicy='EXTEND_DURATION';delete d.maxStacks;delete d.thresholdReaction;
}
for(const id of ['stun','silence','root'] as const)EFFECTS[id]={id,name:{stun:'기절',silence:'침묵',root:'속박'}[id],description:'행동 제한',category:'DEBUFF',behavior:'CONTROL',tags:['CONTROL',id.toUpperCase() as EffectTag],defaultDuration:1,stackingPolicy:'EXTEND_DURATION'};
export type EffectActor='player'|'monster';
const effectsFor=(e:Expedition,actor:EffectActor)=>actor==='player'?e.playerEffects:e.monsterEffects;
const sort=(effects:ActiveEffect[])=>[...effects].sort((a,b)=>a.applicationSequence-b.applicationSequence);
export interface EffectApplicationResult {previousStacks:number;newStacks:number;thresholdTriggered:boolean;message?:string;immune?:boolean}
function transition(e:Expedition,actor:EffectActor,definition:EffectDefinition,previousStacks:number,newStacks:number,source:EffectActor,turn:number,depth:number):EffectApplicationResult {const threshold=definition.thresholdReaction;if(!threshold||previousStacks>=threshold.threshold||newStacks<threshold.threshold)return {previousStacks,newStacks,thresholdTriggered:false};if(threshold.removeSelf)removeEffectById(e,actor,definition.id);for(const id of threshold.removeEffectIds??[])removeEffectById(e,actor,id);for(const id of threshold.applyEffectIds??[])applyEffectInternal(e,actor,id,source,turn,depth+1);return {previousStacks,newStacks,thresholdTriggered:true,message:threshold.message};}
function validShieldDefinition(definition:EffectDefinition){const modes=Number(Number.isFinite(definition.shieldAmount)&&Number(definition.shieldAmount)>0)+Number(Number.isFinite(definition.shieldPercent)&&Number(definition.shieldPercent)>0)+Number(Number.isSafeInteger(definition.shieldHits)&&Number(definition.shieldHits)>0);return definition.behavior!=='SHIELD'||(modes===1&&definition.defaultDuration>0&&definition.stackingPolicy==='REPLACE'&&(definition.scope??'BATTLE')==='BATTLE'&&!definition.maxStacks&&!definition.thresholdReaction);}
function applyEffectInternal(e:Expedition,actor:EffectActor,effectId:string,source:EffectActor,turn:number,depth:number,duration?:number):EffectApplicationResult|undefined {if(depth>8)return;const base=EFFECTS[effectId];const definition=base?{...base,...(duration!==undefined?{defaultDuration:duration}:{}),...(base.shieldPercent!==undefined?{shieldAmount:Math.round((actor==='player'?combatRuntime(e).playerMaxHp:e.monster.hp)*base.shieldPercent),shieldPercent:undefined}:{})}:undefined;if(!definition||!validShieldDefinition(definition))return;
 if(actor==='monster'&&e.monsterRuntime?.effectImmunities?.some(id=>id===effectId||definition.tags.includes(id as EffectTag)))return {previousStacks:0,newStacks:0,thresholdTriggered:false,immune:true};if(actor==='monster'&&definition.tags.includes('STUN')&&e.monsterRuntime){e.monsterRuntime.preparedActionId=null;e.monsterRuntime.eventFlags??={};e.monsterRuntime.eventFlags.interrupted=true;e.monsterRuntime.eventFlags.stunned=true;}if(e.monsterRuntime){e.monsterRuntime.effectApplications??={};if(actor==='monster'&&effectId==='iron_armor'){e.monsterRuntime.effectApplications['monster:fracture']=0;removeEffectById(e,'monster','fracture');}const key=actor+':'+effectId;e.monsterRuntime.effectApplications[key]=(e.monsterRuntime.effectApplications[key]??0)+1;}const list=effectsFor(e,actor);if(definition.behavior==='SHIELD')for(let index=list.length-1;index>=0;index--){const candidate=EFFECTS[list[index].effectId];if(candidate?.behavior==='SHIELD'&&definition.shieldHits)list.splice(index,1);}const active=list.find(effect=>effect.effectId===effectId),previousStacks=active?.stackCount??0;if(active){if(definition.stackingPolicy==='EXTEND_DURATION'){active.remainingDuration+=definition.defaultDuration;return {previousStacks,newStacks:active.stackCount,thresholdTriggered:false};}if(definition.behavior==='SHIELD'&&definition.shieldAmount){const cap=3*(actor==='player'?combatRuntime(e).playerMaxHp:e.monster.hp);active.currentShield=Math.min(Math.max(0,cap-shieldTotal(e,actor)+(active.currentShield??0)),(active.currentShield??0)+definition.shieldAmount);return {previousStacks,newStacks:1,thresholdTriggered:false};}if(definition.stackingPolicy==='IGNORE_IF_ACTIVE')return {previousStacks,newStacks:previousStacks,thresholdTriggered:false};if(definition.stackingPolicy==='STACK')active.stackCount=Math.min(definition.maxStacks??99,active.stackCount+1);if(definition.stackingPolicy==='REPLACE')list.splice(list.indexOf(active),1);else {active.remainingDuration=definition.defaultDuration;active.createdTurn=turn;return transition(e,actor,definition,previousStacks,active.stackCount,source,turn,depth);}}
 const shieldAmount=definition.behavior==='SHIELD'&&definition.shieldAmount?Math.min(definition.shieldAmount,Math.max(0,3*(actor==='player'?combatRuntime(e).playerMaxHp:e.monster.hp)-shieldTotal(e,actor))):undefined;
 if(shieldAmount===0)return {previousStacks,newStacks:previousStacks,thresholdTriggered:false};
 const created:ActiveEffect={instanceId:`effect-${++e.effectSequence}`,effectId,sourceActorId:source,targetActorId:actor,remainingDuration:definition.defaultDuration,stackCount:1,applicationSequence:e.effectSequence,createdTurn:turn,scope:definition.scope??'BATTLE',...(shieldAmount!==undefined?{currentShield:shieldAmount}: {}),...(definition.behavior==='SHIELD'&&definition.shieldHits?{currentShieldHits:definition.shieldHits}: {})};list.push(created);return transition(e,actor,definition,previousStacks,created.stackCount,source,turn,depth);
}
export function applyEffect(e:Expedition,actor:EffectActor,effectId:string,source:EffectActor,turn:number,duration?:number){return applyEffectInternal(e,actor,effectId,source,turn,0,duration);}
export function removeEffectsByTag(e:Expedition,actor:EffectActor,tag:EffectTag){const list=effectsFor(e,actor);list.splice(0,list.length,...list.filter(effect=>!EFFECTS[effect.effectId]?.tags.includes(tag)));}
export function removeEffectById(e:Expedition,actor:EffectActor,effectId:string){const list=effectsFor(e,actor);list.splice(0,list.length,...list.filter(effect=>effect.effectId!==effectId));}
export function effectStacks(effects:ActiveEffect[],effectId:string){const active=effects.find(effect=>effect.effectId===effectId&&effect.remainingDuration>0&&effect.stackCount>0);return active?.stackCount??0;}
export function hasEffect(effects:ActiveEffect[],effectId:string){return effectStacks(effects,effectId)>0;}
export function validateEffectDefinitions(catalog:Record<string,EffectDefinition>=EFFECTS){const errors:string[]=[];for(const definition of Object.values(catalog)){if(!definition.id)errors.push('effect: missing id');if(!Number.isSafeInteger(definition.defaultDuration)||definition.defaultDuration<1)errors.push(`${definition.id}: invalid duration`);if(definition.behavior==='SHIELD'){const modes=Number(Number.isFinite(definition.shieldAmount)&&Number(definition.shieldAmount)>0)+Number(Number.isFinite(definition.shieldPercent)&&Number(definition.shieldPercent)>0)+Number(Number.isSafeInteger(definition.shieldHits)&&Number(definition.shieldHits)>0);if(modes!==1)errors.push(`${definition.id}: shield requires exactly one amount or hit-count mode`);if(definition.stackingPolicy!=='REPLACE')errors.push(`${definition.id}: shield requires REPLACE policy`);if((definition.scope??'BATTLE')!=='BATTLE')errors.push(`${definition.id}: shield scope must be BATTLE`);if(definition.maxStacks||definition.thresholdReaction)errors.push(`${definition.id}: shield cannot use stack threshold`);}const threshold=definition.thresholdReaction;if(!threshold)continue;if(!Number.isSafeInteger(threshold.threshold)||threshold.threshold<1)errors.push(`${definition.id}: invalid threshold`);if(definition.stackingPolicy!=='STACK')errors.push(`${definition.id}: threshold requires STACK policy`);for(const id of [...(threshold.removeEffectIds??[]),...(threshold.applyEffectIds??[])])if(!catalog[id])errors.push(`${definition.id}: unknown transition effect ${id}`);}return errors;}
export interface DamageAbsorption {incomingDamage:number;absorbedByShield:number;hpDamage:number;shieldBefore:number;shieldAfter:number}
export function activeShield(e:Expedition,actor:EffectActor){return sort(effectsFor(e,actor)).reverse().find(effect=>EFFECTS[effect.effectId]?.behavior==='SHIELD'&&((effect.currentShield??0)>0||(effect.currentShieldHits??0)>0));}
export function shieldTotal(e:Expedition,actor:EffectActor){return effectsFor(e,actor).reduce((sum,x)=>sum+(x.currentShield??0),0);}
export function applyIncomingDamage(e:Expedition,actor:EffectActor,incomingDamage:number):DamageAbsorption {
 const incoming=Math.max(0,incomingDamage),before=shieldTotal(e,actor);let remaining=incoming;
 for(const shield of sort(effectsFor(e,actor))){
  if(EFFECTS[shield.effectId]?.behavior!=='SHIELD'||remaining<=0)continue;
  if(shield.currentShieldHits){const hits=shield.currentShieldHits;shield.currentShieldHits--;if(!shield.currentShieldHits)removeEffectById(e,actor,shield.effectId);return {incomingDamage:incoming,absorbedByShield:incoming,hpDamage:0,shieldBefore:hits,shieldAfter:shield.currentShieldHits};}
  const absorbed=Math.min(shield.currentShield??0,remaining);remaining-=absorbed;shield.currentShield=(shield.currentShield??0)-absorbed;
  if(shield.currentShield<=0)removeEffectById(e,actor,shield.effectId);
 }
 return {incomingDamage:incoming,absorbedByShield:incoming-remaining,hpDamage:remaining,shieldBefore:before,shieldAfter:shieldTotal(e,actor)};
}
export function modifier(e:Expedition,actor:EffectActor,stat:NonNullable<NonNullable<EffectDefinition['payload']>['stat']>){return sort(effectsFor(e,actor)).reduce((value,effect)=>{const d=EFFECTS[effect.effectId];return d?.behavior==='STAT_MODIFIER'&&d.payload?.stat===stat?value+(d.payload.multiplier??0)*effect.stackCount:value;},0);}
export function periodicDelta(e:Expedition,actor:EffectActor,maxHp:number,turn:number){return sort(effectsFor(e,actor)).filter(effect=>effect.createdTurn!==turn).reduce((total,effect)=>{const d=EFFECTS[effect.effectId];if(!d)return total;if(d.behavior==='PERIODIC_DAMAGE')return total-(d.payload?.amount??0)*effect.stackCount;if(d.behavior==='PERIODIC_HEAL')return total+maxHp*(d.payload?.amount??0)*effect.stackCount;return total;},0);}
export function expireTurnEffects(e:Expedition,actor:EffectActor,turn:number){const list=effectsFor(e,actor);for(const effect of list)if(EFFECTS[effect.effectId]?.behavior!=='SHIELD'&&effect.createdTurn!==turn)effect.remainingDuration--;list.splice(0,list.length,...list.filter(effect=>effect.remainingDuration>0));}
export function clearBattleEffects(e:Expedition){e.playerEffects=e.playerEffects.filter(x=>x.scope==='EXPEDITION');e.monsterEffects=e.monsterEffects.filter(x=>x.scope==='EXPEDITION');e.preparedEffects=e.preparedEffects.filter(x=>x.scope==='EXPEDITION');e.reactivePrepared={player:null,monster:null};}


export const isStunned=(e:Expedition,actor:EffectActor)=>effectsFor(e,actor).some(x=>EFFECTS[x.effectId]?.tags.includes('STUN'));
export const isSilenced=(e:Expedition,actor:EffectActor)=>effectsFor(e,actor).some(x=>EFFECTS[x.effectId]?.tags.includes('SILENCE'));
export const isRooted=(e:Expedition,actor:EffectActor)=>effectsFor(e,actor).some(x=>EFFECTS[x.effectId]?.tags.includes('ROOT'));
export interface EffectRemovalOptions {count?:number;tags?:EffectTag[]}
const cleansePriority=(d:EffectDefinition)=>d.tags.includes('STUN')?0:d.tags.includes('SILENCE')?1:d.tags.includes('DOT')?2:d.tags.includes('STAT_DOWN')?3:d.tags.includes('ROOT')?4:5;
function removeEligible(e:Expedition,actor:EffectActor,category:'BUFF'|'DEBUFF',options:EffectRemovalOptions){
 const eligible=sort(effectsFor(e,actor)).filter(x=>{const d=EFFECTS[x.effectId];return d?.category===category&&d.behavior!=='SHIELD'&&(!options.tags||options.tags.some(t=>d.tags.includes(t)));});
 eligible.sort((a,b)=>cleansePriority(EFFECTS[a.effectId])-cleansePriority(EFFECTS[b.effectId])||a.applicationSequence-b.applicationSequence);
 const removed=eligible.slice(0,Math.max(0,options.count??eligible.length));for(const x of removed)removeEffectById(e,actor,x.effectId);
 return removed.map(x=>x.effectId);
}
export const cleanseEffects=(e:Expedition,actor:EffectActor,options:EffectRemovalOptions={})=>removeEligible(e,actor,'DEBUFF',options);
export const dispelEffects=(e:Expedition,actor:EffectActor,options:EffectRemovalOptions={})=>removeEligible(e,actor,'BUFF',options);
