import type {MonsterDefinition} from './monsterAi';

export const KALEON_NORMAL_DEFINITIONS:MonsterDefinition[]=[
 {id:'verdant_penitent',name:'녹흔 순례자',skills:[{id:'penitent_grace',name:'녹빛 회복 기도',description:'오염된 은총으로 상처를 천천히 회복합니다.',cooldown:4,kind:'effect',effects:[{target:'SELF',effectId:'verdant_grace'}]}],aiRules:[{id:'pray',priority:20,actionId:'penitent_grace',conditions:[{kind:'SELF_MISSING_EFFECT',effectId:'verdant_grace'},{kind:'SKILL_READY',skillId:'penitent_grace'}]}]},
 {id:'anointed_censer_bearer',name:'성유 향로지기',skills:[{id:'censer_miasma',name:'성유 독향',description:'타락한 성유 연기로 지속 피해를 남깁니다.',cooldown:3,kind:'effect',effects:[{target:'TARGET',effectId:'green_incense'}]},{id:'censer_swing',name:'향로 휘두르기',description:'무거운 향로를 휘둘러 공격합니다.',cooldown:2,kind:'damage',multiplier:1.15}],aiRules:[{id:'miasma',priority:30,actionId:'censer_miasma',conditions:[{kind:'TARGET_MISSING_EFFECT',effectId:'green_incense'},{kind:'SKILL_READY',skillId:'censer_miasma'}]},{id:'swing',priority:10,actionId:'censer_swing',conditions:[{kind:'SKILL_READY',skillId:'censer_swing'}]}]},
 {id:'vicarious_armor_monk',name:'대속 갑주수도사',skills:[{id:'vicarious_guard',name:'대속 갑주',description:'겹겹이 쌓인 대속의 흔적으로 방어를 굳힙니다.',cooldown:4,kind:'effect',effects:[{target:'SELF',effectId:'atonement_guard'}]},{id:'burden_slam',name:'대속 강타',description:'누적된 고통의 무게로 내려칩니다.',cooldown:2,kind:'damage',multiplier:1.25}],aiRules:[{id:'guard',priority:30,actionId:'vicarious_guard',conditions:[{kind:'SELF_MISSING_EFFECT',effectId:'atonement_guard'},{kind:'SKILL_READY',skillId:'vicarious_guard'}]},{id:'slam',priority:10,actionId:'burden_slam',conditions:[{kind:'SKILL_READY',skillId:'burden_slam'}]}]},
 {id:'confession_binder',name:'고해 속박자',skills:[{id:'confession_sentence',name:'고해의 속박',description:'죄를 선고해 공격 의지를 꺾습니다.',cooldown:3,kind:'effect',effects:[{target:'TARGET',effectId:'confession_burden'}]},{id:'binding_lash',name:'속죄 채찍',description:'속박된 대상에게 무거운 일격을 가합니다.',cooldown:2,kind:'damage',multiplier:1.3}],aiRules:[{id:'bind',priority:30,actionId:'confession_sentence',conditions:[{kind:'TARGET_MISSING_EFFECT',effectId:'confession_burden'},{kind:'SKILL_READY',skillId:'confession_sentence'}]},{id:'lash',priority:20,actionId:'binding_lash',conditions:[{kind:'TARGET_HAS_EFFECT',effectId:'confession_burden'},{kind:'SKILL_READY',skillId:'binding_lash'}]}]},
 {id:'stigmata_reaper',name:'성흔 수확자',skills:[{id:'stigmata_cut',name:'성흔 절개',description:'상처를 벌려 이후 받는 피해를 증가시킵니다.',cooldown:3,kind:'damage',multiplier:1.05,effects:[{target:'TARGET',effectId:'stigmata_wound'}]},{id:'stigmata_harvest',name:'성흔 수확',description:'쇠약해진 상처를 노려 치명적인 수확을 시도합니다.',cooldown:2,kind:'damage',multiplier:1.75}],aiRules:[{id:'harvest',priority:40,actionId:'stigmata_harvest',conditions:[{kind:'TARGET_HP_BELOW',value:.45},{kind:'TARGET_HAS_EFFECT',effectId:'stigmata_wound'},{kind:'SKILL_READY',skillId:'stigmata_harvest'}]},{id:'cut',priority:30,actionId:'stigmata_cut',conditions:[{kind:'TARGET_MISSING_EFFECT',effectId:'stigmata_wound'},{kind:'SKILL_READY',skillId:'stigmata_cut'}]}]}
];

export const KALEON_BOSS_DEFINITIONS:MonsterDefinition[]=[
 {id:'stigmata_healer',name:'성흔을 품은 치유사',skills:[{id:'stigmata_ministration',name:'녹빛 치유',description:'녹빛 은총으로 자신의 상처를 되돌립니다.',cooldown:4,kind:'effect',effects:[{target:'SELF',effectId:'verdant_grace'}]},{id:'pain_transference',name:'성흔 이전',description:'자신의 고통을 상대에게 옮기고 회복의 흐름을 유지합니다.',cooldown:3,kind:'effect',effects:[{target:'TARGET',effectId:'transferred_pain'},{target:'SELF',effectId:'verdant_grace'}]},{id:'healer_lance',name:'대속의 가시',description:'옮겨진 고통 위에 성흔을 새깁니다.',cooldown:2,kind:'damage',multiplier:1.35,effects:[{target:'TARGET',effectId:'stigmata_wound'}]}],aiRules:[{id:'heal',priority:50,actionId:'stigmata_ministration',conditions:[{kind:'SELF_HP_BELOW',value:.65},{kind:'SELF_MISSING_EFFECT',effectId:'verdant_grace'},{kind:'SKILL_READY',skillId:'stigmata_ministration'}]},{id:'transfer',priority:40,actionId:'pain_transference',conditions:[{kind:'TARGET_MISSING_EFFECT',effectId:'transferred_pain'},{kind:'SKILL_READY',skillId:'pain_transference'}]},{id:'lance',priority:20,actionId:'healer_lance',conditions:[{kind:'TARGET_HAS_EFFECT',effectId:'transferred_pain'},{kind:'SKILL_READY',skillId:'healer_lance'}]}]},
 {id:'atonement_cross_bearer',name:'대속 십자가 운반자',skills:[{id:'cross_barrier',name:'대속의 장막',description:'십자가형 장막으로 피해를 대신 받아냅니다.',cooldown:4,kind:'effect',effects:[{target:'SELF',effectId:'atonement_shield'}]},{id:'atonement_brand',name:'대속 각인',description:'상대에게 희생 대상으로 지정되는 대속의 인장을 남깁니다.',cooldown:3,kind:'effect',effects:[{target:'TARGET',effectId:'atonement_mark'}]},{id:'cross_crush',name:'십자가 압착',description:'대속의 인장이 새겨진 대상을 향해 거대한 십자가를 내리꽂습니다.',cooldown:3,kind:'charge',multiplier:2.2}],aiRules:[{id:'barrier',priority:60,actionId:'cross_barrier',conditions:[{kind:'SELF_MISSING_EFFECT',effectId:'atonement_shield'},{kind:'SKILL_READY',skillId:'cross_barrier'}]},{id:'brand',priority:50,actionId:'atonement_brand',conditions:[{kind:'TARGET_MISSING_EFFECT',effectId:'atonement_mark'},{kind:'SKILL_READY',skillId:'atonement_brand'}]},{id:'crush',priority:40,actionId:'cross_crush',conditions:[{kind:'TARGET_HAS_EFFECT',effectId:'atonement_mark'},{kind:'SKILL_READY',skillId:'cross_crush'}]}]},
 {id:'sacrament_executioner',name:'희생의 집전관',skills:[{id:'sacrifice_sentence',name:'희생 선고',description:'대상을 제물로 지목하며 희생 표식을 누적합니다.',cooldown:1,kind:'effect',effects:[{target:'TARGET',effectId:'sacrifice_mark'}]},{id:'sacrament_execution',name:'집전 처형',description:'희생 표식이 완성된 대상을 의식의 제물로 집행합니다.',cooldown:3,kind:'charge',multiplier:2.45}],aiRules:[{id:'execute',priority:60,actionId:'sacrament_execution',conditions:[{kind:'TARGET_EFFECT_STACKS_AT_LEAST',effectId:'sacrifice_mark',requiredStacks:3},{kind:'SKILL_READY',skillId:'sacrament_execution'}]},{id:'sentence',priority:40,actionId:'sacrifice_sentence',conditions:[{kind:'SKILL_READY',skillId:'sacrifice_sentence'}]}]},
 {id:'false_salvation_apostle',name:'거짓 구원의 사도',skills:[{id:'false_grace',name:'거짓 은총',description:'구원의 형상을 흉내 낸 보호막을 펼칩니다.',cooldown:4,kind:'effect',effects:[{target:'SELF',effectId:'false_grace_shield'}]},{id:'inverted_absolution',name:'뒤집힌 사죄',description:'용서 대신 죄책과 상처를 상대에게 되돌립니다.',cooldown:4,kind:'effect',effects:[{target:'TARGET',effectId:'confession_burden'},{target:'TARGET',effectId:'stigmata_wound'}]},{id:'apostle_counter_stance',name:'거짓 계시',description:'직접 공격을 받으면 즉시 응보할 준비를 합니다.',cooldown:3,kind:'reactive_prepare',reactiveTrigger:'DIRECT_HIT_RECEIVED',reactionSkillId:'apostle_counter'},{id:'apostle_counter',name:'사도의 응보',description:'준비된 거짓 계시로 즉시 반격합니다.',cooldown:0,kind:'damage',multiplier:1},{id:'apostle_judgment',name:'구원의 심판',description:'죄책에 짓눌린 대상에게 강한 심판을 내립니다.',cooldown:2,kind:'damage',multiplier:1.55}],aiRules:[{id:'grace',priority:70,actionId:'false_grace',conditions:[{kind:'SELF_MISSING_EFFECT',effectId:'false_grace_shield'},{kind:'SKILL_READY',skillId:'false_grace'}]},{id:'absolution',priority:60,actionId:'inverted_absolution',conditions:[{kind:'TARGET_MISSING_EFFECT',effectId:'confession_burden'},{kind:'SKILL_READY',skillId:'inverted_absolution'}]},{id:'counter',priority:50,actionId:'apostle_counter_stance',conditions:[{kind:'SKILL_READY',skillId:'apostle_counter_stance'}]},{id:'judgment',priority:30,actionId:'apostle_judgment',conditions:[{kind:'TARGET_HAS_EFFECT',effectId:'confession_burden'},{kind:'SKILL_READY',skillId:'apostle_judgment'}]}]},
 {id:'false_saint_caleon',name:'거짓 성자 칼레온',skills:[{id:'kaleon_false_salvation',name:'거짓 구원의 장막',description:'자신을 구원의 중심으로 삼아 거대한 녹빛 보호막을 펼칩니다.',cooldown:5,kind:'effect',effects:[{target:'SELF',effectId:'kaleon_shield'}]},{id:'kaleon_green_grace',name:'녹빛 은총',description:'흡수한 생명력으로 자신의 육체를 재생합니다.',cooldown:4,kind:'effect',effects:[{target:'SELF',effectId:'kaleon_grace'}]},{id:'kaleon_benediction',name:'뒤집힌 축복',description:'축복의 이름으로 죄책과 성흔을 상대에게 새깁니다.',cooldown:4,kind:'effect',effects:[{target:'TARGET',effectId:'confession_burden'},{target:'TARGET',effectId:'stigmata_wound'}]},{id:'kaleon_transfer',name:'고통 전가',description:'고통의 몫을 상대에게 떠넘기며 대속의 부채를 누적합니다.',cooldown:1,kind:'effect',effects:[{target:'TARGET',effectId:'atonement_debt'},{target:'TARGET',effectId:'transferred_pain'}]},{id:'kaleon_execution',name:'대속 집행',description:'누적된 대속의 부채를 근거로 희생을 강제합니다.',cooldown:3,kind:'charge',multiplier:2.65},{id:'kaleon_last_gospel',name:'마지막 복음',description:'자신의 생존을 구원이라 선언하며 모든 힘을 쏟아붓습니다.',cooldown:5,kind:'charge',multiplier:3.15}],aiRules:[{id:'last-gospel',priority:100,actionId:'kaleon_last_gospel',conditions:[{kind:'SELF_HP_BELOW',value:.3},{kind:'SKILL_READY',skillId:'kaleon_last_gospel'}]},{id:'salvation',priority:90,actionId:'kaleon_false_salvation',conditions:[{kind:'SELF_MISSING_EFFECT',effectId:'kaleon_shield'},{kind:'SKILL_READY',skillId:'kaleon_false_salvation'}]},{id:'green-grace',priority:80,actionId:'kaleon_green_grace',conditions:[{kind:'SELF_HP_BELOW',value:.75},{kind:'SELF_MISSING_EFFECT',effectId:'kaleon_grace'},{kind:'SKILL_READY',skillId:'kaleon_green_grace'}]},{id:'benediction',priority:70,actionId:'kaleon_benediction',conditions:[{kind:'TARGET_MISSING_EFFECT',effectId:'confession_burden'},{kind:'SKILL_READY',skillId:'kaleon_benediction'}]},{id:'execution',priority:60,actionId:'kaleon_execution',conditions:[{kind:'TARGET_EFFECT_STACKS_AT_LEAST',effectId:'atonement_debt',requiredStacks:3},{kind:'SKILL_READY',skillId:'kaleon_execution'}]},{id:'transfer',priority:50,actionId:'kaleon_transfer',conditions:[{kind:'SKILL_READY',skillId:'kaleon_transfer'}]}]}
];

export const KALEON_MONSTER_DEFINITIONS:MonsterDefinition[]=[...KALEON_NORMAL_DEFINITIONS,...KALEON_BOSS_DEFINITIONS];
