import type {MonsterDefinition} from './monsterAi';

export const LEATHER_BOSS_DEFINITIONS:MonsterDefinition[]=[
  {id:'blood_maned_tracker',name:'핏갈기 추적자',skills:[{id:'tracker_scent',name:'핏빛 추적',description:'상대의 약점을 꿰뚫어 보며 치명타율을 높입니다.',cooldown:3,kind:'effect',effects:[{target:'SELF',effectId:'blood_scent'}]},{id:'tracker_charge',name:'추적자의 돌진',description:'추적한 대상을 향해 맹렬히 돌진합니다.',cooldown:3,kind:'charge',multiplier:2.1}],aiRules:[{id:'scent',priority:50,actionId:'tracker_scent',conditions:[{kind:'SELF_MISSING_EFFECT',effectId:'blood_scent'},{kind:'SKILL_READY',skillId:'tracker_scent'}]},{id:'charge',priority:40,actionId:'tracker_charge',conditions:[{kind:'TARGET_HAS_EFFECT',effectId:'blood_scent'},{kind:'SKILL_READY',skillId:'tracker_charge'}]}]},
  {id:'red_jawed_predator',name:'붉은턱 가죽포식자',skills:[{id:'predator_maul',name:'포식자의 송곳니',description:'깊은 상처를 남겨 지속적인 출혈을 유발합니다.',cooldown:2,kind:'damage',multiplier:1.15,effects:[{target:'TARGET',effectId:'predator_wound'}]},{id:'predator_feast',name:'상처 뜯어먹기',description:'상처 입은 대상을 노려 치명적인 피해를 줍니다.',cooldown:2,kind:'damage',multiplier:1.7}],aiRules:[{id:'maul',priority:40,actionId:'predator_maul',conditions:[{kind:'TARGET_MISSING_EFFECT',effectId:'predator_wound'},{kind:'SKILL_READY',skillId:'predator_maul'}]},{id:'feast',priority:30,actionId:'predator_feast',conditions:[{kind:'TARGET_HAS_EFFECT',effectId:'predator_wound'},{kind:'SKILL_READY',skillId:'predator_feast'}]}]},
  {id:'fang_pack_mother',name:'송곳니 무리어미',skills:[{id:'mother_call',name:'무리 소집',description:'자식을 불러내 방어 태세를 갖춥니다.',cooldown:4,kind:'effect',effects:[{target:'SELF',effectId:'pack_defense'}]},{id:'mother_protect',name:'어미의 가호',description:'직접 공격을 받으면 즉시 반격할 준비를 합니다.',cooldown:3,kind:'reactive_prepare',reactiveTrigger:'DIRECT_HIT_RECEIVED',reactionSkillId:'mother_counter'},{id:'mother_counter',name:'어미의 반격',description:'준비된 반격으로 공격자를 물어뜯습니다.',cooldown:0,kind:'damage',multiplier:1.3}],aiRules:[{id:'call',priority:60,actionId:'mother_call',conditions:[{kind:'SELF_MISSING_EFFECT',effectId:'pack_defense'},{kind:'SKILL_READY',skillId:'mother_call'}]},{id:'protect',priority:50,actionId:'mother_protect',conditions:[{kind:'SKILL_READY',skillId:'mother_protect'}]}]},
  {id:'sanctuary_claw_bishop',name:'성소 발톱주교',skills:[{id:'bishop_ritual',name:'성소의 의식',description:'고대 의식으로 강력한 보호막을 두릅니다.',cooldown:4,kind:'effect',effects:[{target:'SELF',effectId:'sanctuary_shield'}]},{id:'bishop_judgment',name:'주교의 심판',description:'죄 많은 자에게 성소의 벌을 내립니다.',cooldown:3,kind:'effect',effects:[{target:'TARGET',effectId:'ritual_brand'},{target:'TARGET',effectId:'weaken'}]},{id:'bishop_smite',name:'성스러운 강타',description:'낙인 찍힌 대상에게 강력한 일격을 가합니다.',cooldown:2,kind:'damage',multiplier:1.55}],aiRules:[{id:'ritual',priority:70,actionId:'bishop_ritual',conditions:[{kind:'SELF_MISSING_EFFECT',effectId:'sanctuary_shield'},{kind:'SKILL_READY',skillId:'bishop_ritual'}]},{id:'judgment',priority:60,actionId:'bishop_judgment',conditions:[{kind:'TARGET_MISSING_EFFECT',effectId:'ritual_brand'},{kind:'SKILL_READY',skillId:'bishop_judgment'}]},{id:'smite',priority:40,actionId:'bishop_smite',conditions:[{kind:'TARGET_HAS_EFFECT',effectId:'ritual_brand'},{kind:'SKILL_READY',skillId:'bishop_smite'}]}]},
  {id:'lord_of_red_fangs',name:'적아의 주인',skills:[{id:'lord_dominance',name:'적아의 위압',description:'절대적인 포식자로서 전장에 위압감을 펼칩니다.',cooldown:5,kind:'effect',effects:[{target:'SELF',effectId:'lord_shield'}]},{id:'lord_crimson_debt',name:'진홍의 부채',description:'대상에게 진홍의 표식을 새겨 부채를 누적시킵니다.',cooldown:1,kind:'effect',effects:[{target:'TARGET',effectId:'crimson_debt'}]},{id:'lord_blood_harvest',name:'피의 수확',description:'진홍의 부채가 쌓인 대상을 처단합니다.',cooldown:3,kind:'charge',multiplier:2.5},{id:'lord_primal_roar',name:'원초의 포효',description:'체력이 낮아지면 모든 힘을 개방합니다.',cooldown:5,kind:'charge',multiplier:3.2}],aiRules:[{id:'roar',priority:100,actionId:'lord_primal_roar',conditions:[{kind:'SELF_HP_BELOW',value:.3},{kind:'SKILL_READY',skillId:'lord_primal_roar'}]},{id:'dominance',priority:90,actionId:'lord_dominance',conditions:[{kind:'SELF_MISSING_EFFECT',effectId:'lord_shield'},{kind:'SKILL_READY',skillId:'lord_dominance'}]},{id:'debt',priority:70,actionId:'lord_crimson_debt',conditions:[{kind:'TARGET_MISSING_EFFECT',effectId:'crimson_debt'},{kind:'SKILL_READY',skillId:'lord_crimson_debt'}]},{id:'harvest',priority:60,actionId:'lord_blood_harvest',conditions:[{kind:'TARGET_EFFECT_STACKS_AT_LEAST',effectId:'crimson_debt',requiredStacks:3},{kind:'SKILL_READY',skillId:'lord_blood_harvest'}]}]}
];

export const LEATHER_MONSTER_DEFINITIONS:MonsterDefinition[]=[...LEATHER_BOSS_DEFINITIONS];