import type {ActiveEffect,Monster,MonsterBattleRuntime} from '../types';
import {EFFECTS,effectStacks,hasEffect} from './effects';

export type MonsterActionKind='BASIC_ATTACK'|'ACTIVE_SKILL'|'PREPARED_DISCHARGE';
export type AiCondition=
 |{kind:'SELF_HP_BELOW';value:number}
 |{kind:'TARGET_HP_BELOW';value:number}
 |{kind:'SKILL_READY';skillId:string}
 |{kind:'SELF_HAS_EFFECT'|'SELF_MISSING_EFFECT'|'TARGET_HAS_EFFECT'|'TARGET_MISSING_EFFECT';effectId:string}
 |{kind:'SELF_EFFECT_STACKS_AT_LEAST'|'TARGET_EFFECT_STACKS_AT_LEAST';effectId:string;requiredStacks:number};
export interface MonsterSkillEffect {target:'TARGET'|'SELF';effectId:string}
export interface MonsterSkillDefinition {id:string;name:string;description:string;cooldown:number;kind:'damage'|'charge'|'reactive_prepare'|'effect';hits?:number;multiplier?:number;effects?:MonsterSkillEffect[];reactiveTrigger?:'DIRECT_HIT_RECEIVED';reactionSkillId?:string}
export interface MonsterAiRule {id:string;priority:number;actionId:string;conditions:AiCondition[]}
export interface MonsterDefinition {id:string;name:string;skills?:MonsterSkillDefinition[];passives?:string[];aiRules?:MonsterAiRule[]}
export interface MonsterActionDecision {kind:MonsterActionKind;skill?:MonsterSkillDefinition}

export const TEST_MONSTER_BASIC:MonsterDefinition={id:'test-basic-ai',name:'AI 훈련체',skills:[{id:'crush',name:'분쇄',description:'강한 단일 공격',cooldown:2,kind:'damage',multiplier:1.5}],aiRules:[{id:'low-crush',priority:10,actionId:'crush',conditions:[{kind:'SELF_HP_BELOW',value:.6},{kind:'SKILL_READY',skillId:'crush'}]}]};
export const TEST_MONSTER_CHARGE:MonsterDefinition={id:'test-charge',name:'충전 훈련체',skills:[{id:'charge',name:'암반 돌진',description:'한 턴 준비 후 돌진',cooldown:2,kind:'charge',multiplier:2}],aiRules:[{id:'charge-first',priority:100,actionId:'charge',conditions:[{kind:'SKILL_READY',skillId:'charge'}]}]};
export const TEST_MONSTER_MULTI:MonsterDefinition={id:'test-multi',name:'연타 훈련체',skills:[{id:'triple',name:'삼연격',description:'세 번 공격',cooldown:1,kind:'damage',hits:3,multiplier:.65}],aiRules:[{id:'triple-first',priority:10,actionId:'triple',conditions:[]}]};
export const TEST_MONSTER_EFFECT:MonsterDefinition={id:'test-effect',name:'효과 훈련체',skills:[{id:'venom',name:'독성 분진',description:'대상에게 중독',cooldown:2,kind:'effect',effects:[{target:'TARGET',effectId:'poison'}]},{id:'fortify',name:'강철 경화',description:'자신의 방어 증가',cooldown:3,kind:'effect',effects:[{target:'SELF',effectId:'defense_up'}]}],aiRules:[{id:'venom-first',priority:20,actionId:'venom',conditions:[{kind:'TARGET_HP_BELOW',value:1.01},{kind:'SKILL_READY',skillId:'venom'}]},{id:'fortify-second',priority:10,actionId:'fortify',conditions:[{kind:'SKILL_READY',skillId:'fortify'}]}]};
export const TEST_MONSTER_REACTIVE:MonsterDefinition={id:'test-reactive',name:'반격 훈련체',skills:[{id:'counter_stance',name:'TEST_COUNTER 준비',description:'직접 피격에 반응할 준비',cooldown:3,kind:'reactive_prepare',reactiveTrigger:'DIRECT_HIT_RECEIVED',reactionSkillId:'counter'},{id:'counter',name:'TEST_COUNTER',description:'즉시 반격',cooldown:0,kind:'damage',multiplier:.8}],aiRules:[{id:'prepare-counter',priority:100,actionId:'counter_stance',conditions:[{kind:'SKILL_READY',skillId:'counter_stance'}]}]};
export const TEST_MONSTER_STATUS:MonsterDefinition={id:'test-status-ai',name:'상태 AI 훈련체',skills:[{id:'test_burst',name:'TEST_BURST',description:'3중첩 대응',cooldown:2,kind:'damage',multiplier:1.5},{id:'test_pressure',name:'TEST_PRESSURE',description:'상태 대응',cooldown:1,kind:'damage',multiplier:1.1}],aiRules:[{id:'burst',priority:20,actionId:'test_burst',conditions:[{kind:'TARGET_EFFECT_STACKS_AT_LEAST',effectId:'test_resonance',requiredStacks:3},{kind:'SKILL_READY',skillId:'test_burst'}]},{id:'pressure',priority:10,actionId:'test_pressure',conditions:[{kind:'TARGET_HAS_EFFECT',effectId:'test_resonance'}]}]};
export const TEST_MONSTER_SELF_STATUS:MonsterDefinition={id:'test-self-status-ai',name:'자기 상태 AI 훈련체',skills:[{id:'restore_armor',name:'TEST_RESTORE_ARMOR',description:'방어 상태 복구',cooldown:1,kind:'effect',effects:[{target:'SELF',effectId:'test_armor'}]},{id:'armored_strike',name:'TEST_ARMORED_STRIKE',description:'방어 상태 공격',cooldown:1,kind:'damage'}],aiRules:[{id:'restore',priority:20,actionId:'restore_armor',conditions:[{kind:'SELF_MISSING_EFFECT',effectId:'test_armor'}]},{id:'strike',priority:10,actionId:'armored_strike',conditions:[{kind:'SELF_HAS_EFFECT',effectId:'test_armor'}]}]};
export const TEST_MONSTER_PREPARED_COMBINED:MonsterDefinition={id:'test-prepared-combined',name:'복합 준비 훈련체',skills:[{id:'qa_charge',name:'TEST_CHARGE_LONG_NAME',description:'Charge UI 검증',cooldown:2,kind:'charge',multiplier:1.2},{id:'qa_counter_stance',name:'TEST_REACTIVE_COUNTER_LONG_NAME',description:'Reactive UI 검증',cooldown:3,kind:'reactive_prepare',reactiveTrigger:'DIRECT_HIT_RECEIVED',reactionSkillId:'qa_counter'},{id:'qa_counter',name:'TEST_COUNTER',description:'반격',cooldown:0,kind:'damage',multiplier:.5}],aiRules:[]};
export const TEST_MONSTER_SHIELD:MonsterDefinition={id:'test-shield-monster',name:'보호막 훈련체',skills:[{id:'shield_stance',name:'TEST_SHIELD 전개',description:'자신에게 보호막 적용',cooldown:3,kind:'effect',effects:[{target:'SELF',effectId:'test_shield'}]},{id:'shield_multi',name:'TEST_SHIELD 삼연격',description:'세 번 공격',cooldown:1,kind:'damage',hits:3,multiplier:.4}],aiRules:[{id:'shield-first',priority:20,actionId:'shield_stance',conditions:[{kind:'SELF_MISSING_EFFECT',effectId:'test_shield'},{kind:'SKILL_READY',skillId:'shield_stance'}]},{id:'multi-second',priority:10,actionId:'shield_multi',conditions:[{kind:'SKILL_READY',skillId:'shield_multi'}]}]};
export const DEV_MONSTER_DEFINITIONS=[TEST_MONSTER_BASIC,TEST_MONSTER_CHARGE,TEST_MONSTER_MULTI,TEST_MONSTER_EFFECT,TEST_MONSTER_REACTIVE,TEST_MONSTER_STATUS,TEST_MONSTER_SELF_STATUS,TEST_MONSTER_PREPARED_COMBINED,TEST_MONSTER_SHIELD] as const;
const DEFINITIONS=new Map<string,MonsterDefinition>(DEV_MONSTER_DEFINITIONS.map(definition=>[definition.id,definition]));

export const monsterDefinitionById=(id:string)=>DEFINITIONS.get(id);
export const monsterDefinitionFor=(monster:Monster):MonsterDefinition=>monsterDefinitionById(monster.definitionId??'')??{id:monster.definitionId??monster.name,name:monster.name,skills:[],passives:[],aiRules:[]};
export const createMonsterRuntime=(monster:Monster,turnNumber=0):MonsterBattleRuntime=>({definitionId:monsterDefinitionFor(monster).id,skillCooldowns:{},preparedActionId:null,turnNumber});
export const definitionForRuntime=(monster:Monster,runtime:MonsterBattleRuntime)=>monsterDefinitionById(runtime.definitionId)??monsterDefinitionFor(monster);
const ready=(runtime:MonsterBattleRuntime,skill:MonsterSkillDefinition)=>(runtime.skillCooldowns[skill.id]??0)===0;
function condition(item:AiCondition,monster:Monster,targetHp:number,targetMaxHp:number,runtime:MonsterBattleRuntime,skills:MonsterSkillDefinition[],selfEffects:ActiveEffect[],targetEffects:ActiveEffect[]){if('effectId' in item&&!EFFECTS[item.effectId])return false;if(item.kind==='SELF_HP_BELOW')return monster.currentHp/monster.hp<item.value;if(item.kind==='TARGET_HP_BELOW')return targetHp/targetMaxHp<item.value;if(item.kind==='SKILL_READY'){const skill=skills.find(candidate=>candidate.id===item.skillId);return !!skill&&ready(runtime,skill);}if(item.kind==='SELF_HAS_EFFECT')return hasEffect(selfEffects,item.effectId);if(item.kind==='SELF_MISSING_EFFECT')return !hasEffect(selfEffects,item.effectId);if(item.kind==='TARGET_HAS_EFFECT')return hasEffect(targetEffects,item.effectId);if(item.kind==='TARGET_MISSING_EFFECT')return !hasEffect(targetEffects,item.effectId);if(item.kind==='SELF_EFFECT_STACKS_AT_LEAST'||item.kind==='TARGET_EFFECT_STACKS_AT_LEAST'){if(!Number.isSafeInteger(item.requiredStacks)||item.requiredStacks<1)return false;return effectStacks(item.kind==='SELF_EFFECT_STACKS_AT_LEAST'?selfEffects:targetEffects,item.effectId)>=item.requiredStacks;}return false;}
export function chooseMonsterAction(definition:MonsterDefinition,runtime:MonsterBattleRuntime,monster:Monster,targetHp:number,targetMaxHp:number,selfEffects:ActiveEffect[]=[],targetEffects:ActiveEffect[]=[]):MonsterActionDecision {const skills=definition.skills??[];if(runtime.preparedActionId){const skill=skills.find(candidate=>candidate.id===runtime.preparedActionId);if(skill?.kind==='charge')return {kind:'PREPARED_DISCHARGE',skill};}for(const rule of [...(definition.aiRules??[])].sort((a,b)=>b.priority-a.priority||a.id.localeCompare(b.id))){const skill=skills.find(candidate=>candidate.id===rule.actionId);if(skill&&ready(runtime,skill)&&rule.conditions.every(item=>condition(item,monster,targetHp,targetMaxHp,runtime,skills,selfEffects,targetEffects)))return {kind:'ACTIVE_SKILL',skill};}return {kind:'BASIC_ATTACK'};}
export function beginMonsterTurn(runtime:MonsterBattleRuntime){runtime.turnNumber++;for(const id of Object.keys(runtime.skillCooldowns))runtime.skillCooldowns[id]=Math.max(0,runtime.skillCooldowns[id]-1);}
export function useMonsterAction(runtime:MonsterBattleRuntime,decision:MonsterActionDecision){if(decision.kind==='ACTIVE_SKILL'&&decision.skill?.kind==='charge'){runtime.preparedActionId=decision.skill.id;return;}if(decision.kind==='PREPARED_DISCHARGE')runtime.preparedActionId=null;if(decision.skill)runtime.skillCooldowns[decision.skill.id]=Math.max(0,Math.floor(decision.skill.cooldown));}
export const preparedMonsterSkill=(monster:Monster,runtime:MonsterBattleRuntime|null)=>runtime?.preparedActionId?definitionForRuntime(monster,runtime).skills?.find(skill=>skill.id===runtime.preparedActionId):undefined;
export function validateMonsterDefinition(definition:MonsterDefinition){const errors:string[]=[],skills=definition.skills??[],ids=new Set(skills.map(skill=>skill.id));for(const skill of skills){if(skill.kind==='reactive_prepare'){const reaction=skills.find(candidate=>candidate.id===skill.reactionSkillId);if(skill.reactiveTrigger!=='DIRECT_HIT_RECEIVED')errors.push(`${skill.id}: invalid reactive trigger`);if(!reaction)errors.push(`${skill.id}: missing reaction skill`);else if(['reactive_prepare','charge'].includes(reaction.kind))errors.push(`${skill.id}: invalid reaction skill kind`);}for(const effect of skill.effects??[])if(!EFFECTS[effect.effectId])errors.push(`${skill.id}: unknown effect ${effect.effectId}`);}for(const rule of definition.aiRules??[]){if(!ids.has(rule.actionId))errors.push(`${rule.id}: missing action`);for(const item of rule.conditions){if('effectId' in item&&!EFFECTS[item.effectId])errors.push(`${rule.id}: unknown effect ${item.effectId}`);if('requiredStacks' in item&&(!Number.isSafeInteger(item.requiredStacks)||item.requiredStacks<1))errors.push(`${rule.id}: invalid stack threshold`);if(item.kind==='SKILL_READY'&&!ids.has(item.skillId))errors.push(`${rule.id}: missing ready skill`);}}return errors;}

