import type {ActiveEffect,Monster,MonsterBattleRuntime} from '../types';
import {EFFECTS,effectStacks,hasEffect} from './effects';
import {CRYSTAL_MONSTER_DEFINITIONS} from '../data/crystalCombat';

export type MonsterActionKind='BASIC_ATTACK'|'ACTIVE_SKILL'|'PREPARED_DISCHARGE';
export type AiCondition=
 |{kind:'SELF_HP_BELOW';value:number}
 |{kind:'TARGET_HP_BELOW';value:number}
 |{kind:'SKILL_READY';skillId:string}
 |{kind:'SELF_HAS_EFFECT'|'SELF_MISSING_EFFECT'|'TARGET_HAS_EFFECT'|'TARGET_MISSING_EFFECT';effectId:string}
 |{kind:'SELF_EFFECT_STACKS_AT_LEAST'|'TARGET_EFFECT_STACKS_AT_LEAST';effectId:string;requiredStacks:number};
export interface MonsterSkillEffect {target:'TARGET'|'SELF';effectId:string}
export interface MonsterSkillDefinition {id:string;name:string;description:string;cooldown:number;kind:'damage'|'charge'|'reactive_prepare'|'effect';hits?:number;multiplier?:number;effects?:MonsterSkillEffect[];reactiveTrigger?:'DIRECT_HIT_RECEIVED';reactionSkillId?:string}
export interface MonsterAiRule {id:string;priority:number;actionId:string;conditions:AiCondition[]}
export interface MonsterDefinition {id:string;name:string;skills?:MonsterSkillDefinition[];passives?:string[];aiRules?:MonsterAiRule[]}
export interface MonsterActionDecision {kind:MonsterActionKind;skill?:MonsterSkillDefinition}

export const TEST_MONSTER_BASIC:MonsterDefinition={id:'test-basic-ai',name:'AI 훈련체',skills:[{id:'crush',name:'분쇄',description:'강한 단일 공격',cooldown:2,kind:'damage',multiplier:1.5}],aiRules:[{id:'low-crush',priority:10,actionId:'crush',conditions:[{kind:'SELF_HP_BELOW',value:.6},{kind:'SKILL_READY',skillId:'crush'}]}]};
export const TEST_MONSTER_CHARGE:MonsterDefinition={id:'test-charge',name:'충전 훈련체',skills:[{id:'charge',name:'암반 돌진',description:'한 턴 준비 후 돌진',cooldown:2,kind:'charge',multiplier:2}],aiRules:[{id:'charge-first',priority:100,actionId:'charge',conditions:[{kind:'SKILL_READY',skillId:'charge'}]}]};
export const TEST_MONSTER_MULTI:MonsterDefinition={id:'test-multi',name:'연타 훈련체',skills:[{id:'triple',name:'삼연격',description:'세 번 공격',cooldown:1,kind:'damage',hits:3,multiplier:.65}],aiRules:[{id:'triple-first',priority:10,actionId:'triple',conditions:[]}]};
export const TEST_MONSTER_EFFECT:MonsterDefinition={id:'test-effect',name:'효과 훈련체',skills:[{id:'venom',name:'독성 분진',description:'대상에게 중독',cooldown:2,kind:'effect',effects:[{target:'TARGET',effectId:'poison'}]},{id:'fortify',name:'강철 경화',description:'자신의 방어 증가',cooldown:3,kind:'effect',effects:[{target:'SELF',effectId:'defense_up'}]}],aiRules:[{id:'venom-first',priority:20,actionId:'venom',conditions:[{kind:'TARGET_HP_BELOW',value:1.01},{kind:'SKILL_READY',skillId:'venom'}]},{id:'fortify-second',priority:10,actionId:'fortify',conditions:[{kind:'SKILL_READY',skillId:'fortify'}]}]};
export const TEST_MONSTER_REACTIVE:MonsterDefinition={id:'test-reactive',name:'반격 훈련체',skills:[{id:'counter_stance',name:'TEST_COUNTER 준비',description:'직접 피격에 반응할 준비',cooldown:3,kind:'reactive_prepare',reactiveTrigger:'DIRECT_HIT_RECEIVED',reactionSkillId:'counter'},{id:'counter',name:'TEST_COUNTER',description:'즉시 반격',cooldown:0,kind:'damage',multiplier:.8}],aiRules:[{id:'prepare-counter',priority:100,actionId:'counter_stance',conditions:[{kind:'SKILL_READY',skillId:'counter_stance'}]}]};
export const TEST_MONSTER_STATUS:MonsterDefinition={id:'test-status-ai',name:'상태 AI 훈련체',skills:[{id:'test_burst',name:'TEST_BURST',description:'3중첩 대응',cooldown:2,kind:'damage',multiplier:1.5},{id:'test_pressure',name:'TEST_PRESSURE',description:'상태 대응',cooldown:1,kind:'damage',multiplier:1.1}],aiRules:[{id:'burst',priority:20,actionId:'test_burst',conditions:[{kind:'TARGET_EFFECT_STACKS_AT_LEAST',effectId:'test_resonance',requiredStacks:3},{kind:'SKILL_READY',skillId:'test_burst'}]},{id:'pressure',priority:10,actionId:'test_pressure',conditions:[{kind:'TARGET_HAS_EFFECT',effectId:'test_resonance'}]}]};
export const TEST_MONSTER_SELF_STATUS:MonsterDefinition={id:'test-self-status-ai',name:'자기 상태 AI 훈련체',skills:[{id:'restore_armor',name:'TEST_RESTORE_ARMOR',description:'방어 상태 복구',cooldown:1,kind:'effect',effects:[{target:'SELF',effectId:'test_armor'}]},{id:'armored_strike',name:'TEST_ARMORED_STRIKE',description:'방어 상태 공격',cooldown:1,kind:'damage'}],aiRules:[{id:'restore',priority:20,actionId:'restore_armor',conditions:[{kind:'SELF_MISSING_EFFECT',effectId:'test_armor'}]},{id:'strike',priority:10,actionId:'armored_strike',conditions:[{kind:'SELF_HAS_EFFECT',effectId:'test_armor'}]}]};
export const TEST_MONSTER_PREPARED_COMBINED:MonsterDefinition={id:'test-prepared-combined',name:'복합 준비 훈련체',skills:[{id:'qa_charge',name:'TEST_CHARGE_LONG_NAME',description:'Charge UI 검증',cooldown:2,kind:'charge',multiplier:1.2},{id:'qa_counter_stance',name:'TEST_REACTIVE_COUNTER_LONG_NAME',description:'Reactive UI 검증',cooldown:3,kind:'reactive_prepare',reactiveTrigger:'DIRECT_HIT_RECEIVED',reactionSkillId:'qa_counter'},{id:'qa_counter',name:'TEST_COUNTER',description:'반격',cooldown:0,kind:'damage',multiplier:.5}],aiRules:[]};
export const TEST_MONSTER_SHIELD:MonsterDefinition={id:'test-shield-monster',name:'보호막 훈련체',skills:[{id:'shield_stance',name:'TEST_SHIELD 전개',description:'자신에게 보호막 적용',cooldown:3,kind:'effect',effects:[{target:'SELF',effectId:'test_shield'}]},{id:'shield_multi',name:'TEST_SHIELD 삼연격',description:'세 번 공격',cooldown:1,kind:'damage',hits:3,multiplier:.4}],aiRules:[{id:'shield-first',priority:20,actionId:'shield_stance',conditions:[{kind:'SELF_MISSING_EFFECT',effectId:'test_shield'},{kind:'SKILL_READY',skillId:'shield_stance'}]},{id:'multi-second',priority:10,actionId:'shield_multi',conditions:[{kind:'SKILL_READY',skillId:'shield_multi'}]}]};
export const IRON_BOSS_DEFINITIONS:MonsterDefinition[]=[
 {id:'iron_maw_burrower',name:'쇄철턱 굴혈수',skills:[{id:'burrow_charge',name:'굴진 돌격',description:'다음 행동에 강하게 돌진합니다.',cooldown:2,kind:'charge',multiplier:2.05}],aiRules:[{id:'charge',priority:20,actionId:'burrow_charge',conditions:[{kind:'SKILL_READY',skillId:'burrow_charge'}]}]},
 {id:'black_vein_armor_breaker',name:'흑맥갑주 파쇄충',skills:[{id:'armor_up',name:'흑맥 갑주',description:'강한 갑주를 전개합니다.',cooldown:6,kind:'effect',effects:[{target:'SELF',effectId:'iron_armor'}]},{id:'breaker_slam',name:'파쇄 강타',description:'노출된 적을 강타합니다.',cooldown:2,kind:'damage',multiplier:1.55}],aiRules:[{id:'armor',priority:30,actionId:'armor_up',conditions:[{kind:'SELF_MISSING_EFFECT',effectId:'iron_armor'},{kind:'SKILL_READY',skillId:'armor_up'}]},{id:'slam',priority:10,actionId:'breaker_slam',conditions:[{kind:'SKILL_READY',skillId:'breaker_slam'}]}]},
 {id:'echo_devourer',name:'울림포식자',skills:[{id:'echo_mark',name:'울림 각인',description:'플레이어에게 울림을 누적합니다.',cooldown:1,kind:'effect',effects:[{target:'TARGET',effectId:'resonance'}]},{id:'resonant_charge',name:'공명 돌진',description:'울림이 높을 때 준비하는 강공격입니다.',cooldown:3,kind:'charge',multiplier:2.15}],aiRules:[{id:'resonant-charge',priority:30,actionId:'resonant_charge',conditions:[{kind:'TARGET_EFFECT_STACKS_AT_LEAST',effectId:'resonance',requiredStacks:3},{kind:'SKILL_READY',skillId:'resonant_charge'}]},{id:'mark',priority:20,actionId:'echo_mark',conditions:[{kind:'SKILL_READY',skillId:'echo_mark'}]}]},
 {id:'deep_hoist_overseer',name:'심층 권양감독체',skills:[{id:'counter_prepare',name:'권양 반격 준비',description:'직접 피격에 반응합니다.',cooldown:3,kind:'reactive_prepare',reactiveTrigger:'DIRECT_HIT_RECEIVED',reactionSkillId:'counter_strike'},{id:'counter_strike',name:'권양 반격',description:'준비된 즉시 반격입니다.',cooldown:0,kind:'damage',multiplier:.9},{id:'hoist_charge',name:'권양 추락',description:'다음 행동에 압착합니다.',cooldown:3,kind:'charge',multiplier:2.25}],aiRules:[{id:'reactive',priority:30,actionId:'counter_prepare',conditions:[{kind:'SKILL_READY',skillId:'counter_prepare'}]},{id:'charge',priority:20,actionId:'hoist_charge',conditions:[{kind:'SKILL_READY',skillId:'hoist_charge'}]}]},
 {id:'iron_core_pulsator',name:'철심 맥동체',skills:[{id:'core_shield',name:'철심 보호막',description:'철심 보호막을 전개합니다.',cooldown:4,kind:'effect',effects:[{target:'SELF',effectId:'iron_core_shield'}]},{id:'pulse_debuff',name:'압착 맥동',description:'플레이어 방어를 약화합니다.',cooldown:3,kind:'effect',effects:[{target:'TARGET',effectId:'crushing_pressure'}]},{id:'terminal_charge',name:'종말 맥동',description:'저체력에서 준비하는 강공격입니다.',cooldown:3,kind:'charge',multiplier:2.5}],aiRules:[{id:'shield',priority:40,actionId:'core_shield',conditions:[{kind:'SELF_MISSING_EFFECT',effectId:'iron_core_shield'},{kind:'SKILL_READY',skillId:'core_shield'}]},{id:'terminal',priority:30,actionId:'terminal_charge',conditions:[{kind:'SELF_HP_BELOW',value:.5},{kind:'SKILL_READY',skillId:'terminal_charge'}]},{id:'debuff',priority:20,actionId:'pulse_debuff',conditions:[{kind:'TARGET_MISSING_EFFECT',effectId:'crushing_pressure'},{kind:'SKILL_READY',skillId:'pulse_debuff'}]}]}
];
export const RED_BOSS_DEFINITIONS:MonsterDefinition[]=[
 {id:'bloodmane_tracker',name:'핏갈기 추적자',skills:[{id:'blood_charge',name:'혈로 돌진',description:'다음 행동에 강하게 돌진합니다.',cooldown:2,kind:'charge',multiplier:2.05}],aiRules:[{id:'charge',priority:20,actionId:'blood_charge',conditions:[{kind:'SKILL_READY',skillId:'blood_charge'}]}]},
 {id:'redjaw_hide_eater',name:'붉은턱 가죽포식자',skills:[{id:'rip',name:'가죽 찢기',description:'출혈을 누적합니다.',cooldown:1,kind:'damage',multiplier:1.1,effects:[{target:'TARGET',effectId:'fang_wound'}]},{id:'deeper_rend',name:'깊은 할퀴기',description:'출혈이 깊을 때 강타합니다.',cooldown:2,kind:'damage',multiplier:1.7}],aiRules:[{id:'rend',priority:30,actionId:'deeper_rend',conditions:[{kind:'TARGET_EFFECT_STACKS_AT_LEAST',effectId:'fang_wound',requiredStacks:2},{kind:'SKILL_READY',skillId:'deeper_rend'}]},{id:'rip',priority:20,actionId:'rip',conditions:[{kind:'SKILL_READY',skillId:'rip'}]}]},
 {id:'fang_pack_matriarch',name:'송곳니 무리어미',skills:[{id:'matriarch_counter_prepare',name:'무리 반격 준비',description:'직접 피격에 반응합니다.',cooldown:3,kind:'reactive_prepare',reactiveTrigger:'DIRECT_HIT_RECEIVED',reactionSkillId:'matriarch_bite'},{id:'matriarch_bite',name:'무리 반격',description:'준비된 즉시 반격입니다.',cooldown:0,kind:'damage',multiplier:.9},{id:'pack_charge',name:'무리 덮치기',description:'다음 행동에 덮칩니다.',cooldown:3,kind:'charge',multiplier:2.2},{id:'pack_howl',name:'무리 울음',description:'공격을 올립니다.',cooldown:4,kind:'effect',effects:[{target:'SELF',effectId:'attack_up'}]}],aiRules:[{id:'reactive',priority:30,actionId:'matriarch_counter_prepare',conditions:[{kind:'SKILL_READY',skillId:'matriarch_counter_prepare'}]},{id:'charge',priority:20,actionId:'pack_charge',conditions:[{kind:'SKILL_READY',skillId:'pack_charge'}]},{id:'howl',priority:10,actionId:'pack_howl',conditions:[{kind:'SELF_MISSING_EFFECT',effectId:'attack_up'},{kind:'SKILL_READY',skillId:'pack_howl'}]}]},
 {id:'sanctuary_talon_bishop',name:'성소 발톱주교',skills:[{id:'rite_ward',name:'혈의식 수호',description:'수호막을 전개합니다.',cooldown:4,kind:'effect',effects:[{target:'SELF',effectId:'blood_rite_ward'}]},{id:'talon_hex',name:'발톱 저주',description:'플레이어 방어를 약화합니다.',cooldown:3,kind:'effect',effects:[{target:'TARGET',effectId:'crushing_pressure'}]},{id:'bishop_strike',name:'주교 강타',description:'강한 단일 공격입니다.',cooldown:1,kind:'damage',multiplier:1.5}],aiRules:[{id:'shield',priority:40,actionId:'rite_ward',conditions:[{kind:'SELF_MISSING_EFFECT',effectId:'blood_rite_ward'},{kind:'SKILL_READY',skillId:'rite_ward'}]},{id:'debuff',priority:20,actionId:'talon_hex',conditions:[{kind:'TARGET_MISSING_EFFECT',effectId:'crushing_pressure'},{kind:'SKILL_READY',skillId:'talon_hex'}]},{id:'strike',priority:10,actionId:'bishop_strike',conditions:[{kind:'SKILL_READY',skillId:'bishop_strike'}]}]},
 {id:'lord_of_red_fang',name:'적아의 주인',skills:[{id:'red_mantle',name:'적아 외피',description:'외피를 전개합니다.',cooldown:4,kind:'effect',effects:[{target:'SELF',effectId:'red_mantle_shield'}]},{id:'fang_rupture',name:'송곳니 파열',description:'출혈을 누적합니다.',cooldown:1,kind:'damage',multiplier:1.3,effects:[{target:'TARGET',effectId:'fang_wound'}]},{id:'crushing_roar',name:'포식 포효',description:'플레이어 방어를 약화합니다.',cooldown:3,kind:'effect',effects:[{target:'TARGET',effectId:'crushing_pressure'}]},{id:'terminal_hunt',name:'종말 사냥',description:'저체력에서 준비하는 강공격입니다.',cooldown:3,kind:'charge',multiplier:2.5}],aiRules:[{id:'shield',priority:40,actionId:'red_mantle',conditions:[{kind:'SELF_MISSING_EFFECT',effectId:'red_mantle_shield'},{kind:'SKILL_READY',skillId:'red_mantle'}]},{id:'terminal',priority:30,actionId:'terminal_hunt',conditions:[{kind:'SELF_HP_BELOW',value:.5},{kind:'SKILL_READY',skillId:'terminal_hunt'}]},{id:'debuff',priority:20,actionId:'crushing_roar',conditions:[{kind:'TARGET_MISSING_EFFECT',effectId:'crushing_pressure'},{kind:'SKILL_READY',skillId:'crushing_roar'}]},{id:'rupture',priority:10,actionId:'fang_rupture',conditions:[{kind:'SKILL_READY',skillId:'fang_rupture'}]}]}
];
export const DEV_MONSTER_DEFINITIONS=[TEST_MONSTER_BASIC,TEST_MONSTER_CHARGE,TEST_MONSTER_MULTI,TEST_MONSTER_EFFECT,TEST_MONSTER_REACTIVE,TEST_MONSTER_STATUS,TEST_MONSTER_SELF_STATUS,TEST_MONSTER_PREPARED_COMBINED,TEST_MONSTER_SHIELD] as const;
const DEFINITIONS=new Map<string,MonsterDefinition>([...DEV_MONSTER_DEFINITIONS,...IRON_BOSS_DEFINITIONS,...RED_BOSS_DEFINITIONS,...CRYSTAL_MONSTER_DEFINITIONS].map(definition=>[definition.id,definition]));

export const monsterDefinitionById=(id:string)=>DEFINITIONS.get(id);
export const monsterDefinitionFor=(monster:Monster):MonsterDefinition=>monsterDefinitionById(monster.definitionId??'')??{id:monster.definitionId??monster.name,name:monster.name,skills:[],passives:[],aiRules:[]};
export const createMonsterRuntime=(monster:Monster,turnNumber=0):MonsterBattleRuntime=>({definitionId:monsterDefinitionFor(monster).id,skillCooldowns:{},preparedActionId:null,turnNumber});
export const definitionForRuntime=(monster:Monster,runtime:MonsterBattleRuntime)=>monsterDefinitionById(runtime.definitionId)??monsterDefinitionFor(monster);
const ready=(runtime:MonsterBattleRuntime,skill:MonsterSkillDefinition)=>(runtime.skillCooldowns[skill.id]??0)===0;
function condition(item:AiCondition,monster:Monster,targetHp:number,targetMaxHp:number,runtime:MonsterBattleRuntime,skills:MonsterSkillDefinition[],selfEffects:ActiveEffect[],targetEffects:ActiveEffect[]){if('effectId' in item&&!EFFECTS[item.effectId])return false;if(item.kind==='SELF_HP_BELOW')return monster.currentHp/monster.hp<item.value;if(item.kind==='TARGET_HP_BELOW')return targetHp/targetMaxHp<item.value;if(item.kind==='SKILL_READY'){const skill=skills.find(candidate=>candidate.id===item.skillId);return !!skill&&ready(runtime,skill);}if(item.kind==='SELF_HAS_EFFECT')return hasEffect(selfEffects,item.effectId);if(item.kind==='SELF_MISSING_EFFECT')return !hasEffect(selfEffects,item.effectId);if(item.kind==='TARGET_HAS_EFFECT')return hasEffect(targetEffects,item.effectId);if(item.kind==='TARGET_MISSING_EFFECT')return !hasEffect(targetEffects,item.effectId);if(item.kind==='SELF_EFFECT_STACKS_AT_LEAST'||item.kind==='TARGET_EFFECT_STACKS_AT_LEAST'){if(!Number.isSafeInteger(item.requiredStacks)||item.requiredStacks<1)return false;return effectStacks(item.kind==='SELF_EFFECT_STACKS_AT_LEAST'?selfEffects:targetEffects,item.effectId)>=item.requiredStacks;}return false;}
export function chooseMonsterAction(definition:MonsterDefinition,runtime:MonsterBattleRuntime,monster:Monster,targetHp:number,targetMaxHp:number,selfEffects:ActiveEffect[]=[],targetEffects:ActiveEffect[]=[]):MonsterActionDecision {const skills=definition.skills??[];if(runtime.preparedActionId){const skill=skills.find(candidate=>candidate.id===runtime.preparedActionId);if(skill?.kind==='charge')return {kind:'PREPARED_DISCHARGE',skill};}for(const rule of [...(definition.aiRules??[])].sort((a,b)=>b.priority-a.priority||a.id.localeCompare(b.id))){const skill=skills.find(candidate=>candidate.id===rule.actionId);if(skill&&ready(runtime,skill)&&rule.conditions.every(item=>condition(item,monster,targetHp,targetMaxHp,runtime,skills,selfEffects,targetEffects)))return {kind:'ACTIVE_SKILL',skill};}return {kind:'BASIC_ATTACK'};}
export function beginMonsterTurn(runtime:MonsterBattleRuntime){runtime.turnNumber++;for(const id of Object.keys(runtime.skillCooldowns))runtime.skillCooldowns[id]=Math.max(0,runtime.skillCooldowns[id]-1);}
export function useMonsterAction(runtime:MonsterBattleRuntime,decision:MonsterActionDecision){if(decision.kind==='ACTIVE_SKILL'&&decision.skill?.kind==='charge'){runtime.preparedActionId=decision.skill.id;return;}if(decision.kind==='PREPARED_DISCHARGE')runtime.preparedActionId=null;if(decision.skill)runtime.skillCooldowns[decision.skill.id]=Math.max(0,Math.floor(decision.skill.cooldown));}
export const preparedMonsterSkill=(monster:Monster,runtime:MonsterBattleRuntime|null)=>runtime?.preparedActionId?definitionForRuntime(monster,runtime).skills?.find(skill=>skill.id===runtime.preparedActionId):undefined;
export function validateMonsterDefinition(definition:MonsterDefinition){const errors:string[]=[],skills=definition.skills??[],ids=new Set(skills.map(skill=>skill.id));for(const skill of skills){if(skill.kind==='reactive_prepare'){const reaction=skills.find(candidate=>candidate.id===skill.reactionSkillId);if(skill.reactiveTrigger!=='DIRECT_HIT_RECEIVED')errors.push(`${skill.id}: invalid reactive trigger`);if(!reaction)errors.push(`${skill.id}: missing reaction skill`);else if(['reactive_prepare','charge'].includes(reaction.kind))errors.push(`${skill.id}: invalid reaction skill kind`);}for(const effect of skill.effects??[])if(!EFFECTS[effect.effectId])errors.push(`${skill.id}: unknown effect ${effect.effectId}`);}for(const rule of definition.aiRules??[]){if(!ids.has(rule.actionId))errors.push(`${rule.id}: missing action`);for(const item of rule.conditions){if('effectId' in item&&!EFFECTS[item.effectId])errors.push(`${rule.id}: unknown effect ${item.effectId}`);if('requiredStacks' in item&&(!Number.isSafeInteger(item.requiredStacks)||item.requiredStacks<1))errors.push(`${rule.id}: invalid stack threshold`);if(item.kind==='SKILL_READY'&&!ids.has(item.skillId))errors.push(`${rule.id}: missing ready skill`);}}return errors;}

