import type {ExpeditionPreset,GameState,Slot} from '../types';
import {POTIONS,SKILLS,WEAPONS,potionIds} from '../data/config';
export const BASE_PRESET_SLOT_LIMIT=2,PREMIUM_PRESET_SLOT_LIMIT=5,PRESET_NAME_MAX_LENGTH=20;
export const initialPresets=():(ExpeditionPreset|null)[]=>Array(5).fill(null);
export const getPresetSlotLimit=(premium=false)=>premium?PREMIUM_PRESET_SLOT_LIMIT:BASE_PRESET_SLOT_LIMIT;
export const canAccessPresetSlot=(slot:number,limit=getPresetSlotLimit())=>Number.isInteger(slot)&&slot>=1&&slot<=limit&&slot<=PREMIUM_PRESET_SLOT_LIMIT;
const slotOf=(kind:string):Slot=>kind in WEAPONS?'weapon':kind==='armor'?'armor':kind==='boots'?'boots':'accessory';
const normalizedName=(name:string)=>name.trim().slice(0,PRESET_NAME_MAX_LENGTH);
export function snapshotPreset(s:GameState,name:string):ExpeditionPreset|null {const clean=normalizedName(name);if(!clean||s.skills.some(id=>id!==null&&(!SKILLS.some(x=>x.id===id)||!s.learned.includes(id))))return null;return {name:clean,equipment:structuredClone(s.equipped),skills:[...s.skills],potions:{...s.loadout},threshold:s.threshold};}
export function savePreset(s:GameState,slot:number,name?:string,limit=getPresetSlotLimit()):GameState {if(s.expedition)return {...structuredClone(s),notice:'원정 중에는 프리셋을 변경할 수 없습니다.'};if(!canAccessPresetSlot(slot,limit))return {...structuredClone(s),notice:'잠긴 프리셋 슬롯입니다.'};const current=s.expeditionPresets[slot-1],preset=snapshotPreset(s,name??current?.name??`프리셋 ${slot}`);if(!preset)return {...structuredClone(s),notice:'프리셋 이름 또는 스킬 설정을 확인하세요.'};const n=structuredClone(s);n.expeditionPresets[slot-1]=preset;n.notice=preset.name+' 프리셋을 저장했습니다.';return n;}
export function renamePreset(s:GameState,slot:number,name:string,limit=getPresetSlotLimit()):GameState {if(s.expedition)return {...structuredClone(s),notice:'원정 중에는 프리셋을 변경할 수 없습니다.'};if(!canAccessPresetSlot(slot,limit)||!s.expeditionPresets[slot-1])return {...structuredClone(s),notice:'변경할 수 없는 프리셋입니다.'};const clean=normalizedName(name);if(!clean)return {...structuredClone(s),notice:'프리셋 이름을 입력하세요.'};const n=structuredClone(s);n.expeditionPresets[slot-1]!.name=clean;n.notice='프리셋 이름을 변경했습니다.';return n;}
export function validatePresetApply(s:GameState,slot:number,limit=getPresetSlotLimit()):string[]{if(s.expedition)return ['원정 중에는 프리셋을 변경할 수 없습니다.'];if(!canAccessPresetSlot(slot,limit))return ['잠긴 프리셋 슬롯입니다.'];const p=s.expeditionPresets[slot-1];if(!p)return ['비어 있는 프리셋입니다.'];const errors:string[]=[];for(const [key,id] of Object.entries(p.equipment) as [Slot,string|null][])if(id){const item=s.items.find(x=>x.id===id);if(!item||slotOf(item.kind)!==key)errors.push(key+': 보유하지 않음');}for(const id of p.skills)if(id&&(!SKILLS.some(x=>x.id===id)||!s.learned.includes(id)))errors.push('사용할 수 없는 스킬: '+id);for(const potion of potionIds)if(p.potions[potion]>s.potions[potion])errors.push(POTIONS[potion].name+' 포션 필요 '+p.potions[potion]+' / 보유 '+s.potions[potion]);if(p.potions.health+p.potions.regen>30)errors.push('체력과 재생 포션은 합쳐서 30개까지 가능합니다.');return errors;}
export function applyPreset(s:GameState,slot:number,limit=getPresetSlotLimit()):GameState {const errors=validatePresetApply(s,slot,limit);if(errors.length)return {...structuredClone(s),notice:'프리셋을 적용할 수 없습니다. '+errors.join(' · ')};const p=s.expeditionPresets[slot-1]!,n=structuredClone(s);n.equipped={...p.equipment};n.skills=[...p.skills];n.loadout={...p.potions};n.threshold=p.threshold;n.notice=p.name+' 프리셋을 불러왔습니다.';return n;}

