import React,{useEffect,useRef} from 'react';
import type {InventoryViewItem} from '../../game/inventoryView';
import {categoryNames} from '../../game/inventoryView';
export function InventoryIcon({id}:{id:string}){return <img className="inventory-icon" src={'./assets/ui/inventory/'+id+'.png'} alt=""/>;}
export function InventoryDetailSheet({item,onClose,action,disabled,label}:{item:InventoryViewItem;onClose:()=>void;action?:()=>void;disabled?:boolean;label?:string}){
 const root=useRef<HTMLElement>(null);
 useEffect(()=>{const previous=document.activeElement as HTMLElement;root.current?.focus();const handler=(e:KeyboardEvent)=>{if(e.key==='Escape')onClose();if(e.key==='Tab'){const els=root.current?.querySelectorAll<HTMLElement>('button:not(:disabled),[tabindex="0"]');if(!els?.length)return;const first=els[0],last=els[els.length-1];if(e.shiftKey&&(document.activeElement===first||document.activeElement===root.current)){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}};document.addEventListener('keydown',handler);return()=>{document.removeEventListener('keydown',handler);previous?.focus();};},[onClose]);
 return <div className="inventory-overlay" onClick={onClose}><section ref={root} tabIndex={-1} role="dialog" aria-modal="true" aria-labelledby="inventory-detail-title" className="inventory-sheet" onClick={e=>e.stopPropagation()}><div className="sheet-top"><span aria-hidden="true"/><button aria-label="상세 닫기" onClick={onClose}>×</button></div><div className="sheet-heading"><InventoryIcon id={item.iconId}/><div><h2 id="inventory-detail-title">{item.name}</h2><small>{item.tier?'T'+item.tier+' · ':''}{categoryNames[item.category]}{item.equipped?' · 장착 중':''}{item.learned?' · 습득 완료':''}{item.registered?' · 등록 완료':''}</small></div></div><p>{item.description}</p><div className="sheet-facts">수량 {item.quantity.toLocaleString()}{item.enhancement!==undefined?' · 강화 +'+item.enhancement:''}</div>{action&&<button className="primary" disabled={disabled} onClick={action}>{label}</button>}</section></div>;
}
