import React,{useState} from 'react';
import type {InventoryCategory,InventorySort,InventoryFilter} from '../../game/inventoryView';
import {CampBagDialog} from '../camp-bag/CampBagDialog';
export function InventoryToolbar({query,setQuery,sort,setSort,filter,setFilter,category}:{query:string;setQuery:(x:string)=>void;sort:InventorySort;setSort:(x:InventorySort)=>void;filter:InventoryFilter;setFilter:(x:InventoryFilter)=>void;category:InventoryCategory}){
 const [open,setOpen]=useState(false),[panel,setPanel]=useState<'search'|'sort'>('search');
 const statusLabel=category==='equipment'?'장착 중':category==='skillbooks'?'미습득':category==='cosmetics'?'미등록':'';
 return <><div className="inventory-tools"><button onClick={()=>{setPanel('search');setOpen(true);}} aria-label="아이템 검색">{query?'검색: '+query:'아이템 검색'} <span>⌕</span></button><button onClick={()=>{setPanel('sort');setOpen(true);}}>정렬 · 필터{filter.tier||filter.status?' ●':''}</button></div>
 {open&&<CampBagDialog title={panel==='search'?'아이템 검색':'정렬 · 필터'} onClose={()=>setOpen(false)}>
 {panel==='search'?<label className="camp-field">이름으로 찾기<input aria-label="아이템 검색어" value={query} onChange={e=>setQuery(e.target.value)} placeholder="아이템 이름"/></label>:<div className="camp-filter-fields"><label className="camp-field">정렬<select aria-label="아이템 정렬" value={sort} onChange={e=>setSort(e.target.value as InventorySort)}><option value="default">기본 정렬</option><option value="name">이름순</option><option value="tier">등급 높은순</option><option value="quantity">수량 많은순</option></select></label>{['all','equipment','materials','tickets'].includes(category)&&<label className="camp-field">등급<select aria-label="등급 필터" value={filter.tier} onChange={e=>setFilter({...filter,tier:+e.target.value})}>{[0,1,2,3,4,5].map(t=><option key={t} value={t}>{t?'T'+t:'전체'}</option>)}</select></label>}{statusLabel&&<label className="camp-check"><input type="checkbox" checked={filter.status} onChange={e=>setFilter({...filter,status:e.target.checked})}/>{statusLabel}</label>}</div>}
 <div className="camp-dialog-actions"><button onClick={()=>{setQuery('');setSort('default');setFilter({tier:0,status:false});}}>초기화</button><button className="camp-primary" onClick={()=>setOpen(false)}>적용</button></div></CampBagDialog>}</>;
}
