import type {GameState} from '../types';
import {initialState} from '../engine/state';
import {enter} from '../engine/expedition';
import {applyEffect} from '../engine/effects';
import {createMonsterRuntime,TEST_MONSTER_PREPARED_COMBINED,TEST_MONSTER_SHIELD,TEST_MONSTER_STATUS} from '../engine/monsterAi';
import {prepareReactive} from '../engine/reactions';

export type CombatFixtureName='reactive'|'stack'|'status-ai'|'shield'|'shield-expiry';
export function combatFixture(name:string|null):GameState|undefined {if(!['reactive','stack','status-ai','shield','shield-expiry'].includes(name??''))return;const s=enter(initialState(),'ore',1),e=s.expedition!;if(name==='reactive'){const definition=TEST_MONSTER_PREPARED_COMBINED;e.monster={definitionId:definition.id,name:definition.name,hp:500,currentHp:500,attack:16,defense:3,speed:1,skillPower:1};e.monsterRuntime=createMonsterRuntime(e.monster);e.monsterRuntime.preparedActionId='qa_charge';const stance=definition.skills!.find(skill=>skill.id==='qa_counter_stance')!;prepareReactive(e,'monster',definition.id,stance);for(let i=0;i<2;i++)applyEffect(e,'player','test_resonance','monster',e.playerTurn);return s;}if(name==='stack'){for(let i=0;i<2;i++)applyEffect(e,'player','test_resonance','monster',e.playerTurn);for(let i=0;i<2;i++)applyEffect(e,'monster','test_crack','player',e.playerTurn);return s;}if(name==='shield'||name==='shield-expiry'){const definition=TEST_MONSTER_SHIELD;e.monster={definitionId:definition.id,name:definition.name,hp:500,currentHp:500,attack:name==='shield-expiry'?1:12,defense:name==='shield-expiry'?999:0,speed:1,skillPower:1};e.monsterRuntime=createMonsterRuntime(e.monster);applyEffect(e,'player','test_shield','player',e.playerTurn);applyEffect(e,'monster','test_shield','monster',e.monsterTurn);if(name==='shield'){applyEffect(e,'player','poison','monster',e.playerTurn-1);const reactive=TEST_MONSTER_PREPARED_COMBINED.skills!.find(skill=>skill.id==='qa_counter_stance')!;prepareReactive(e,'monster',TEST_MONSTER_PREPARED_COMBINED.id,reactive);}return s;}const definition=TEST_MONSTER_STATUS;e.monster={definitionId:definition.id,name:definition.name,hp:500,currentHp:500,attack:14,defense:2,speed:1,skillPower:1};e.monsterRuntime=createMonsterRuntime(e.monster);for(let i=0;i<3;i++)applyEffect(e,'player','test_resonance','monster',e.playerTurn);return s;}
