import type {Association,AssociationPolicy,GameState} from '../types';
export const ASSOCIATION_CREATION_FEE_SILVER=1000,ASSOCIATION_MEMBER_LIMIT=30,ASSOCIATION_NAME_MIN=2,ASSOCIATION_NAME_MAX=20;
export const FORBIDDEN_ASSOCIATION_NAMES=['탑기록원','노바르 평의회','은저울 상회','네 공방 연맹','청동마차 상단'];
const normalize=(v:string)=>v.trim(),key=(v:string)=>normalize(v).toLocaleLowerCase(),player=(s:GameState)=>s.market.ownerId;
const current=(s:GameState)=>s.association.associations.find(a=>a.associationId===s.association.currentId&&a.status==='ACTIVE');
const event=(a:Association,text:string,at:number)=>a.activityLog.unshift({at,text});
const fail=(s:GameState,notice:string)=>({...s,notice});
export function createAssociation(state:GameState,input:{name:string;description:string;joinPolicy:AssociationPolicy},now=Date.now()):GameState {const s=structuredClone(state),n=normalize(input.name),id=player(s);if(s.association.currentId)return fail(s,'이미 조합에 소속되어 있습니다.');if(!s.market.traderCertified)return fail(s,'조합 창설 자격이 없습니다. 10층 보스 처치 후 안전 귀환이 필요합니다.');if(n.length<ASSOCIATION_NAME_MIN||n.length>ASSOCIATION_NAME_MAX||FORBIDDEN_ASSOCIATION_NAMES.includes(n)||s.association.associations.some(a=>key(a.name)===key(n)))return fail(s,'사용할 수 없는 조합명입니다.');if(s.silver<ASSOCIATION_CREATION_FEE_SILVER)return fail(s,'조합 등록에 필요한 Silver가 부족합니다.');const serial=s.association.nextId++,a:Association={associationId:'association-'+serial,recordNumber:'NR-'+String(serial).padStart(6,'0'),name:n,description:normalize(input.description).slice(0,120),leaderId:id,createdAt:now,notice:'',noticeUpdatedAt:null,joinPolicy:input.joinPolicy,status:'ACTIVE',members:[{playerId:id,role:'LEADER',joinedAt:now}],applications:[],activityLog:[],revenueShareRatePercent:0,treasurySilver:0,treasuryLedger:[]};event(a,'조합이 탑기록원에 등록되었습니다.',now);s.silver-=ASSOCIATION_CREATION_FEE_SILVER;s.association.associations.push(a);s.association.currentId=a.associationId;s.notice=`${a.name} 조합을 창설했습니다.`;return s;}
export function leaveAssociation(state:GameState,now=Date.now()):GameState {const s=structuredClone(state),a=current(s),id=player(s);if(!a)return fail(s,'소속 조합이 없습니다.');if(a.leaderId===id)return fail(s,'조합장은 위임 또는 해산 후에만 탈퇴할 수 있습니다.');a.members=a.members.filter(m=>m.playerId!==id);a.applications=a.applications.filter(x=>x.applicantId!==id);event(a,'조합원이 탈퇴했습니다.',now);s.association.currentId=null;s.notice='조합에서 탈퇴했습니다.';return s;}
export function updateAssociation(state:GameState,input:{description?:string;notice?:string;joinPolicy?:AssociationPolicy},now=Date.now()):GameState {const s=structuredClone(state),a=current(s);if(!a||a.leaderId!==player(s))return fail(s,'조합장만 관리할 수 있습니다.');if(input.description!==undefined){a.description=normalize(input.description).slice(0,120);event(a,'조합 소개를 수정했습니다.',now);}if(input.notice!==undefined){a.notice=normalize(input.notice).slice(0,180);a.noticeUpdatedAt=now;event(a,'조합 공지를 수정했습니다.',now);}if(input.joinPolicy){a.joinPolicy=input.joinPolicy;event(a,'가입 정책을 변경했습니다.',now);}s.notice='조합 정보를 저장했습니다.';return s;}
export function disbandAssociation(state:GameState,now=Date.now()):GameState {const s=structuredClone(state),a=current(s);if(!a||a.leaderId!==player(s))return fail(s,'조합장만 해산할 수 있습니다.');a.status='DISBANDED';a.applications=[];event(a,'조합이 해산되었습니다.',now);s.association.currentId=null;s.notice='조합을 해산했습니다.';return s;}
export function joinAssociation(state:GameState,associationId:string,now=Date.now()):GameState {const s=structuredClone(state),a=s.association.associations.find(x=>x.associationId===associationId&&x.status==='ACTIVE'),id=player(s);if(s.association.currentId)return fail(s,'이미 조합에 소속되어 있습니다.');if(!a)return fail(s,'찾을 수 없는 조합입니다.');if(a.joinPolicy==='CLOSED')return fail(s,'이 조합은 현재 모집을 중지했습니다.');if(a.members.length>=ASSOCIATION_MEMBER_LIMIT)return fail(s,'조합 인원이 가득 찼습니다.');if(a.joinPolicy==='OPEN'){a.members.push({playerId:id,role:'MEMBER',joinedAt:now});s.association.currentId=a.associationId;event(a,'새 조합원이 가입했습니다.',now);s.notice=`${a.name} 조합에 가입했습니다.`;return s;}if(a.applications.some(x=>x.applicantId===id&&x.status==='PENDING'))return fail(s,'이미 가입 신청을 보냈습니다.');a.applications.push({applicationId:`application-${s.association.nextApplicationId++}`,associationId:a.associationId,applicantId:id,createdAt:now,status:'PENDING'});event(a,'새 가입 신청이 도착했습니다.',now);s.notice=`${a.name} 조합에 가입을 신청했습니다.`;return s;}
export function reviewApplication(state:GameState,applicationId:string,accept:boolean,now=Date.now()):GameState {const s=structuredClone(state),a=current(s);if(!a||a.leaderId!==player(s))return fail(s,'조합장만 가입 신청을 처리할 수 있습니다.');const application=a.applications.find(x=>x.applicationId===applicationId&&x.status==='PENDING');if(!application)return fail(s,'처리할 가입 신청이 없습니다.');if(accept&&a.members.length>=ASSOCIATION_MEMBER_LIMIT)return fail(s,'조합 인원이 가득 찼습니다.');application.status=accept?'ACCEPTED':'REJECTED';if(accept){a.members.push({playerId:application.applicantId,role:'MEMBER',joinedAt:now});if(application.applicantId===player(s))s.association.currentId=a.associationId;}event(a,accept?'가입 신청을 승인했습니다.':'가입 신청을 거절했습니다.',now);s.notice=accept?'가입 신청을 승인했습니다.':'가입 신청을 거절했습니다.';return s;}
export function transferLeadership(state:GameState,memberId:string,now=Date.now()):GameState {const s=structuredClone(state),a=current(s),id=player(s);if(!a||a.leaderId!==id)return fail(s,'조합장만 권한을 위임할 수 있습니다.');const member=a.members.find(m=>m.playerId===memberId&&m.role==='MEMBER');if(!member)return fail(s,'위임할 조합원을 찾을 수 없습니다.');a.members.find(m=>m.playerId===id)!.role='MEMBER';member.role='LEADER';a.leaderId=memberId;event(a,'조합장 권한이 위임되었습니다.',now);s.notice='조합장 권한을 위임했습니다.';return s;}
export function kickMember(state:GameState,memberId:string,now=Date.now()):GameState {const s=structuredClone(state),a=current(s);if(!a||a.leaderId!==player(s))return fail(s,'조합장만 조합원을 내보낼 수 있습니다.');if(memberId===a.leaderId)return fail(s,'조합장은 내보낼 수 없습니다.');if(!a.members.some(m=>m.playerId===memberId))return fail(s,'조합원을 찾을 수 없습니다.');a.members=a.members.filter(m=>m.playerId!==memberId);if(memberId===player(s))s.association.currentId=null;event(a,'조합원이 조합에서 제외되었습니다.',now);s.notice='조합원을 내보냈습니다.';return s;}

export function setRevenueShareRate(state:GameState,rate:number,now=Date.now()):GameState{const s=structuredClone(state),a=s.association.associations.find(x=>x.associationId===s.association.currentId&&x.status==='ACTIVE');if(!a||a.leaderId!==s.market.ownerId)return {...s,notice:'조합장만 조합 수익 분담률을 변경할 수 있습니다.'};if(!Number.isInteger(rate)||rate<0||rate>30)return {...s,notice:'조합 수익 분담률은 0%~30% 정수만 설정할 수 있습니다.'};const old=a.revenueShareRatePercent;a.revenueShareRatePercent=rate;event(a,'조합 수익 분담률이 '+old+'%에서 '+rate+'%로 변경되었습니다.',now);s.notice='조합 수익 분담률을 '+rate+'%로 변경했습니다.';return s;}
