const {chromium}=require(process.env.TOWER_PLAYWRIGHT||'C:/Users/양문지역아동센터2/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('node:fs');const assert=require('node:assert/strict');
(async()=>{fs.mkdirSync('qa-v0.1.24',{recursive:true});const browser=await chromium.launch({headless:true,channel:'msedge'});const errors=[],results=[];const page=await browser.newPage();page.on('pageerror',e=>errors.push(e.message));
for(const width of [320,390]){await page.setViewportSize({width,height:844});for(const [name,query] of [['discovery',''],['long','?long=1'],['no-preview','?noPreview=1'],['broken-art','?brokenArt=1'],['no-art','?noArt=1']]){await page.goto('http://127.0.0.1:5174/event-qa.html'+query);await page.locator('.event-screen').waitFor();await page.evaluate(()=>document.fonts.ready);const metrics=await page.evaluate(()=>({width:innerWidth,scroll:document.documentElement.scrollWidth,buttons:[...document.querySelectorAll('.event-choice')].map(b=>({text:b.textContent,height:b.getBoundingClientRect().height}))}));assert.ok(metrics.scroll<=width,JSON.stringify(metrics));if(name==='long')assert.equal(metrics.buttons.length,4);if(name==='no-preview')assert.equal(await page.locator('.event-rewards').count(),0);if(name==='broken-art')await page.locator('.event-art-placeholder').waitFor();await page.screenshot({path:`qa-v0.1.24/${name}-${width}.png`,fullPage:true});results.push({name,width,...metrics});}}
await page.goto('http://127.0.0.1:5174/event-qa.html');await page.locator('#qa-state').waitFor({state:'attached'});const state=JSON.parse(await page.locator('#qa-state').textContent());await page.goto('http://127.0.0.1:5174/');await page.evaluate(s=>localStorage.setItem('tower-record-v1',JSON.stringify(s)),state);await page.reload();await page.getByRole('heading',{name:'버려진 광부의 가방',exact:true}).waitFor();await page.screenshot({path:'qa-v0.1.24/real-game-390.png',fullPage:true});await page.reload();await page.getByRole('heading',{name:'버려진 광부의 가방',exact:true}).waitFor();await page.getByRole('button',{name:/가방을 조사한다/}).click();await page.getByRole('heading',{name:'탐사 결과',exact:true}).waitFor();const saved=await page.evaluate(()=>JSON.parse(localStorage.getItem('tower-record-v1')));assert.equal(saved.expedition.loot.silver,10);assert.equal(saved.silver,0);await page.reload();await page.getByRole('heading',{name:'탐사 결과',exact:true}).waitFor();assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('tower-record-v1')).expedition.loot.silver),10);await page.screenshot({path:'qa-v0.1.24/result-390.png',fullPage:true});await page.getByRole('button',{name:'계속',exact:false}).click();await page.getByRole('button',{name:'기본 공격',exact:true}).waitFor();results.push({name:'real-app-save-reload-next',passed:true});
const live=await page.evaluate(()=>JSON.parse(localStorage.getItem('tower-record-v1')));live.expedition.monster.currentHp=1;live.expedition.events.mode='test';await page.evaluate(s=>localStorage.setItem('tower-record-v1',JSON.stringify(s)),live);await page.reload();await page.getByRole('button',{name:'기본 공격',exact:true}).waitFor();await page.evaluate(()=>{Math.random=()=>0});await page.getByRole('button',{name:'기본 공격',exact:true}).click();await page.locator('.event-screen').waitFor();const pauseState=await page.evaluate(()=>JSON.parse(localStorage.getItem('tower-record-v1')));await page.waitForTimeout(1600);assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('tower-record-v1')).expedition.monster.currentHp),0);assert.equal(pauseState.expedition.events.phase,'EVENT');results.push({name:'real-app-victory-to-event-paused',passed:true});
for(const width of [320,390]){await page.setViewportSize({width,height:844});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));results.push({name:'real-app-width',width,passed:true});}

// Boss challenge and skip use the real EventScreen and shared battle scene.
for(const choice of ['도전한다','지나간다']){await page.goto('http://127.0.0.1:5174/event-qa.html?fixture=TEST_BOSS_EVENT');await page.getByRole('button',{name:new RegExp(choice)}).click();await page.getByRole('button',{name:choice==='도전한다'?'보스에게 향한다':'계속',exact:false}).click();await page.getByRole('button',{name:'기본 공격',exact:true}).waitFor();const s=JSON.parse(await page.locator('#qa-state').textContent());assert.equal(s.expedition.events.activeBossId,choice==='도전한다'?'mining_ogre':null);results.push({name:'boss-'+choice,passed:true});}
assert.deepEqual(errors,[]);fs.writeFileSync('qa-v0.1.24/results.json',JSON.stringify({results,errors},null,2));console.log(JSON.stringify({cases:results.length,errors,passed:true}));await browser.close();})().catch(e=>{console.error(e);process.exit(1)});
