Add-Type -AssemblyName System.Drawing
$dest=Join-Path $PSScriptRoot '../public/assets/ui/inventory'
New-Item -ItemType Directory -Force $dest | Out-Null
$patterns=@{
sword='......ss/.....ss./....ss../...ss.../..ss..../.bb...../..b...../b.......';dagger='......s./.....ss./....ss../...ss.../..bb..../...b..../..b...../........';bow='..bb..../.b..b.../b...b.../b...bs../b...b.../.b..b.../..bb..../........';staff='...gg.../..g.gg../...gg.../....b.../...b..../..b...../.b....../b.......';armor='..ssss../.ssssss./ss.ss.ss/...ss.../..ssss../..ssss../..ssss../........';boots='..bb.bb./..bb.bb./..bb.bb./..bb.bb./..bb.bb./.bbb.bb./bbbbbbb./........';accessory='..ssss../.ss..ss./ss....ss/ss....ss/ss....ss/.ss..ss./..ssss../........';ore='...ss.../..ssss../.ssssss./ssssssss/sssss.ss/.ssssss./..ssss../........';leather='..bb.bb./.bbbbbb./bbbbbbbb/.bbbbbb./.bbbbbb./bbbbbbbb/.bbbbbb./..b..b..';gem='...gg.../..gssg../.gssssg./ggssssgg/.ggssgg./..gggg../...gg.../........';kaleon='.....gg./...gggg./..gggg../...gb.../.ggb..../ggb...../.b....../........';potions='...ss.../...ss.../..ssss../..s..s../.s....s./.sggggs./.sggggs./..ssss..';skillbooks='.bbbbbb./bsSSSSsb/bsSSSSsb/bsSSSSsb/bsSSSSsb/bsSSSSsb/.bbbbbb./........';tickets='.ssssss./.sbbbb s/.ssssss./..ssss../.ssssss./.sbbbb s/.ssssss./........';cosmetics='..ssss../.s....s./..s..s../..bbbb../.bbbbbb./bbbbbbbb/bbbbbbbb/........';other='..bbbb../.bbbbbb./bbbbbbbb/bssssssb/bbbbbbbb/bbbbbbbb/bbbbbbbb/........';all='sss.sss/sss.sss/sss.sss/......./sss.sss/sss.sss/sss.sss/.......';search='..ssss../.ss..ss./.s....s./.ss..ss./..ssss../.....s../......s./.......s';sort='..s..s../.ss..ss./sss..sss/..s..s../..s..s../..s..s../..s..s../........';filter='ssssssss/.ssssss./..ssss../...ss.../...ss.../...ss.../...ss.../........'
}
$aliases=@{equipment='sword';materials='ore';health='potions';regen='potions';attack='potions';defense='potions';haste='potions'}
foreach($k in @($aliases.Keys)){$patterns[$k]=$patterns[$aliases[$k]]}
foreach($key in $patterns.Keys){$bmp=New-Object System.Drawing.Bitmap 32,32; $g=[System.Drawing.Graphics]::FromImage($bmp);$g.Clear([System.Drawing.Color]::Transparent);$rows=$patterns[$key].Split('/');for($y=0;$y -lt $rows.Length;$y++){for($x=0;$x -lt $rows[$y].Length;$x++){ $c=$rows[$y][$x];if($c -eq '.' -or $c -eq ' '){continue};$hex=switch -CaseSensitive ($c){'s'{'#b5aa92'} 'S'{'#847056'} 'b'{'#79543a'} 'g'{switch($key){health{'#ac5148'} attack{'#b37742'} defense{'#6c8190'} haste{'#b69c56'} gem{'#807aa4'} default{'#67866a'}}}};$brush=New-Object System.Drawing.SolidBrush ([System.Drawing.ColorTranslator]::FromHtml($hex));$g.FillRectangle($brush,$x*4,$y*4,4,4);$brush.Dispose()}};$g.Dispose();$bmp.Save((Join-Path $dest ($key+'.png')),[System.Drawing.Imaging.ImageFormat]::Png);$bmp.Dispose()}


