import type {MarketTrade} from '../types';
export type MarketTimeRange='1H'|'6H'|'24H'|'7D'|'30D';
export interface MarketStats {itemId:string;range:MarketTimeRange;tradeCount:number;volume:number;firstPrice:number|null;lastPrice:number|null;highPrice:number|null;lowPrice:number|null;averagePrice:number|null;priceChange:number|null;priceChangePercent:number|null;firstTradeAt:number|null;lastTradeAt:number|null}
export interface MarketChartPoint {timestamp:number;price:number;volume:number}
export const MARKET_RANGE_MS:Record<MarketTimeRange,number>={"1H":3600000,"6H":21600000,"24H":86400000,"7D":604800000,"30D":2592000000};
export const MARKET_BUCKET_MS:Record<MarketTimeRange,number>={"1H":300000,"6H":1800000,"24H":3600000,"7D":21600000,"30D":86400000};
export function tradesInRange(trades:MarketTrade[],itemId:string,range:MarketTimeRange,now=Date.now()){const start=now-MARKET_RANGE_MS[range];return trades.filter(t=>t.itemId===itemId&&t.executedAt>=start&&t.executedAt<=now).slice().sort((a,b)=>a.executedAt-b.executedAt||a.sequence-b.sequence);}
export function marketStats(trades:MarketTrade[],itemId:string,range:MarketTimeRange,now=Date.now()):MarketStats {const data=tradesInRange(trades,itemId,range,now),count=data.length,volume=data.reduce((n,t)=>n+t.quantity,0),turnover=data.reduce((n,t)=>n+t.price*t.quantity,0);if(!count)return {itemId,range,tradeCount:0,volume:0,firstPrice:null,lastPrice:null,highPrice:null,lowPrice:null,averagePrice:null,priceChange:null,priceChangePercent:null,firstTradeAt:null,lastTradeAt:null};const first=data[0],last=data.at(-1)!,prices=data.map(t=>t.price),change=count<2?null:last.price-first.price;return {itemId,range,tradeCount:count,volume,firstPrice:first.price,lastPrice:last.price,highPrice:Math.max(...prices),lowPrice:Math.min(...prices),averagePrice:turnover/volume,priceChange:change,priceChangePercent:change===null?null:change/first.price*100,firstTradeAt:first.executedAt,lastTradeAt:last.executedAt};}
export function marketChart(trades:MarketTrade[],itemId:string,range:MarketTimeRange,now=Date.now()):MarketChartPoint[]{const bucket=MARKET_BUCKET_MS[range],byBucket=new Map<number,MarketChartPoint>();tradesInRange(trades,itemId,range,now).forEach(t=>{const timestamp=Math.floor(t.executedAt/bucket)*bucket,current=byBucket.get(timestamp);byBucket.set(timestamp,{timestamp,price:t.price,volume:(current?.volume||0)+t.quantity});});return [...byBucket.values()].sort((a,b)=>a.timestamp-b.timestamp);}
