import React,{useState} from 'react';
import type {AssociationPolicy,GameState} from '../../game/types';
import {ASSOCIATION_CREATION_FEE_SILVER,createAssociation,disbandAssociation,leaveAssociation,updateAssociation} from '../../game/association/service';
import {Pager,Screen,Segments} from '../../ui/mobile';

type Tab='overview'|'members'|'activity'|'manage';
const tabs=[['overview','개요'],['members','조합원'],['activity','기록'],['manage','관리']] as const;
const PAGE_SIZE=5;
export function AssociationScreen({game,setGame}:{game:GameState;setGame:React.Dispatch<React.SetStateAction<GameState>>}){
 const [name,setName]=useState(''),[description,setDescription]=useState(''),[policy,setPolicy]=useState<AssociationPolicy>('APPROVAL'),[tab,setTab]=useState<Tab>('overview'),[page,setPage]=useState(0);
 const current=game.association.associations.find(a=>a.associationId===game.association.currentId&&a.status==='ACTIVE'),qualified=game.market.traderCertified;
 if(!current)return <Screen eyebrow="NOVAR REGISTRY" title="원정단 등록" meta={<span>{game.silver.toLocaleString()} S</span>}><div className="tc-assoc"><div className="tc-floor-risk">{qualified?'창설 자격 확인됨':'10층 보스 처치 후 안전 귀환이 필요합니다.'} · 등록금 {ASSOCIATION_CREATION_FEE_SILVER.toLocaleString()} S</div><section className="tc-panel strong"><div className="tc-form"><label>원정단명<input value={name} maxLength={20} onChange={e=>setName(e.target.value)} placeholder="2~20자"/></label><label>소개<textarea value={description} maxLength={120} onChange={e=>setDescription(e.target.value)} placeholder="원정단 소개"/></label><label>가입 방식<select value={policy} onChange={e=>setPolicy(e.target.value as AssociationPolicy)}><option value="APPROVAL">승인 가입</option><option value="OPEN">자유 가입</option></select></label></div></section><div/><button className="tc-action" disabled={!qualified||game.silver<ASSOCIATION_CREATION_FEE_SILVER||name.trim().length<2} onClick={()=>setGame(s=>createAssociation(s,{name,description,joinPolicy:policy}))}>원정단 등록</button></div></Screen>;
 const leader=current.leaderId===game.market.ownerId,visibleTabs=leader?tabs:tabs.filter(([id])=>id!=='manage'),source=tab==='members'?current.members:tab==='activity'?current.activityLog:[],pages=Math.max(1,Math.ceil(source.length/PAGE_SIZE)),safe=Math.min(page,pages-1),shown=source.slice(safe*PAGE_SIZE,safe*PAGE_SIZE+PAGE_SIZE);
 return <Screen eyebrow="NOVAR REGISTRY" title={current.name} meta={<span>{leader?'원정단장':'원정단원'}</span>}>
  <div className="tc-assoc">
   <Segments items={visibleTabs as readonly [Tab,string][]} value={tab} onChange={v=>{setTab(v);setPage(0);}} label="원정단 메뉴"/>
   {tab==='overview'&&<section className="tc-panel strong"><div className="tc-panel-title"><b>기록번호 {current.recordNumber}</b><small>{current.members.length}명</small></div><p style={{fontSize:'9px',lineHeight:1.45,margin:'0 0 8px'}}>{current.description||'등록된 소개가 없습니다.'}</p><div className="tc-floor-risk"><b>공지</b><br/>{current.notice||'등록된 공지가 없습니다.'}</div><div className="tc-stat-grid"><div className="tc-stat"><small>가입</small><b>{current.joinPolicy==='OPEN'?'자유':current.joinPolicy==='APPROVAL'?'승인':'중지'}</b></div><div className="tc-stat"><small>역할</small><b>{leader?'단장':'단원'}</b></div></div></section>}
   {(tab==='members'||tab==='activity')&&<><div className="tc-member-list">{shown.map((x:any,i)=>tab==='members'?<div className="tc-member" key={x.playerId}><div><b>{x.playerId===game.market.ownerId?'나':'탐사자 '+x.playerId}</b><small>{x.role==='LEADER'?'단장':'단원'}</small></div><small>{new Date(x.joinedAt).toLocaleDateString('ko-KR')}</small></div>:<div className="tc-member" key={safe*PAGE_SIZE+i}><small>{new Date(x.at).toLocaleString('ko-KR')}</small><span>{x.text}</span></div>)}{Array.from({length:Math.max(0,PAGE_SIZE-shown.length)},(_,i)=><div className="tc-member" key={'blank'+i}/>)}</div><Pager page={safe} count={pages} onChange={setPage}/></>}
   {tab==='manage'&&leader&&<section className="tc-panel"><div className="tc-form"><label>소개<textarea defaultValue={current.description} maxLength={120} onBlur={e=>setGame(s=>updateAssociation(s,{description:e.target.value}))}/></label><label>공지<textarea defaultValue={current.notice} maxLength={180} onBlur={e=>setGame(s=>updateAssociation(s,{notice:e.target.value}))}/></label><label>가입 방식<select value={current.joinPolicy} onChange={e=>setGame(s=>updateAssociation(s,{joinPolicy:e.target.value as AssociationPolicy}))}><option value="APPROVAL">승인 가입</option><option value="OPEN">자유 가입</option><option value="CLOSED">모집 중지</option></select></label></div><button className="tc-action danger" onClick={()=>{if(window.confirm('원정단을 해산하시겠습니까?'))setGame(s=>disbandAssociation(s));}}>원정단 해산</button></section>}
   {tab==='overview'&&!leader&&<button className="tc-action danger" onClick={()=>{if(window.confirm('원정단에서 탈퇴하시겠습니까?'))setGame(s=>leaveAssociation(s));}}>원정단 탈퇴</button>}
  </div>
 </Screen>;
}
